#pragma checksum "/home/runner/workspace/RobloxWebSite/UserControls/Modals/GenericModal.ascx" "{406ea660-64cf-4c82-b6f0-42d48172a799}" "997683B63B2EC0FB82F54540C63BF0B6"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
    using System;
    using System.Collections;
    using System.Collections.Specialized;
    using System.Configuration;
    using System.Text;
    using System.Text.RegularExpressions;
    using System.Web;
    using System.Web.Caching;
    using System.Web.SessionState;
    using System.Web.Security;
    using System.Web.Profile;
    using System.Web.UI;
    using System.Web.UI.WebControls;
    using System.Web.UI.HtmlControls;
    using Roblox.Website;
    using Roblox.Web.Code;
    
    
    public class usercontrols_modals_genericmodal_ascx : global::Roblox.Website.UserControls.Modals.GenericModal {
        
        private static bool @__initialized = false;
        
        private static object @__stringResource = null;
        
        private static int @__autoHandlers;
        
        public usercontrols_modals_genericmodal_ascx() {
            ((global::Roblox.Website.UserControls.Modals.GenericModal)(this)).AppRelativeVirtualPath = "~/UserControls/Modals/GenericModal.ascx";
            if ((global::ASP.usercontrols_modals_genericmodal_ascx.@__initialized == false)) {
                global::ASP.usercontrols_modals_genericmodal_ascx.@__initialized = true;
            }
        }
        
        [System.Obsolete()]
        protected override int AutoHandlers {
            get {
                return ASP.usercontrols_modals_genericmodal_ascx.@__autoHandlers;
            }
            set {
                ASP.usercontrols_modals_genericmodal_ascx.@__autoHandlers = value;
            }
        }
        
        protected System.Web.HttpApplication ApplicationInstance {
            get {
                return ((System.Web.HttpApplication)(this.Context.ApplicationInstance));
            }
        }
        
        protected System.Web.Profile.DefaultProfile Profile {
            get {
                return ((System.Web.Profile.DefaultProfile)(this.Context.Profile));
            }
        }
        
        private void @__BuildControlTree(usercontrols_modals_genericmodal_ascx @__ctrl) {
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/Modals/GenericModal.ascx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"<div class=""GenericModal modalPopup unifiedModal smallModal"" style=""display:none;"">
    <div class=""Title""></div>
    <div class=""GenericModalBody"">
        <div>
            <div class=""ImageContainer roblox-item-image""  data-image-size=""small"" data-no-overlays data-no-click>
                <img class=""GenericModalImage"" alt=""generic image"" />
            </div>
            <div class=""Message""></div>  
            <div style=""clear:both""></div>
        </div>
        <div class=""GenericModalButtonContainer"">
            <a class=""ImageButton btn-neutral btn-large roblox-ok"" >OK<span class=""btn-text"">OK</span></a> 
        </div>  
    </div>
</div>"));
            
            #line default
            #line hidden
        }
        
        protected override void FrameworkInitialize() {
            base.FrameworkInitialize();
            this.SetStringResourcePointer(global::ASP.usercontrols_modals_genericmodal_ascx.@__stringResource, 0);
            this.@__BuildControlTree(this);
        }
    }
}
