#pragma checksum "/home/runner/workspace/RobloxWebSite/UserControls/Modals/InsufficientCurrencyOrBC/BCOnlyModal.ascx" "{406ea660-64cf-4c82-b6f0-42d48172a799}" "57A98EB9A7150C6081B14E17C60AC114"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
    using System;
    using System.Collections;
    using System.Collections.Specialized;
    using System.Configuration;
    using System.Text;
    using System.Text.RegularExpressions;
    using System.Web;
    using System.Web.Caching;
    using System.Web.SessionState;
    using System.Web.Security;
    using System.Web.Profile;
    using System.Web.UI;
    using System.Web.UI.WebControls;
    using System.Web.UI.HtmlControls;
    using Roblox.Website;
    using Roblox.Web.Code;
    
    
    public class usercontrols_modals_insufficientcurrencyorbc_bconlymodal_ascx : global::Roblox.Website.UserControls.Modals.InsufficientCurrencyOrBC.BCOnlyModal {
        
        private static bool @__initialized = false;
        
        private static object @__stringResource = null;
        
        private static int @__autoHandlers;
        
        
        #line 44 "/home/runner/workspace/RobloxWebSite/UserControls/Modals/InsufficientCurrencyOrBC/BCOnlyModal.ascx"
        protected global::ASP.usercontrols_modals_genericmodal_ascx _bctrl_10;
        
        #line default
        #line hidden
        
        public usercontrols_modals_insufficientcurrencyorbc_bconlymodal_ascx() {
            ((global::Roblox.Website.UserControls.Modals.InsufficientCurrencyOrBC.BCOnlyModal)(this)).AppRelativeVirtualPath = "~/UserControls/Modals/InsufficientCurrencyOrBC/BCOnlyModal.ascx";
            if ((global::ASP.usercontrols_modals_insufficientcurrencyorbc_bconlymodal_ascx.@__initialized == false)) {
                global::ASP.usercontrols_modals_insufficientcurrencyorbc_bconlymodal_ascx.@__initialized = true;
            }
        }
        
        [System.Obsolete()]
        protected override int AutoHandlers {
            get {
                return ASP.usercontrols_modals_insufficientcurrencyorbc_bconlymodal_ascx.@__autoHandlers;
            }
            set {
                ASP.usercontrols_modals_insufficientcurrencyorbc_bconlymodal_ascx.@__autoHandlers = value;
            }
        }
        
        protected System.Web.HttpApplication ApplicationInstance {
            get {
                return ((System.Web.HttpApplication)(this.Context.ApplicationInstance));
            }
        }
        
        protected System.Web.Profile.DefaultProfile Profile {
            get {
                return ((System.Web.Profile.DefaultProfile)(this.Context.Profile));
            }
        }
        
        private void @__BuildControlTree(usercontrols_modals_insufficientcurrencyorbc_bconlymodal_ascx @__ctrl) {
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/Modals/InsufficientCurrencyOrBC/BCOnlyModal.ascx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("<div id=\"BCOnlyModal\" class=\"modalPopup unifiedModal smallModal\" style=\"display:n" +
                        "one;\">\n \t<div style=\"margin:4px 0px;\">\n        <span>Builders Club Only</span>\n " +
                        "   </div>\n    <div class=\"simplemodal-close\">\n        <a class=\"ImageButton clos" +
                        "eBtnCircle_20h\" style=\"margin-left:400px;\"></a>\n    </div>\n    <div class=\"unifi" +
                        "edModalContent\" style=\"padding-top:5px; margin-bottom: 3px; margin-left: 3px; ma" +
                        "rgin-right: 3px\">\n        <div class=\"ImageContainer\" >\n            <img class=\"" +
                        "GenericModalImage BCModalImage\" alt=\"Builder\'s Club\" src=\"http://images.rbxcdn.c" +
                        "om/ae345c0d59b00329758518edc104d573.png\" />\n            <div id=\"BCMessageDiv\" c" +
                        "lass=\"BCMessage Message\">\n                Builders Club membership is required t" +
                        "o play in this place.\n            </div>\n        </div>\n        <div style=\"clea" +
                        "r:both;\"></div>\n        <div style=\"clear:both;\"></div>\n        <div class=\"Gene" +
                        "ricModalButtonContainer\" style=\"padding-bottom: 13px\">\n            <div style=\"t" +
                        "ext-align:center\">\n                <a id=\"BClink\" href=\"/Upgrades/BuildersClubMe" +
                        "mberships.aspx\" class=\"btn-primary btn-large\">Upgrade Now</a>\n            </div>" +
                        "\n            <div style=\"clear:both;\"></div>\n        </div>\n        <div style=\"" +
                        "clear:both;\"></div>\n    </div>\n</div>\n\n<script type=\"text/javascript\">\n    funct" +
                        "ion showBCOnlyModal(modalId) {\n        var modalProperties = { overlayClose: tru" +
                        "e, escClose: true, opacity: 80, overlayCss: { backgroundColor: \"#000\" } };\n     " +
                        "   if (typeof modalId === \"undefined\")\n            $(\"#BCOnlyModal\").modal(modal" +
                        "Properties);\n        else\n            $(\"#\" + modalId).modal(modalProperties);\n " +
                        "   }\n    $(document).ready(function () {\n        $(\'#VOID\').click(function () {\n" +
                        "            showBCOnlyModal(\"BCOnlyModal\");\n            return false;\n        })" +
                        ";\n    });\n</script>\n "));
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/Modals/InsufficientCurrencyOrBC/BCOnlyModal.ascx"
            this.@__BuildControl__bctrl_10();
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/Modals/InsufficientCurrencyOrBC/BCOnlyModal.ascx"
            @__parser.AddParsedSubObject(this._bctrl_10);
            
            #line default
            #line hidden
        }
        
        private global::ASP.usercontrols_modals_genericmodal_ascx @__BuildControl__bctrl_10() {
            global::ASP.usercontrols_modals_genericmodal_ascx @__ctrl;
            
            #line 44 "/home/runner/workspace/RobloxWebSite/UserControls/Modals/InsufficientCurrencyOrBC/BCOnlyModal.ascx"
            @__ctrl = new global::ASP.usercontrols_modals_genericmodal_ascx();
            
            #line default
            #line hidden
            
            #line 44 "/home/runner/workspace/RobloxWebSite/UserControls/Modals/InsufficientCurrencyOrBC/BCOnlyModal.ascx"
            this._bctrl_10 = @__ctrl;
            
            #line default
            #line hidden
            this._bctrl_10.InitializeAsUserControl(this.Page);
            return @__ctrl;
        }
        
        protected override void FrameworkInitialize() {
            base.FrameworkInitialize();
            this.SetStringResourcePointer(global::ASP.usercontrols_modals_insufficientcurrencyorbc_bconlymodal_ascx.@__stringResource, 0);
            this.@__BuildControlTree(this);
        }
    }
}
