#pragma checksum "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/Footer.ascx" "{406ea660-64cf-4c82-b6f0-42d48172a799}" "D0CAB71919A584F4CFF314EC962B1515"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
    using System;
    using System.Collections;
    using System.Collections.Specialized;
    using System.Configuration;
    using System.Text;
    using System.Text.RegularExpressions;
    using System.Web;
    using System.Web.Caching;
    using System.Web.SessionState;
    using System.Web.Security;
    using System.Web.Profile;
    using System.Web.UI;
    using System.Web.UI.WebControls;
    using System.Web.UI.HtmlControls;
    using Roblox.Website;
    using Roblox.Web.Code;
    
    
    public class usercontrols_navigation_footer_ascx : global::Roblox.Website.UserControls.Navigation.Footer {
        
        private static bool @__initialized = false;
        
        private static object @__stringResource = null;
        
        private static int @__autoHandlers;
        
        
        #line 4 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/Footer.ascx"
        protected global::System.Web.UI.WebControls.Literal _bctrl_32;
        
        #line default
        #line hidden
        
        
        #line 6 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/Footer.ascx"
        protected global::System.Web.UI.WebControls.Literal _bctrl_33;
        
        #line default
        #line hidden
        
        
        #line 8 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/Footer.ascx"
        protected global::System.Web.UI.WebControls.Literal _bctrl_34;
        
        #line default
        #line hidden
        
        
        #line 10 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/Footer.ascx"
        protected global::System.Web.UI.WebControls.Literal _bctrl_35;
        
        #line default
        #line hidden
        
        
        #line 12 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/Footer.ascx"
        protected global::System.Web.UI.WebControls.Literal _bctrl_36;
        
        #line default
        #line hidden
        
        
        #line 14 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/Footer.ascx"
        protected global::System.Web.UI.WebControls.Literal _bctrl_37;
        
        #line default
        #line hidden
        
        
        #line 16 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/Footer.ascx"
        protected global::System.Web.UI.WebControls.Literal _bctrl_38;
        
        #line default
        #line hidden
        
        
        #line 18 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/Footer.ascx"
        protected global::System.Web.UI.WebControls.Literal _bctrl_39;
        
        #line default
        #line hidden
        
        
        #line 20 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/Footer.ascx"
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl _bctrl_40;
        
        #line default
        #line hidden
        
        
        #line 30 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/Footer.ascx"
        protected global::System.Web.UI.WebControls.Literal _bctrl_41;
        
        #line default
        #line hidden
        
        
        #line 32 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/Footer.ascx"
        protected global::System.Web.UI.WebControls.Literal _bctrl_42;
        
        #line default
        #line hidden
        
        
        #line 34 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/Footer.ascx"
        protected global::System.Web.UI.WebControls.Literal _bctrl_43;
        
        #line default
        #line hidden
        
        
        #line 36 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/Footer.ascx"
        protected global::System.Web.UI.WebControls.Literal _bctrl_44;
        
        #line default
        #line hidden
        
        
        #line 38 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/Footer.ascx"
        protected global::System.Web.UI.WebControls.Literal _bctrl_45;
        
        #line default
        #line hidden
        
        
        #line 40 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/Footer.ascx"
        protected global::System.Web.UI.WebControls.Literal _bctrl_46;
        
        #line default
        #line hidden
        
        
        #line 42 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/Footer.ascx"
        protected global::System.Web.UI.WebControls.Literal _bctrl_47;
        
        #line default
        #line hidden
        
        
        #line 44 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/Footer.ascx"
        protected global::System.Web.UI.WebControls.Literal _bctrl_48;
        
        #line default
        #line hidden
        
        
        #line 46 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/Footer.ascx"
        protected global::System.Web.UI.WebControls.Literal _bctrl_49;
        
        #line default
        #line hidden
        
        
        #line 48 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/Footer.ascx"
        protected global::System.Web.UI.WebControls.Literal _bctrl_50;
        
        #line default
        #line hidden
        
        
        #line 50 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/Footer.ascx"
        protected global::System.Web.UI.WebControls.Literal _bctrl_51;
        
        #line default
        #line hidden
        
        
        #line 52 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/Footer.ascx"
        protected global::System.Web.UI.WebControls.Literal _bctrl_52;
        
        #line default
        #line hidden
        
        
        #line 54 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/Footer.ascx"
        protected global::System.Web.UI.WebControls.Literal _bctrl_53;
        
        #line default
        #line hidden
        
        
        #line 56 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/Footer.ascx"
        protected global::System.Web.UI.WebControls.Literal _bctrl_54;
        
        #line default
        #line hidden
        
        
        #line 58 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/Footer.ascx"
        protected global::System.Web.UI.WebControls.Literal _bctrl_55;
        
        #line default
        #line hidden
        
        public usercontrols_navigation_footer_ascx() {
            ((global::Roblox.Website.UserControls.Navigation.Footer)(this)).AppRelativeVirtualPath = "~/UserControls/Navigation/Footer.ascx";
            if ((global::ASP.usercontrols_navigation_footer_ascx.@__initialized == false)) {
                global::ASP.usercontrols_navigation_footer_ascx.@__initialized = true;
            }
        }
        
        [System.Obsolete()]
        protected override int AutoHandlers {
            get {
                return ASP.usercontrols_navigation_footer_ascx.@__autoHandlers;
            }
            set {
                ASP.usercontrols_navigation_footer_ascx.@__autoHandlers = value;
            }
        }
        
        protected System.Web.HttpApplication ApplicationInstance {
            get {
                return ((System.Web.HttpApplication)(this.Context.ApplicationInstance));
            }
        }
        
        protected System.Web.Profile.DefaultProfile Profile {
            get {
                return ((System.Web.Profile.DefaultProfile)(this.Context.Profile));
            }
        }
        
        private void @__BuildControlTree(usercontrols_navigation_footer_ascx @__ctrl) {
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/Footer.ascx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("<div id=\"Footer\" class=\"footer-container\">\n    <div class=\"FooterNav\">\n        <a" +
                        " href=\"/info/Privacy.aspx\"><b>"));
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/Footer.ascx"
            this.@__BuildControl__bctrl_32();
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/Footer.ascx"
            @__parser.AddParsedSubObject(this._bctrl_32);
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/Footer.ascx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("</b></a>\n        &nbsp;|&nbsp; \n        <a href=\"http://corp.roblox.com/advertise" +
                        "-on-roblox\">"));
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/Footer.ascx"
            this.@__BuildControl__bctrl_33();
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/Footer.ascx"
            @__parser.AddParsedSubObject(this._bctrl_33);
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/Footer.ascx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("</a>\n        &nbsp;|&nbsp; \n        <a href=\"http://corp.roblox.com/roblox-press\"" +
                        ">"));
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/Footer.ascx"
            this.@__BuildControl__bctrl_34();
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/Footer.ascx"
            @__parser.AddParsedSubObject(this._bctrl_34);
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/Footer.ascx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("</a>\n        &nbsp;|&nbsp; \n        <a href=\"http://corp.roblox.com/contact-us\">"));
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/Footer.ascx"
            this.@__BuildControl__bctrl_35();
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/Footer.ascx"
            @__parser.AddParsedSubObject(this._bctrl_35);
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/Footer.ascx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("</a>\n        &nbsp;|&nbsp;\n        <a href=\"http://corp.roblox.com/\">"));
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/Footer.ascx"
            this.@__BuildControl__bctrl_36();
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/Footer.ascx"
            @__parser.AddParsedSubObject(this._bctrl_36);
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/Footer.ascx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("</a>\n        &nbsp;|&nbsp;\n        <a href=\"http://blog.roblox.com\">"));
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/Footer.ascx"
            this.@__BuildControl__bctrl_37();
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/Footer.ascx"
            @__parser.AddParsedSubObject(this._bctrl_37);
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/Footer.ascx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("</a>\n        &nbsp;|&nbsp;\n        <a href=\"http://corp.roblox.com/jobs\">"));
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/Footer.ascx"
            this.@__BuildControl__bctrl_38();
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/Footer.ascx"
            @__parser.AddParsedSubObject(this._bctrl_38);
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/Footer.ascx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("</a>\n        &nbsp;|&nbsp;\n        <a href=\"/Parents.aspx\">"));
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/Footer.ascx"
            this.@__BuildControl__bctrl_39();
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/Footer.ascx"
            @__parser.AddParsedSubObject(this._bctrl_39);
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/Footer.ascx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("</a>  \n            <span class=\"LanguageOptionElement\">&nbsp;|&nbsp;</span> \n    " +
                        "        "));
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/Footer.ascx"
            this.@__BuildControl__bctrl_40();
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/Footer.ascx"
            @__parser.AddParsedSubObject(this._bctrl_40);
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/Footer.ascx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(" \n    </div>\n    <div class=\"FooterNav\">\n        <div id=\"SEOGenreLinks\" class=\"S" +
                        "EOGenreLinks\">\n                  <a href=\"/all-games\">"));
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/Footer.ascx"
            this.@__BuildControl__bctrl_41();
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/Footer.ascx"
            @__parser.AddParsedSubObject(this._bctrl_41);
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/Footer.ascx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("</a> \n                      <span>|</span>\n                  <a href=\"/building-g" +
                        "ames\">"));
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/Footer.ascx"
            this.@__BuildControl__bctrl_42();
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/Footer.ascx"
            @__parser.AddParsedSubObject(this._bctrl_42);
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/Footer.ascx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("</a> \n                      <span>|</span>\n                  <a href=\"/horror-gam" +
                        "es\">"));
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/Footer.ascx"
            this.@__BuildControl__bctrl_43();
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/Footer.ascx"
            @__parser.AddParsedSubObject(this._bctrl_43);
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/Footer.ascx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("</a> \n                      <span>|</span>\n                  <a href=\"/town-and-c" +
                        "ity-games\">"));
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/Footer.ascx"
            this.@__BuildControl__bctrl_44();
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/Footer.ascx"
            @__parser.AddParsedSubObject(this._bctrl_44);
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/Footer.ascx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("</a> \n                      <span>|</span>\n                  <a href=\"/military-g" +
                        "ames\">"));
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/Footer.ascx"
            this.@__BuildControl__bctrl_45();
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/Footer.ascx"
            @__parser.AddParsedSubObject(this._bctrl_45);
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/Footer.ascx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("</a> \n                      <span>|</span>\n                  <a href=\"/comedy-gam" +
                        "es\">"));
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/Footer.ascx"
            this.@__BuildControl__bctrl_46();
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/Footer.ascx"
            @__parser.AddParsedSubObject(this._bctrl_46);
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/Footer.ascx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("</a> \n                      <span>|</span>\n                  <a href=\"/medieval-g" +
                        "ames\">"));
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/Footer.ascx"
            this.@__BuildControl__bctrl_47();
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/Footer.ascx"
            @__parser.AddParsedSubObject(this._bctrl_47);
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/Footer.ascx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("</a> \n                      <span>|</span>\n                  <a href=\"/adventure-" +
                        "games\">"));
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/Footer.ascx"
            this.@__BuildControl__bctrl_48();
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/Footer.ascx"
            @__parser.AddParsedSubObject(this._bctrl_48);
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/Footer.ascx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("</a> \n                      <span>|</span>\n                  <a href=\"/sci-fi-gam" +
                        "es\">"));
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/Footer.ascx"
            this.@__BuildControl__bctrl_49();
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/Footer.ascx"
            @__parser.AddParsedSubObject(this._bctrl_49);
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/Footer.ascx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("</a> \n                      <span>|</span>\n                  <a href=\"/naval-game" +
                        "s\">"));
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/Footer.ascx"
            this.@__BuildControl__bctrl_50();
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/Footer.ascx"
            @__parser.AddParsedSubObject(this._bctrl_50);
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/Footer.ascx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("</a> \n                      <span>|</span>\n                  <a href=\"/fps-games\"" +
                        ">"));
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/Footer.ascx"
            this.@__BuildControl__bctrl_51();
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/Footer.ascx"
            @__parser.AddParsedSubObject(this._bctrl_51);
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/Footer.ascx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("</a> \n                      <span>|</span>\n                  <a href=\"/rpg-games\"" +
                        ">"));
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/Footer.ascx"
            this.@__BuildControl__bctrl_52();
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/Footer.ascx"
            @__parser.AddParsedSubObject(this._bctrl_52);
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/Footer.ascx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("</a> \n                      <span>|</span>\n                  <a href=\"/sports-gam" +
                        "es\">"));
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/Footer.ascx"
            this.@__BuildControl__bctrl_53();
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/Footer.ascx"
            @__parser.AddParsedSubObject(this._bctrl_53);
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/Footer.ascx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("</a> \n                      <span>|</span>\n                  <a href=\"/fighting-g" +
                        "ames\">"));
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/Footer.ascx"
            this.@__BuildControl__bctrl_54();
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/Footer.ascx"
            @__parser.AddParsedSubObject(this._bctrl_54);
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/Footer.ascx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("</a> \n                      <span>|</span>\n                  <a href=\"/western-ga" +
                        "mes\">"));
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/Footer.ascx"
            this.@__BuildControl__bctrl_55();
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/Footer.ascx"
            @__parser.AddParsedSubObject(this._bctrl_55);
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/Footer.ascx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"</a> 
        </div>
    </div>
    <div class=""legal"">
        <div class=""left"">
            <div id=""a15b1695-1a5a-49a9-94f0-9cd25ae6c3b2"">
                <a href=""http://www.truste.org/ivalidate.php?url=www.roblox.com&sealid=105"" id=""TrusteeSeal""><img src=""/Images/TRUSTe/seal.png"" border=""0"" id=""TrusteLogo"" alt=""Truste"" /></a>
            </div>
        </div>
        <div class=""right"">
            <p class=""Legalese"">
    ROBLOX, ""Online Building Toy"", characters, logos, names, and all related indicia are trademarks of <a href=""http://corp.roblox.com/"" ref=""footer-smallabout"">ROBLOX Corporation</a>, &copy;"));
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/Footer.ascx"
            this.@__BuildControl_YearLabel();
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/Footer.ascx"
            @__parser.AddParsedSubObject(this.YearLabel);
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/Footer.ascx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@". Patents pending.
    ROBLOX is not sponsored, authorized or endorsed by any producer of plastic building bricks, including The LEGO Group, MEGA Brands, and K'Nex, and no resemblance to the products of these companies is intended. Use of this site signifies your acceptance of the <a href=""/info/terms-of-service"" ref=""footer-terms"">Terms and Conditions</a>.
</p>
        </div>
        <div class=""clear""></div>
    </div>
</div>"));
            
            #line default
            #line hidden
        }
        
        private global::System.Web.UI.WebControls.Literal @__BuildControl__bctrl_32() {
            global::System.Web.UI.WebControls.Literal @__ctrl;
            
            #line 4 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/Footer.ascx"
            @__ctrl = new global::System.Web.UI.WebControls.Literal();
            
            #line default
            #line hidden
            
            #line 4 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/Footer.ascx"
            this._bctrl_32 = @__ctrl;
            
            #line default
            #line hidden
            
            #line 4 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/Footer.ascx"
            @__ctrl.Text = global::System.Convert.ToString(global::System.Convert.ToString(this.GetLocalResourceObject("Privacy Policy"), System.Globalization.CultureInfo.CurrentCulture), System.Globalization.CultureInfo.CurrentCulture);
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        private global::System.Web.UI.WebControls.Literal @__BuildControl__bctrl_33() {
            global::System.Web.UI.WebControls.Literal @__ctrl;
            
            #line 6 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/Footer.ascx"
            @__ctrl = new global::System.Web.UI.WebControls.Literal();
            
            #line default
            #line hidden
            
            #line 6 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/Footer.ascx"
            this._bctrl_33 = @__ctrl;
            
            #line default
            #line hidden
            
            #line 6 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/Footer.ascx"
            @__ctrl.Text = global::System.Convert.ToString(global::System.Convert.ToString(this.GetLocalResourceObject("Advertise with Us"), System.Globalization.CultureInfo.CurrentCulture), System.Globalization.CultureInfo.CurrentCulture);
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        private global::System.Web.UI.WebControls.Literal @__BuildControl__bctrl_34() {
            global::System.Web.UI.WebControls.Literal @__ctrl;
            
            #line 8 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/Footer.ascx"
            @__ctrl = new global::System.Web.UI.WebControls.Literal();
            
            #line default
            #line hidden
            
            #line 8 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/Footer.ascx"
            this._bctrl_34 = @__ctrl;
            
            #line default
            #line hidden
            
            #line 8 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/Footer.ascx"
            @__ctrl.Text = global::System.Convert.ToString(global::System.Convert.ToString(this.GetLocalResourceObject("Press"), System.Globalization.CultureInfo.CurrentCulture), System.Globalization.CultureInfo.CurrentCulture);
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        private global::System.Web.UI.WebControls.Literal @__BuildControl__bctrl_35() {
            global::System.Web.UI.WebControls.Literal @__ctrl;
            
            #line 10 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/Footer.ascx"
            @__ctrl = new global::System.Web.UI.WebControls.Literal();
            
            #line default
            #line hidden
            
            #line 10 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/Footer.ascx"
            this._bctrl_35 = @__ctrl;
            
            #line default
            #line hidden
            
            #line 10 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/Footer.ascx"
            @__ctrl.Text = global::System.Convert.ToString(global::System.Convert.ToString(this.GetLocalResourceObject("Contact Us"), System.Globalization.CultureInfo.CurrentCulture), System.Globalization.CultureInfo.CurrentCulture);
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        private global::System.Web.UI.WebControls.Literal @__BuildControl__bctrl_36() {
            global::System.Web.UI.WebControls.Literal @__ctrl;
            
            #line 12 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/Footer.ascx"
            @__ctrl = new global::System.Web.UI.WebControls.Literal();
            
            #line default
            #line hidden
            
            #line 12 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/Footer.ascx"
            this._bctrl_36 = @__ctrl;
            
            #line default
            #line hidden
            
            #line 12 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/Footer.ascx"
            @__ctrl.Text = global::System.Convert.ToString(global::System.Convert.ToString(this.GetLocalResourceObject("About Us"), System.Globalization.CultureInfo.CurrentCulture), System.Globalization.CultureInfo.CurrentCulture);
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        private global::System.Web.UI.WebControls.Literal @__BuildControl__bctrl_37() {
            global::System.Web.UI.WebControls.Literal @__ctrl;
            
            #line 14 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/Footer.ascx"
            @__ctrl = new global::System.Web.UI.WebControls.Literal();
            
            #line default
            #line hidden
            
            #line 14 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/Footer.ascx"
            this._bctrl_37 = @__ctrl;
            
            #line default
            #line hidden
            
            #line 14 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/Footer.ascx"
            @__ctrl.Text = global::System.Convert.ToString(global::System.Convert.ToString(this.GetLocalResourceObject("Blog"), System.Globalization.CultureInfo.CurrentCulture), System.Globalization.CultureInfo.CurrentCulture);
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        private global::System.Web.UI.WebControls.Literal @__BuildControl__bctrl_38() {
            global::System.Web.UI.WebControls.Literal @__ctrl;
            
            #line 16 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/Footer.ascx"
            @__ctrl = new global::System.Web.UI.WebControls.Literal();
            
            #line default
            #line hidden
            
            #line 16 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/Footer.ascx"
            this._bctrl_38 = @__ctrl;
            
            #line default
            #line hidden
            
            #line 16 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/Footer.ascx"
            @__ctrl.Text = global::System.Convert.ToString(global::System.Convert.ToString(this.GetLocalResourceObject("Jobs"), System.Globalization.CultureInfo.CurrentCulture), System.Globalization.CultureInfo.CurrentCulture);
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        private global::System.Web.UI.WebControls.Literal @__BuildControl__bctrl_39() {
            global::System.Web.UI.WebControls.Literal @__ctrl;
            
            #line 18 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/Footer.ascx"
            @__ctrl = new global::System.Web.UI.WebControls.Literal();
            
            #line default
            #line hidden
            
            #line 18 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/Footer.ascx"
            this._bctrl_39 = @__ctrl;
            
            #line default
            #line hidden
            
            #line 18 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/Footer.ascx"
            @__ctrl.Text = global::System.Convert.ToString(global::System.Convert.ToString(this.GetLocalResourceObject("Parents"), System.Globalization.CultureInfo.CurrentCulture), System.Globalization.CultureInfo.CurrentCulture);
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        private void @__Render__bctrl_40(System.Web.UI.HtmlTextWriter @__output, System.Web.UI.Control parameterContainer) {
            @__output.Write(@"English&nbsp;<span class=""FooterArrow"">▼</span>
                    <div class=""dropuplanguagecontainer"" style=""display:none;"" drop-down-nav-container=""LanguageTrigger"">
                        <div class=""dropdownmainnav"" style=""z-index:1023"">
                                <a href=""/UserLanguage/LanguageRedirect?languageCode=de&amp;relativePath=");
            
            #line 23 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/Footer.ascx"
            @__output.Write( HttpUtility.UrlEncode(HttpContext.Current.Request.Url.AbsolutePath) );
            
            #line default
            #line hidden
            @__output.Write("\"class=\"LanguageOption js-lang\" data-js-langcode=\"de\"><span class=\"notranslate\">D" +
                    "eutsch</span>&nbsp;(German) </a>\n                            </div>  \n          " +
                    "          </div>\n            ");
        }
        
        private global::System.Web.UI.HtmlControls.HtmlGenericControl @__BuildControl__bctrl_40() {
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl;
            
            #line 20 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/Footer.ascx"
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlGenericControl("span");
            
            #line default
            #line hidden
            
            #line 20 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/Footer.ascx"
            this._bctrl_40 = @__ctrl;
            
            #line default
            #line hidden
            
            #line 20 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/Footer.ascx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "LanguageOptionElement LanguageTrigger");
            
            #line default
            #line hidden
            
            #line 20 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/Footer.ascx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("ref", "footer-parents");
            
            #line default
            #line hidden
            
            #line 20 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/Footer.ascx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("NavigateUrl", "/Parents.aspx");
            
            #line default
            #line hidden
            
            #line 20 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/Footer.ascx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("drop-down-nav-button", "LanguageTrigger");
            
            #line default
            #line hidden
            @__ctrl.SetRenderMethodDelegate(new System.Web.UI.RenderMethod(this.@__Render__bctrl_40));
            return @__ctrl;
        }
        
        private global::System.Web.UI.WebControls.Literal @__BuildControl__bctrl_41() {
            global::System.Web.UI.WebControls.Literal @__ctrl;
            
            #line 30 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/Footer.ascx"
            @__ctrl = new global::System.Web.UI.WebControls.Literal();
            
            #line default
            #line hidden
            
            #line 30 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/Footer.ascx"
            this._bctrl_41 = @__ctrl;
            
            #line default
            #line hidden
            
            #line 30 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/Footer.ascx"
            @__ctrl.Text = global::System.Convert.ToString(global::System.Convert.ToString(this.GetLocalResourceObject("SEOGenres.AllGames"), System.Globalization.CultureInfo.CurrentCulture), System.Globalization.CultureInfo.CurrentCulture);
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        private global::System.Web.UI.WebControls.Literal @__BuildControl__bctrl_42() {
            global::System.Web.UI.WebControls.Literal @__ctrl;
            
            #line 32 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/Footer.ascx"
            @__ctrl = new global::System.Web.UI.WebControls.Literal();
            
            #line default
            #line hidden
            
            #line 32 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/Footer.ascx"
            this._bctrl_42 = @__ctrl;
            
            #line default
            #line hidden
            
            #line 32 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/Footer.ascx"
            @__ctrl.Text = global::System.Convert.ToString(global::System.Convert.ToString(this.GetLocalResourceObject("SEOGenres.Building"), System.Globalization.CultureInfo.CurrentCulture), System.Globalization.CultureInfo.CurrentCulture);
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        private global::System.Web.UI.WebControls.Literal @__BuildControl__bctrl_43() {
            global::System.Web.UI.WebControls.Literal @__ctrl;
            
            #line 34 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/Footer.ascx"
            @__ctrl = new global::System.Web.UI.WebControls.Literal();
            
            #line default
            #line hidden
            
            #line 34 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/Footer.ascx"
            this._bctrl_43 = @__ctrl;
            
            #line default
            #line hidden
            
            #line 34 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/Footer.ascx"
            @__ctrl.Text = global::System.Convert.ToString(global::System.Convert.ToString(this.GetLocalResourceObject("SEOGenres.Horror"), System.Globalization.CultureInfo.CurrentCulture), System.Globalization.CultureInfo.CurrentCulture);
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        private global::System.Web.UI.WebControls.Literal @__BuildControl__bctrl_44() {
            global::System.Web.UI.WebControls.Literal @__ctrl;
            
            #line 36 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/Footer.ascx"
            @__ctrl = new global::System.Web.UI.WebControls.Literal();
            
            #line default
            #line hidden
            
            #line 36 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/Footer.ascx"
            this._bctrl_44 = @__ctrl;
            
            #line default
            #line hidden
            
            #line 36 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/Footer.ascx"
            @__ctrl.Text = global::System.Convert.ToString(global::System.Convert.ToString(this.GetLocalResourceObject("SEOGenres.TownAndCity"), System.Globalization.CultureInfo.CurrentCulture), System.Globalization.CultureInfo.CurrentCulture);
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        private global::System.Web.UI.WebControls.Literal @__BuildControl__bctrl_45() {
            global::System.Web.UI.WebControls.Literal @__ctrl;
            
            #line 38 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/Footer.ascx"
            @__ctrl = new global::System.Web.UI.WebControls.Literal();
            
            #line default
            #line hidden
            
            #line 38 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/Footer.ascx"
            this._bctrl_45 = @__ctrl;
            
            #line default
            #line hidden
            
            #line 38 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/Footer.ascx"
            @__ctrl.Text = global::System.Convert.ToString(global::System.Convert.ToString(this.GetLocalResourceObject("SEOGenres.Military"), System.Globalization.CultureInfo.CurrentCulture), System.Globalization.CultureInfo.CurrentCulture);
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        private global::System.Web.UI.WebControls.Literal @__BuildControl__bctrl_46() {
            global::System.Web.UI.WebControls.Literal @__ctrl;
            
            #line 40 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/Footer.ascx"
            @__ctrl = new global::System.Web.UI.WebControls.Literal();
            
            #line default
            #line hidden
            
            #line 40 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/Footer.ascx"
            this._bctrl_46 = @__ctrl;
            
            #line default
            #line hidden
            
            #line 40 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/Footer.ascx"
            @__ctrl.Text = global::System.Convert.ToString(global::System.Convert.ToString(this.GetLocalResourceObject("SEOGenres.Comedy"), System.Globalization.CultureInfo.CurrentCulture), System.Globalization.CultureInfo.CurrentCulture);
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        private global::System.Web.UI.WebControls.Literal @__BuildControl__bctrl_47() {
            global::System.Web.UI.WebControls.Literal @__ctrl;
            
            #line 42 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/Footer.ascx"
            @__ctrl = new global::System.Web.UI.WebControls.Literal();
            
            #line default
            #line hidden
            
            #line 42 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/Footer.ascx"
            this._bctrl_47 = @__ctrl;
            
            #line default
            #line hidden
            
            #line 42 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/Footer.ascx"
            @__ctrl.Text = global::System.Convert.ToString(global::System.Convert.ToString(this.GetLocalResourceObject("SEOGenres.Medieval"), System.Globalization.CultureInfo.CurrentCulture), System.Globalization.CultureInfo.CurrentCulture);
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        private global::System.Web.UI.WebControls.Literal @__BuildControl__bctrl_48() {
            global::System.Web.UI.WebControls.Literal @__ctrl;
            
            #line 44 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/Footer.ascx"
            @__ctrl = new global::System.Web.UI.WebControls.Literal();
            
            #line default
            #line hidden
            
            #line 44 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/Footer.ascx"
            this._bctrl_48 = @__ctrl;
            
            #line default
            #line hidden
            
            #line 44 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/Footer.ascx"
            @__ctrl.Text = global::System.Convert.ToString(global::System.Convert.ToString(this.GetLocalResourceObject("SEOGenres.Adventure"), System.Globalization.CultureInfo.CurrentCulture), System.Globalization.CultureInfo.CurrentCulture);
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        private global::System.Web.UI.WebControls.Literal @__BuildControl__bctrl_49() {
            global::System.Web.UI.WebControls.Literal @__ctrl;
            
            #line 46 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/Footer.ascx"
            @__ctrl = new global::System.Web.UI.WebControls.Literal();
            
            #line default
            #line hidden
            
            #line 46 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/Footer.ascx"
            this._bctrl_49 = @__ctrl;
            
            #line default
            #line hidden
            
            #line 46 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/Footer.ascx"
            @__ctrl.Text = global::System.Convert.ToString(global::System.Convert.ToString(this.GetLocalResourceObject("SEOGenres.Sci-Fi"), System.Globalization.CultureInfo.CurrentCulture), System.Globalization.CultureInfo.CurrentCulture);
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        private global::System.Web.UI.WebControls.Literal @__BuildControl__bctrl_50() {
            global::System.Web.UI.WebControls.Literal @__ctrl;
            
            #line 48 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/Footer.ascx"
            @__ctrl = new global::System.Web.UI.WebControls.Literal();
            
            #line default
            #line hidden
            
            #line 48 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/Footer.ascx"
            this._bctrl_50 = @__ctrl;
            
            #line default
            #line hidden
            
            #line 48 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/Footer.ascx"
            @__ctrl.Text = global::System.Convert.ToString(global::System.Convert.ToString(this.GetLocalResourceObject("SEOGenres.Naval"), System.Globalization.CultureInfo.CurrentCulture), System.Globalization.CultureInfo.CurrentCulture);
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        private global::System.Web.UI.WebControls.Literal @__BuildControl__bctrl_51() {
            global::System.Web.UI.WebControls.Literal @__ctrl;
            
            #line 50 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/Footer.ascx"
            @__ctrl = new global::System.Web.UI.WebControls.Literal();
            
            #line default
            #line hidden
            
            #line 50 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/Footer.ascx"
            this._bctrl_51 = @__ctrl;
            
            #line default
            #line hidden
            
            #line 50 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/Footer.ascx"
            @__ctrl.Text = global::System.Convert.ToString(global::System.Convert.ToString(this.GetLocalResourceObject("SEOGenres.FPS"), System.Globalization.CultureInfo.CurrentCulture), System.Globalization.CultureInfo.CurrentCulture);
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        private global::System.Web.UI.WebControls.Literal @__BuildControl__bctrl_52() {
            global::System.Web.UI.WebControls.Literal @__ctrl;
            
            #line 52 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/Footer.ascx"
            @__ctrl = new global::System.Web.UI.WebControls.Literal();
            
            #line default
            #line hidden
            
            #line 52 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/Footer.ascx"
            this._bctrl_52 = @__ctrl;
            
            #line default
            #line hidden
            
            #line 52 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/Footer.ascx"
            @__ctrl.Text = global::System.Convert.ToString(global::System.Convert.ToString(this.GetLocalResourceObject("SEOGenres.RPG"), System.Globalization.CultureInfo.CurrentCulture), System.Globalization.CultureInfo.CurrentCulture);
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        private global::System.Web.UI.WebControls.Literal @__BuildControl__bctrl_53() {
            global::System.Web.UI.WebControls.Literal @__ctrl;
            
            #line 54 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/Footer.ascx"
            @__ctrl = new global::System.Web.UI.WebControls.Literal();
            
            #line default
            #line hidden
            
            #line 54 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/Footer.ascx"
            this._bctrl_53 = @__ctrl;
            
            #line default
            #line hidden
            
            #line 54 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/Footer.ascx"
            @__ctrl.Text = global::System.Convert.ToString(global::System.Convert.ToString(this.GetLocalResourceObject("SEOGenres.Sports"), System.Globalization.CultureInfo.CurrentCulture), System.Globalization.CultureInfo.CurrentCulture);
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        private global::System.Web.UI.WebControls.Literal @__BuildControl__bctrl_54() {
            global::System.Web.UI.WebControls.Literal @__ctrl;
            
            #line 56 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/Footer.ascx"
            @__ctrl = new global::System.Web.UI.WebControls.Literal();
            
            #line default
            #line hidden
            
            #line 56 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/Footer.ascx"
            this._bctrl_54 = @__ctrl;
            
            #line default
            #line hidden
            
            #line 56 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/Footer.ascx"
            @__ctrl.Text = global::System.Convert.ToString(global::System.Convert.ToString(this.GetLocalResourceObject("SEOGenres.Fighting"), System.Globalization.CultureInfo.CurrentCulture), System.Globalization.CultureInfo.CurrentCulture);
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        private global::System.Web.UI.WebControls.Literal @__BuildControl__bctrl_55() {
            global::System.Web.UI.WebControls.Literal @__ctrl;
            
            #line 58 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/Footer.ascx"
            @__ctrl = new global::System.Web.UI.WebControls.Literal();
            
            #line default
            #line hidden
            
            #line 58 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/Footer.ascx"
            this._bctrl_55 = @__ctrl;
            
            #line default
            #line hidden
            
            #line 58 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/Footer.ascx"
            @__ctrl.Text = global::System.Convert.ToString(global::System.Convert.ToString(this.GetLocalResourceObject("SEOGenres.Western"), System.Globalization.CultureInfo.CurrentCulture), System.Globalization.CultureInfo.CurrentCulture);
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        private global::System.Web.UI.WebControls.Label @__BuildControl_YearLabel() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            
            #line 69 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/Footer.ascx"
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            
            #line default
            #line hidden
            
            #line 69 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/Footer.ascx"
            this.YearLabel = @__ctrl;
            
            #line default
            #line hidden
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            
            #line 69 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/Footer.ascx"
            @__ctrl.ID = "YearLabel";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        protected override void FrameworkInitialize() {
            base.FrameworkInitialize();
            this.SetStringResourcePointer(global::ASP.usercontrols_navigation_footer_ascx.@__stringResource, 0);
            this.@__BuildControlTree(this);
        }
    }
}
