#pragma checksum "/home/runner/workspace/RobloxWebSite/UserControls/TrackingPixels/RobloxEventManager.ascx" "{406ea660-64cf-4c82-b6f0-42d48172a799}" "9B699B5DF6901FDFF910797A49CF2161"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
    using System;
    using System.Collections;
    using System.Collections.Specialized;
    using System.Configuration;
    using System.Text;
    using System.Text.RegularExpressions;
    using System.Web;
    using System.Web.Caching;
    using System.Web.SessionState;
    using System.Web.Security;
    using System.Web.Profile;
    using System.Web.UI;
    using System.Web.UI.WebControls;
    using System.Web.UI.HtmlControls;
    using Roblox.Website;
    using Roblox.Web.Code;
    
    
    public class usercontrols_trackingpixels_robloxeventmanager_ascx : global::Roblox.Website.UserControls.Tracking.RobloxEventManager {
        
        private static bool @__initialized = false;
        
        private static object @__stringResource = null;
        
        private static int @__autoHandlers;
        
        public usercontrols_trackingpixels_robloxeventmanager_ascx() {
            ((global::Roblox.Website.UserControls.Tracking.RobloxEventManager)(this)).AppRelativeVirtualPath = "~/UserControls/TrackingPixels/RobloxEventManager.ascx";
            if ((global::ASP.usercontrols_trackingpixels_robloxeventmanager_ascx.@__initialized == false)) {
                global::ASP.usercontrols_trackingpixels_robloxeventmanager_ascx.@__initialized = true;
            }
        }
        
        [System.Obsolete()]
        protected override int AutoHandlers {
            get {
                return ASP.usercontrols_trackingpixels_robloxeventmanager_ascx.@__autoHandlers;
            }
            set {
                ASP.usercontrols_trackingpixels_robloxeventmanager_ascx.@__autoHandlers = value;
            }
        }
        
        protected System.Web.HttpApplication ApplicationInstance {
            get {
                return ((System.Web.HttpApplication)(this.Context.ApplicationInstance));
            }
        }
        
        protected System.Web.Profile.DefaultProfile Profile {
            get {
                return ((System.Web.Profile.DefaultProfile)(this.Context.Profile));
            }
        }
        
        private void @__BuildControlTree(usercontrols_trackingpixels_robloxeventmanager_ascx @__ctrl) {
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/TrackingPixels/RobloxEventManager.ascx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("<script type=\"text/javascript\">\n        $(function () {\n            function trac" +
                        "kReturns() {\n                function dayDiff(d1, d2) {\n                    retu" +
                        "rn Math.floor((d1 - d2) / 86400000);\n                }\n\n                var cook" +
                        "ieName = \'RBXReturn\';\n                var cookieOptions = { expires: 9001 };\n   " +
                        "             var cookie = $.getJSONCookie(cookieName);\n\n                if (type" +
                        "of cookie.ts === \"undefined\" || isNaN(new Date(cookie.ts))) {\n                  " +
                        "  $.setJSONCookie(cookieName, { ts: new Date().toDateString() }, cookieOptions);" +
                        "\n                    return;\n                }\n\n                var daysSinceFir" +
                        "stVisit = dayDiff(new Date(), new Date(cookie.ts));\n                if (daysSinc" +
                        "eFirstVisit == 1 && typeof cookie.odr === \"undefined\") {\n                    Rob" +
                        "loxEventManager.triggerEvent(\'rbx_evt_odr\', {});\n                    cookie.odr " +
                        "= 1;\n                }\n                if (daysSinceFirstVisit >= 1 && daysSince" +
                        "FirstVisit <= 7 && typeof cookie.sdr === \"undefined\") {\n                    Robl" +
                        "oxEventManager.triggerEvent(\'rbx_evt_sdr\', {});\n                    cookie.sdr =" +
                        " 1;\n                }\n\n                $.setJSONCookie(cookieName, cookie, cooki" +
                        "eOptions);\n            }\n\n\n            RobloxListener.restUrl = window.location." +
                        "protocol + \"//\" + \"roblox.com/Game/EventTracker.ashx\";\n            RobloxListene" +
                        "r.init();\n\n\n            GoogleListener.init();\n\n\n\n\n            RobloxEventManage" +
                        "r.initialize(true);\n            RobloxEventManager.triggerEvent(\'rbx_evt_pagevie" +
                        "w\');\n            trackReturns();\n\n\n\n            RobloxEventManager._idleInterval" +
                        " = 450000;\n            RobloxEventManager.registerCookieStoreEvent(\'rbx_evt_init" +
                        "ial_install_start\');\n            RobloxEventManager.registerCookieStoreEvent(\'rb" +
                        "x_evt_ftp\');\n            RobloxEventManager.registerCookieStoreEvent(\'rbx_evt_in" +
                        "itial_install_success\');\n            RobloxEventManager.registerCookieStoreEvent" +
                        "(\'rbx_evt_fmp\');\n            RobloxEventManager.startMonitor();\n\n\n        });\n\n " +
                        "   </script>"));
            
            #line default
            #line hidden
        }
        
        protected override void FrameworkInitialize() {
            base.FrameworkInitialize();
            this.SetStringResourcePointer(global::ASP.usercontrols_trackingpixels_robloxeventmanager_ascx.@__stringResource, 0);
            this.@__BuildControlTree(this);
        }
    }
}
