#pragma checksum "/home/runner/workspace/RobloxWebSite/UserControls/UserContent/UserStatisticsPane.ascx" "{406ea660-64cf-4c82-b6f0-42d48172a799}" "78F92E60156A3B7A1C65FA7D97D7EFDE"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
    using System;
    using System.Collections;
    using System.Collections.Specialized;
    using System.Configuration;
    using System.Text;
    using System.Text.RegularExpressions;
    using System.Web;
    using System.Web.Caching;
    using System.Web.SessionState;
    using System.Web.Security;
    using System.Web.Profile;
    using System.Web.UI;
    using System.Web.UI.WebControls;
    using System.Web.UI.HtmlControls;
    using Roblox.Website;
    using Roblox.Web.Code;
    
    
    public class usercontrols_usercontent_userstatisticspane_ascx : global::Roblox.Website.UserControls.UserContent.UserStatisticsPane {
        
        private static bool @__initialized = false;
        
        private static object @__stringResource = null;
        
        private static int @__autoHandlers;
        
        public usercontrols_usercontent_userstatisticspane_ascx() {
            ((global::Roblox.Website.UserControls.UserContent.UserStatisticsPane)(this)).AppRelativeVirtualPath = "~/UserControls/UserContent/UserStatisticsPane.ascx";
            if ((global::ASP.usercontrols_usercontent_userstatisticspane_ascx.@__initialized == false)) {
                global::ASP.usercontrols_usercontent_userstatisticspane_ascx.@__initialized = true;
            }
        }
        
        [System.Obsolete()]
        protected override int AutoHandlers {
            get {
                return ASP.usercontrols_usercontent_userstatisticspane_ascx.@__autoHandlers;
            }
            set {
                ASP.usercontrols_usercontent_userstatisticspane_ascx.@__autoHandlers = value;
            }
        }
        
        protected System.Web.HttpApplication ApplicationInstance {
            get {
                return ((System.Web.HttpApplication)(this.Context.ApplicationInstance));
            }
        }
        
        protected System.Web.Profile.DefaultProfile Profile {
            get {
                return ((System.Web.Profile.DefaultProfile)(this.Context.Profile));
            }
        }
        
        private void @__RenderTree(System.Web.UI.HtmlTextWriter @__output, System.Web.UI.Control parameterContainer) {
            
            #line 2 "/home/runner/workspace/RobloxWebSite/UserControls/UserContent/UserStatisticsPane.ascx"
if (UserProfile != null) { 
            
            #line default
            #line hidden
            @__output.Write("<style>\n.statsLabel { font-weight:bold; width:200px; text-align:right; padding-ri" +
                    "ght:10px;}\n.statsValue { font-weight:normal; width:200px; text-align:left;}\n.sta" +
                    "tsTable { width:400px; }\n</style>\n<h2 class=\"title\"><span>");
            
            #line 8 "/home/runner/workspace/RobloxWebSite/UserControls/UserContent/UserStatisticsPane.ascx"
            @__output.Write(Resources.GetString("Heading.Statistics") );
            
            #line default
            #line hidden
            @__output.Write(@"</span></h2>

<div class=""divider-bottom"" style=""padding-bottom: 20px"">
<table class=""statsTable"">
    <tr>
        <td class=""statsLabel"">
        <acronym title=""The number of this user's friends."">Friends</acronym>:
        </td>
        <td class=""statsValue"">
        ");
            parameterContainer.Controls[0].RenderControl(@__output);
            @__output.Write("\n        </td>\n    </tr>\n    ");
            parameterContainer.Controls[1].RenderControl(@__output);
            @__output.Write("\n    <tr>\n        <td class=\"statsLabel\"><acronym title=\"The number of posts this" +
                    " user has made to the ROBLOX forum.\">Forum Posts</acronym>:</td>\n        <td cla" +
                    "ss=\"statsValue\">");
            parameterContainer.Controls[2].RenderControl(@__output);
            @__output.Write("</td>\n    </tr>\n    \n    <tr>\n        <td class=\"statsLabel\"><acronym title=\"The " +
                    "number of times this user\'s place has been visited.\">Place Visits</acronym>:</td" +
                    ">\n        <td class=\"statsValue\">");
            parameterContainer.Controls[3].RenderControl(@__output);
            @__output.Write("</td>\n    </tr>\n    <tr>\n        <td class=\"statsLabel\"><acronym title=\"The numbe" +
                    "r of times this user\'s character has destroyed another user\'s character in-game." +
                    "\">Knockouts</acronym>:</td>\n        <td class=\"statsValue\">");
            parameterContainer.Controls[4].RenderControl(@__output);
            @__output.Write("</td>\n    </tr>\n    ");
            parameterContainer.Controls[5].RenderControl(@__output);
            @__output.Write("\n     <tr>\n        <td class=\"statsLabel\"><acronym title=\"The all-time highest vo" +
                    "ting accuracy this user has achieved when voting in contests.\">Highest Ever Voti" +
                    "ng Accuracy</acronym>:</td>\n        <td class=\"statsValue\">");
            parameterContainer.Controls[6].RenderControl(@__output);
            @__output.Write("%</td>\n    </tr>\n     ");
            parameterContainer.Controls[7].RenderControl(@__output);
            @__output.Write("\n</table>    \n</div>\n");
            
            #line 66 "/home/runner/workspace/RobloxWebSite/UserControls/UserContent/UserStatisticsPane.ascx"
} 
            
            #line default
            #line hidden
        }
        
        private void @__BuildControlTree(usercontrols_usercontent_userstatisticspane_ascx @__ctrl) {
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/UserContent/UserStatisticsPane.ascx"
            this.@__BuildControl_lFriendsStatistics();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/UserContent/UserStatisticsPane.ascx"
            @__parser.AddParsedSubObject(this.lFriendsStatistics);
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/UserContent/UserStatisticsPane.ascx"
            this.@__BuildControl_pInvitations();
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/UserContent/UserStatisticsPane.ascx"
            @__parser.AddParsedSubObject(this.pInvitations);
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/UserContent/UserStatisticsPane.ascx"
            this.@__BuildControl_lForumPostsStatistics();
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/UserContent/UserStatisticsPane.ascx"
            @__parser.AddParsedSubObject(this.lForumPostsStatistics);
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/UserContent/UserStatisticsPane.ascx"
            this.@__BuildControl_lPlaceVisitsStatistics();
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/UserContent/UserStatisticsPane.ascx"
            @__parser.AddParsedSubObject(this.lPlaceVisitsStatistics);
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/UserContent/UserStatisticsPane.ascx"
            this.@__BuildControl_lKillsStatistics();
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/UserContent/UserStatisticsPane.ascx"
            @__parser.AddParsedSubObject(this.lKillsStatistics);
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/UserContent/UserStatisticsPane.ascx"
            this.@__BuildControl_pDeaths();
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/UserContent/UserStatisticsPane.ascx"
            @__parser.AddParsedSubObject(this.pDeaths);
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/UserContent/UserStatisticsPane.ascx"
            this.@__BuildControl_lHighestEverVotingAccuracyStatistics();
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/UserContent/UserStatisticsPane.ascx"
            @__parser.AddParsedSubObject(this.lHighestEverVotingAccuracyStatistics);
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/UserContent/UserStatisticsPane.ascx"
            this.@__BuildControl_pConsecutiveDaysInBC();
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/UserContent/UserStatisticsPane.ascx"
            @__parser.AddParsedSubObject(this.pConsecutiveDaysInBC);
            
            #line default
            #line hidden
            @__ctrl.SetRenderMethodDelegate(new System.Web.UI.RenderMethod(this.@__RenderTree));
        }
        
        private global::System.Web.UI.WebControls.Label @__BuildControl_lFriendsStatistics() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            
            #line 17 "/home/runner/workspace/RobloxWebSite/UserControls/UserContent/UserStatisticsPane.ascx"
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            
            #line default
            #line hidden
            
            #line 17 "/home/runner/workspace/RobloxWebSite/UserControls/UserContent/UserStatisticsPane.ascx"
            this.lFriendsStatistics = @__ctrl;
            
            #line default
            #line hidden
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            
            #line 17 "/home/runner/workspace/RobloxWebSite/UserControls/UserContent/UserStatisticsPane.ascx"
            @__ctrl.ID = "lFriendsStatistics";
            
            #line default
            #line hidden
            
            #line 17 "/home/runner/workspace/RobloxWebSite/UserControls/UserContent/UserStatisticsPane.ascx"
            @__ctrl.Text = "0";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        private global::System.Web.UI.WebControls.Panel @__BuildControl_pInvitations() {
            global::System.Web.UI.WebControls.Panel @__ctrl;
            
            #line 20 "/home/runner/workspace/RobloxWebSite/UserControls/UserContent/UserStatisticsPane.ascx"
            @__ctrl = new global::System.Web.UI.WebControls.Panel();
            
            #line default
            #line hidden
            
            #line 20 "/home/runner/workspace/RobloxWebSite/UserControls/UserContent/UserStatisticsPane.ascx"
            this.pInvitations = @__ctrl;
            
            #line default
            #line hidden
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            
            #line 20 "/home/runner/workspace/RobloxWebSite/UserControls/UserContent/UserStatisticsPane.ascx"
            @__ctrl.ID = "pInvitations";
            
            #line default
            #line hidden
            
            #line 20 "/home/runner/workspace/RobloxWebSite/UserControls/UserContent/UserStatisticsPane.ascx"
            @__ctrl.Visible = false;
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 20 "/home/runner/workspace/RobloxWebSite/UserControls/UserContent/UserStatisticsPane.ascx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\n\t\n    <tr>\n        <td class=\"statsLabel\"><acronym title=\"The number of friends " +
                        "this user has recruited to join ROBLOX.\">Friends Invited</acronym>:</td>\n       " +
                        " <td class=\"statsValue\">"));
            
            #line default
            #line hidden
            
            #line 20 "/home/runner/workspace/RobloxWebSite/UserControls/UserContent/UserStatisticsPane.ascx"
            this.@__BuildControl_lFriendsInvitedStatistics();
            
            #line default
            #line hidden
            
            #line 20 "/home/runner/workspace/RobloxWebSite/UserControls/UserContent/UserStatisticsPane.ascx"
            @__parser.AddParsedSubObject(this.lFriendsInvitedStatistics);
            
            #line default
            #line hidden
            
            #line 20 "/home/runner/workspace/RobloxWebSite/UserControls/UserContent/UserStatisticsPane.ascx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("</td>\n    </tr>\n    \n"));
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        private global::System.Web.UI.WebControls.Label @__BuildControl_lFriendsInvitedStatistics() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            
            #line 24 "/home/runner/workspace/RobloxWebSite/UserControls/UserContent/UserStatisticsPane.ascx"
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            
            #line default
            #line hidden
            
            #line 24 "/home/runner/workspace/RobloxWebSite/UserControls/UserContent/UserStatisticsPane.ascx"
            this.lFriendsInvitedStatistics = @__ctrl;
            
            #line default
            #line hidden
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            
            #line 24 "/home/runner/workspace/RobloxWebSite/UserControls/UserContent/UserStatisticsPane.ascx"
            @__ctrl.ID = "lFriendsInvitedStatistics";
            
            #line default
            #line hidden
            
            #line 24 "/home/runner/workspace/RobloxWebSite/UserControls/UserContent/UserStatisticsPane.ascx"
            @__ctrl.Text = "0";
            
            #line default
            #line hidden
            
            #line 24 "/home/runner/workspace/RobloxWebSite/UserControls/UserContent/UserStatisticsPane.ascx"
            @__ctrl.CssClass = "notranslate";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        private global::System.Web.UI.WebControls.Label @__BuildControl_lForumPostsStatistics() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            
            #line 30 "/home/runner/workspace/RobloxWebSite/UserControls/UserContent/UserStatisticsPane.ascx"
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            
            #line default
            #line hidden
            
            #line 30 "/home/runner/workspace/RobloxWebSite/UserControls/UserContent/UserStatisticsPane.ascx"
            this.lForumPostsStatistics = @__ctrl;
            
            #line default
            #line hidden
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            
            #line 30 "/home/runner/workspace/RobloxWebSite/UserControls/UserContent/UserStatisticsPane.ascx"
            @__ctrl.ID = "lForumPostsStatistics";
            
            #line default
            #line hidden
            
            #line 30 "/home/runner/workspace/RobloxWebSite/UserControls/UserContent/UserStatisticsPane.ascx"
            @__ctrl.Text = "0";
            
            #line default
            #line hidden
            
            #line 30 "/home/runner/workspace/RobloxWebSite/UserControls/UserContent/UserStatisticsPane.ascx"
            @__ctrl.CssClass = "notranslate";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        private global::System.Web.UI.WebControls.Label @__BuildControl_lPlaceVisitsStatistics() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            
            #line 38 "/home/runner/workspace/RobloxWebSite/UserControls/UserContent/UserStatisticsPane.ascx"
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            
            #line default
            #line hidden
            
            #line 38 "/home/runner/workspace/RobloxWebSite/UserControls/UserContent/UserStatisticsPane.ascx"
            this.lPlaceVisitsStatistics = @__ctrl;
            
            #line default
            #line hidden
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            
            #line 38 "/home/runner/workspace/RobloxWebSite/UserControls/UserContent/UserStatisticsPane.ascx"
            @__ctrl.ID = "lPlaceVisitsStatistics";
            
            #line default
            #line hidden
            
            #line 38 "/home/runner/workspace/RobloxWebSite/UserControls/UserContent/UserStatisticsPane.ascx"
            @__ctrl.Text = "0";
            
            #line default
            #line hidden
            
            #line 38 "/home/runner/workspace/RobloxWebSite/UserControls/UserContent/UserStatisticsPane.ascx"
            @__ctrl.CssClass = "notranslate";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        private global::System.Web.UI.WebControls.Label @__BuildControl_lKillsStatistics() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            
            #line 42 "/home/runner/workspace/RobloxWebSite/UserControls/UserContent/UserStatisticsPane.ascx"
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            
            #line default
            #line hidden
            
            #line 42 "/home/runner/workspace/RobloxWebSite/UserControls/UserContent/UserStatisticsPane.ascx"
            this.lKillsStatistics = @__ctrl;
            
            #line default
            #line hidden
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            
            #line 42 "/home/runner/workspace/RobloxWebSite/UserControls/UserContent/UserStatisticsPane.ascx"
            @__ctrl.ID = "lKillsStatistics";
            
            #line default
            #line hidden
            
            #line 42 "/home/runner/workspace/RobloxWebSite/UserControls/UserContent/UserStatisticsPane.ascx"
            @__ctrl.Text = "0";
            
            #line default
            #line hidden
            
            #line 42 "/home/runner/workspace/RobloxWebSite/UserControls/UserContent/UserStatisticsPane.ascx"
            @__ctrl.CssClass = "notranslate";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        private global::System.Web.UI.WebControls.Panel @__BuildControl_pDeaths() {
            global::System.Web.UI.WebControls.Panel @__ctrl;
            
            #line 44 "/home/runner/workspace/RobloxWebSite/UserControls/UserContent/UserStatisticsPane.ascx"
            @__ctrl = new global::System.Web.UI.WebControls.Panel();
            
            #line default
            #line hidden
            
            #line 44 "/home/runner/workspace/RobloxWebSite/UserControls/UserContent/UserStatisticsPane.ascx"
            this.pDeaths = @__ctrl;
            
            #line default
            #line hidden
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            
            #line 44 "/home/runner/workspace/RobloxWebSite/UserControls/UserContent/UserStatisticsPane.ascx"
            @__ctrl.ID = "pDeaths";
            
            #line default
            #line hidden
            
            #line 44 "/home/runner/workspace/RobloxWebSite/UserControls/UserContent/UserStatisticsPane.ascx"
            @__ctrl.Visible = false;
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 44 "/home/runner/workspace/RobloxWebSite/UserControls/UserContent/UserStatisticsPane.ascx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\n\t\n    <tr>\n        <td class=\"statsLabel\"><acronym title=\"The number of times th" +
                        "is user\'s character has been destroyed in-game.\">Wipeouts</acronym>:</td>\n      " +
                        "  <td class=\"statsValue\">"));
            
            #line default
            #line hidden
            
            #line 44 "/home/runner/workspace/RobloxWebSite/UserControls/UserContent/UserStatisticsPane.ascx"
            this.@__BuildControl_lDeathsStatistics();
            
            #line default
            #line hidden
            
            #line 44 "/home/runner/workspace/RobloxWebSite/UserControls/UserContent/UserStatisticsPane.ascx"
            @__parser.AddParsedSubObject(this.lDeathsStatistics);
            
            #line default
            #line hidden
            
            #line 44 "/home/runner/workspace/RobloxWebSite/UserControls/UserContent/UserStatisticsPane.ascx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("</td>\n    </tr>\n    \n"));
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        private global::System.Web.UI.WebControls.Label @__BuildControl_lDeathsStatistics() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            
            #line 48 "/home/runner/workspace/RobloxWebSite/UserControls/UserContent/UserStatisticsPane.ascx"
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            
            #line default
            #line hidden
            
            #line 48 "/home/runner/workspace/RobloxWebSite/UserControls/UserContent/UserStatisticsPane.ascx"
            this.lDeathsStatistics = @__ctrl;
            
            #line default
            #line hidden
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            
            #line 48 "/home/runner/workspace/RobloxWebSite/UserControls/UserContent/UserStatisticsPane.ascx"
            @__ctrl.ID = "lDeathsStatistics";
            
            #line default
            #line hidden
            
            #line 48 "/home/runner/workspace/RobloxWebSite/UserControls/UserContent/UserStatisticsPane.ascx"
            @__ctrl.Text = "0";
            
            #line default
            #line hidden
            
            #line 48 "/home/runner/workspace/RobloxWebSite/UserControls/UserContent/UserStatisticsPane.ascx"
            @__ctrl.CssClass = "notranslate";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        private global::System.Web.UI.WebControls.Label @__BuildControl_lHighestEverVotingAccuracyStatistics() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            
            #line 54 "/home/runner/workspace/RobloxWebSite/UserControls/UserContent/UserStatisticsPane.ascx"
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            
            #line default
            #line hidden
            
            #line 54 "/home/runner/workspace/RobloxWebSite/UserControls/UserContent/UserStatisticsPane.ascx"
            this.lHighestEverVotingAccuracyStatistics = @__ctrl;
            
            #line default
            #line hidden
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            
            #line 54 "/home/runner/workspace/RobloxWebSite/UserControls/UserContent/UserStatisticsPane.ascx"
            @__ctrl.ID = "lHighestEverVotingAccuracyStatistics";
            
            #line default
            #line hidden
            
            #line 54 "/home/runner/workspace/RobloxWebSite/UserControls/UserContent/UserStatisticsPane.ascx"
            @__ctrl.Text = "0";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        private global::System.Web.UI.WebControls.Panel @__BuildControl_pConsecutiveDaysInBC() {
            global::System.Web.UI.WebControls.Panel @__ctrl;
            
            #line 56 "/home/runner/workspace/RobloxWebSite/UserControls/UserContent/UserStatisticsPane.ascx"
            @__ctrl = new global::System.Web.UI.WebControls.Panel();
            
            #line default
            #line hidden
            
            #line 56 "/home/runner/workspace/RobloxWebSite/UserControls/UserContent/UserStatisticsPane.ascx"
            this.pConsecutiveDaysInBC = @__ctrl;
            
            #line default
            #line hidden
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            
            #line 56 "/home/runner/workspace/RobloxWebSite/UserControls/UserContent/UserStatisticsPane.ascx"
            @__ctrl.ID = "pConsecutiveDaysInBC";
            
            #line default
            #line hidden
            
            #line 56 "/home/runner/workspace/RobloxWebSite/UserControls/UserContent/UserStatisticsPane.ascx"
            @__ctrl.Visible = false;
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 56 "/home/runner/workspace/RobloxWebSite/UserControls/UserContent/UserStatisticsPane.ascx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
	
    <tr>
        <td class=""statsLabel""><acronym title=""The number of consecutive days this user has been in Builders Club and their corresponding loyalty multiplier."">Consecutive Days In BC</acronym>:</td>
        <td class=""statsValue"">909 (<a href='http://community.roblox.com/?p=4157'>3x</a>)</td>
    </tr>
    
"));
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        protected override void FrameworkInitialize() {
            base.FrameworkInitialize();
            this.SetStringResourcePointer(global::ASP.usercontrols_usercontent_userstatisticspane_ascx.@__stringResource, 0);
            this.@__BuildControlTree(this);
        }
    }
}
