#pragma checksum "/home/runner/workspace/RobloxWebSite/UserControls/VisitButtons.ascx" "{406ea660-64cf-4c82-b6f0-42d48172a799}" "7EDF992B0755C6D0B58D7486E38E4C98"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
    using System;
    using System.Collections;
    using System.Collections.Specialized;
    using System.Configuration;
    using System.Text;
    using System.Text.RegularExpressions;
    using System.Web;
    using System.Web.Caching;
    using System.Web.SessionState;
    using System.Web.Security;
    using System.Web.Profile;
    using System.Web.UI;
    using System.Web.UI.WebControls;
    using System.Web.UI.HtmlControls;
    using Roblox.Website;
    using Roblox.Web.Code;
    
    
    public class usercontrols_visitbuttons_ascx : global::Roblox.Website.UserControls.VisitButtons {
        
        private static bool @__initialized = false;
        
        private static object @__stringResource = null;
        
        private static int @__autoHandlers;
        
        
        #line 4 "/home/runner/workspace/RobloxWebSite/UserControls/VisitButtons.ascx"
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl _bctrl_69;
        
        #line default
        #line hidden
        
        
        #line 15 "/home/runner/workspace/RobloxWebSite/UserControls/VisitButtons.ascx"
        protected global::ASP.usercontrols_visitbuttonoverhead_ascx _bctrl_74;
        
        #line default
        #line hidden
        
        
        #line 16 "/home/runner/workspace/RobloxWebSite/UserControls/VisitButtons.ascx"
        protected global::ASP.usercontrols_modals_insufficientcurrencyorbc_bconlymodal_ascx _bctrl_75;
        
        #line default
        #line hidden
        
        public usercontrols_visitbuttons_ascx() {
            ((global::Roblox.Website.UserControls.VisitButtons)(this)).AppRelativeVirtualPath = "~/UserControls/VisitButtons.ascx";
            if ((global::ASP.usercontrols_visitbuttons_ascx.@__initialized == false)) {
                global::ASP.usercontrols_visitbuttons_ascx.@__initialized = true;
            }
        }
        
        [System.Obsolete()]
        protected override int AutoHandlers {
            get {
                return ASP.usercontrols_visitbuttons_ascx.@__autoHandlers;
            }
            set {
                ASP.usercontrols_visitbuttons_ascx.@__autoHandlers = value;
            }
        }
        
        protected System.Web.HttpApplication ApplicationInstance {
            get {
                return ((System.Web.HttpApplication)(this.Context.ApplicationInstance));
            }
        }
        
        protected System.Web.Profile.DefaultProfile Profile {
            get {
                return ((System.Web.Profile.DefaultProfile)(this.Context.Profile));
            }
        }
        
        private void @__BuildControlTree(usercontrols_visitbuttons_ascx @__ctrl) {
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/VisitButtons.ascx"
            this.@__BuildControl__bctrl_69();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/VisitButtons.ascx"
            @__parser.AddParsedSubObject(this._bctrl_69);
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/VisitButtons.ascx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\n    "));
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/VisitButtons.ascx"
            this.@__BuildControl__bctrl_74();
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/VisitButtons.ascx"
            @__parser.AddParsedSubObject(this._bctrl_74);
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/VisitButtons.ascx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\n    "));
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/VisitButtons.ascx"
            this.@__BuildControl__bctrl_75();
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/VisitButtons.ascx"
            @__parser.AddParsedSubObject(this._bctrl_75);
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/VisitButtons.ascx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
<script type=""text/javascript"">
    $(function () {
        Roblox.Client.Resources = {
            //<sl:translate>
            here: ""here"",
            youNeedTheLatest: ""You need Our Plugin for this.  Get the latest version from "",
            plugInInstallationFailed: ""Plugin installation failed!"",
            errorUpdating: ""Error updating: ""
            //</sl:translate>
        };
    });
</script>"));
            
            #line default
            #line hidden
        }
        
        private global::System.Web.UI.HtmlControls.HtmlGenericControl @__BuildControl__bctrl_69() {
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl;
            
            #line 4 "/home/runner/workspace/RobloxWebSite/UserControls/VisitButtons.ascx"
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlGenericControl("div");
            
            #line default
            #line hidden
            
            #line 4 "/home/runner/workspace/RobloxWebSite/UserControls/VisitButtons.ascx"
            this._bctrl_69 = @__ctrl;
            
            #line default
            #line hidden
            @__ctrl.DataBinding += new System.EventHandler(this.@__DataBind__bctrl_70);
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 4 "/home/runner/workspace/RobloxWebSite/UserControls/VisitButtons.ascx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\n            "));
            
            #line default
            #line hidden
            
            #line 4 "/home/runner/workspace/RobloxWebSite/UserControls/VisitButtons.ascx"
            this.@__BuildControl_MultiplayerVisitButton();
            
            #line default
            #line hidden
            
            #line 4 "/home/runner/workspace/RobloxWebSite/UserControls/VisitButtons.ascx"
            @__parser.AddParsedSubObject(this.MultiplayerVisitButton);
            
            #line default
            #line hidden
            
            #line 4 "/home/runner/workspace/RobloxWebSite/UserControls/VisitButtons.ascx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("  \n            "));
            
            #line default
            #line hidden
            
            #line 4 "/home/runner/workspace/RobloxWebSite/UserControls/VisitButtons.ascx"
            this.@__BuildControl_BuildButton();
            
            #line default
            #line hidden
            
            #line 4 "/home/runner/workspace/RobloxWebSite/UserControls/VisitButtons.ascx"
            @__parser.AddParsedSubObject(this.BuildButton);
            
            #line default
            #line hidden
            
            #line 4 "/home/runner/workspace/RobloxWebSite/UserControls/VisitButtons.ascx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\n            "));
            
            #line default
            #line hidden
            
            #line 4 "/home/runner/workspace/RobloxWebSite/UserControls/VisitButtons.ascx"
            this.@__BuildControl_EditButton();
            
            #line default
            #line hidden
            
            #line 4 "/home/runner/workspace/RobloxWebSite/UserControls/VisitButtons.ascx"
            @__parser.AddParsedSubObject(this.EditButton);
            
            #line default
            #line hidden
            
            #line 4 "/home/runner/workspace/RobloxWebSite/UserControls/VisitButtons.ascx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\n        "));
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        public void @__DataBind__bctrl_70(object sender, System.EventArgs e) {
            System.Web.UI.Control Container;
            System.Web.UI.HtmlControls.HtmlGenericControl target;
            
            #line 4 "/home/runner/workspace/RobloxWebSite/UserControls/VisitButtons.ascx"
            target = ((System.Web.UI.HtmlControls.HtmlGenericControl)(sender));
            
            #line default
            #line hidden
            
            #line 4 "/home/runner/workspace/RobloxWebSite/UserControls/VisitButtons.ascx"
            Container = ((System.Web.UI.Control)(target.BindingContainer));
            
            #line default
            #line hidden
            ((System.Web.UI.IAttributeAccessor)(target)).SetAttribute("class", System.Convert.ToString(FancyButtonsClassName));
        }
        
        private global::System.Web.UI.HtmlControls.HtmlGenericControl @__BuildControl_MultiplayerVisitButton() {
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl;
            
            #line 5 "/home/runner/workspace/RobloxWebSite/UserControls/VisitButtons.ascx"
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlGenericControl("div");
            
            #line default
            #line hidden
            
            #line 5 "/home/runner/workspace/RobloxWebSite/UserControls/VisitButtons.ascx"
            this.MultiplayerVisitButton = @__ctrl;
            
            #line default
            #line hidden
            
            #line 5 "/home/runner/workspace/RobloxWebSite/UserControls/VisitButtons.ascx"
            @__ctrl.ID = "MultiplayerVisitButton";
            
            #line default
            #line hidden
            
            #line 5 "/home/runner/workspace/RobloxWebSite/UserControls/VisitButtons.ascx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "VisitButton VisitButtonPlay");
            
            #line default
            #line hidden
            @__ctrl.DataBinding += new System.EventHandler(this.@__DataBind__bctrl_71);
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 5 "/home/runner/workspace/RobloxWebSite/UserControls/VisitButtons.ascx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\n                <a  class=\"btn-medium btn-primary\">Play</a>\n            "));
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        public void @__DataBind__bctrl_71(object sender, System.EventArgs e) {
            System.Web.UI.Control Container;
            System.Web.UI.HtmlControls.HtmlGenericControl target;
            
            #line 5 "/home/runner/workspace/RobloxWebSite/UserControls/VisitButtons.ascx"
            target = ((System.Web.UI.HtmlControls.HtmlGenericControl)(sender));
            
            #line default
            #line hidden
            
            #line 5 "/home/runner/workspace/RobloxWebSite/UserControls/VisitButtons.ascx"
            Container = ((System.Web.UI.Control)(target.BindingContainer));
            
            #line default
            #line hidden
            ((System.Web.UI.IAttributeAccessor)(target)).SetAttribute("placeid", System.Convert.ToString(Place.ID));
        }
        
        private global::System.Web.UI.HtmlControls.HtmlGenericControl @__BuildControl_BuildButton() {
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl;
            
            #line 8 "/home/runner/workspace/RobloxWebSite/UserControls/VisitButtons.ascx"
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlGenericControl("div");
            
            #line default
            #line hidden
            
            #line 8 "/home/runner/workspace/RobloxWebSite/UserControls/VisitButtons.ascx"
            this.BuildButton = @__ctrl;
            
            #line default
            #line hidden
            
            #line 8 "/home/runner/workspace/RobloxWebSite/UserControls/VisitButtons.ascx"
            @__ctrl.ID = "BuildButton";
            
            #line default
            #line hidden
            
            #line 8 "/home/runner/workspace/RobloxWebSite/UserControls/VisitButtons.ascx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "VisitButton VisitButtonBuild");
            
            #line default
            #line hidden
            @__ctrl.DataBinding += new System.EventHandler(this.@__DataBind__bctrl_72);
            @__ctrl.DataBinding += new System.EventHandler(this.@__BuildControl_BuildButton_DB_0);
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 8 "/home/runner/workspace/RobloxWebSite/UserControls/VisitButtons.ascx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\n                <a  title=\"Open in Build Mode\" class=\"btn-medium btn-primary too" +
                        "ltip\">Build</a>\n            "));
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        public void @__DataBind__bctrl_72(object sender, System.EventArgs e) {
            System.Web.UI.Control Container;
            System.Web.UI.HtmlControls.HtmlGenericControl target;
            
            #line 8 "/home/runner/workspace/RobloxWebSite/UserControls/VisitButtons.ascx"
            target = ((System.Web.UI.HtmlControls.HtmlGenericControl)(sender));
            
            #line default
            #line hidden
            
            #line 8 "/home/runner/workspace/RobloxWebSite/UserControls/VisitButtons.ascx"
            Container = ((System.Web.UI.Control)(target.BindingContainer));
            
            #line default
            #line hidden
            ((System.Web.UI.IAttributeAccessor)(target)).SetAttribute("placeid", System.Convert.ToString(Place.ID));
        }
        
        public void @__BuildControl_BuildButton_DB_0(object sender, System.EventArgs e) {
            System.Web.UI.Control Container;
            System.Web.UI.HtmlControls.HtmlGenericControl target;
            
            #line 8 "/home/runner/workspace/RobloxWebSite/UserControls/VisitButtons.ascx"
            target = ((System.Web.UI.HtmlControls.HtmlGenericControl)(sender));
            
            #line default
            #line hidden
            
            #line 8 "/home/runner/workspace/RobloxWebSite/UserControls/VisitButtons.ascx"
            Container = ((System.Web.UI.Control)(target.BindingContainer));
            
            #line default
            #line hidden
            target.Visible = ((bool)(CanBuild));
        }
        
        private global::System.Web.UI.HtmlControls.HtmlGenericControl @__BuildControl_EditButton() {
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl;
            
            #line 11 "/home/runner/workspace/RobloxWebSite/UserControls/VisitButtons.ascx"
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlGenericControl("div");
            
            #line default
            #line hidden
            
            #line 11 "/home/runner/workspace/RobloxWebSite/UserControls/VisitButtons.ascx"
            this.EditButton = @__ctrl;
            
            #line default
            #line hidden
            
            #line 11 "/home/runner/workspace/RobloxWebSite/UserControls/VisitButtons.ascx"
            @__ctrl.ID = "EditButton";
            
            #line default
            #line hidden
            
            #line 11 "/home/runner/workspace/RobloxWebSite/UserControls/VisitButtons.ascx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "VisitButton VisitButtonEdit");
            
            #line default
            #line hidden
            @__ctrl.DataBinding += new System.EventHandler(this.@__DataBind__bctrl_73);
            @__ctrl.DataBinding += new System.EventHandler(this.@__BuildControl_EditButton_DB_0);
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 11 "/home/runner/workspace/RobloxWebSite/UserControls/VisitButtons.ascx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\n                <a  title=\"Open in Studio Mode\" class=\"btn-medium btn-primary to" +
                        "oltip\">Edit</a>\n            "));
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        public void @__DataBind__bctrl_73(object sender, System.EventArgs e) {
            System.Web.UI.Control Container;
            System.Web.UI.HtmlControls.HtmlGenericControl target;
            
            #line 11 "/home/runner/workspace/RobloxWebSite/UserControls/VisitButtons.ascx"
            target = ((System.Web.UI.HtmlControls.HtmlGenericControl)(sender));
            
            #line default
            #line hidden
            
            #line 11 "/home/runner/workspace/RobloxWebSite/UserControls/VisitButtons.ascx"
            Container = ((System.Web.UI.Control)(target.BindingContainer));
            
            #line default
            #line hidden
            ((System.Web.UI.IAttributeAccessor)(target)).SetAttribute("placeid", System.Convert.ToString(Place.ID));
        }
        
        public void @__BuildControl_EditButton_DB_0(object sender, System.EventArgs e) {
            System.Web.UI.Control Container;
            System.Web.UI.HtmlControls.HtmlGenericControl target;
            
            #line 11 "/home/runner/workspace/RobloxWebSite/UserControls/VisitButtons.ascx"
            target = ((System.Web.UI.HtmlControls.HtmlGenericControl)(sender));
            
            #line default
            #line hidden
            
            #line 11 "/home/runner/workspace/RobloxWebSite/UserControls/VisitButtons.ascx"
            Container = ((System.Web.UI.Control)(target.BindingContainer));
            
            #line default
            #line hidden
            target.Visible = ((bool)(CanEdit));
        }
        
        private global::ASP.usercontrols_visitbuttonoverhead_ascx @__BuildControl__bctrl_74() {
            global::ASP.usercontrols_visitbuttonoverhead_ascx @__ctrl;
            
            #line 15 "/home/runner/workspace/RobloxWebSite/UserControls/VisitButtons.ascx"
            @__ctrl = new global::ASP.usercontrols_visitbuttonoverhead_ascx();
            
            #line default
            #line hidden
            
            #line 15 "/home/runner/workspace/RobloxWebSite/UserControls/VisitButtons.ascx"
            this._bctrl_74 = @__ctrl;
            
            #line default
            #line hidden
            this._bctrl_74.InitializeAsUserControl(this.Page);
            return @__ctrl;
        }
        
        private global::ASP.usercontrols_modals_insufficientcurrencyorbc_bconlymodal_ascx @__BuildControl__bctrl_75() {
            global::ASP.usercontrols_modals_insufficientcurrencyorbc_bconlymodal_ascx @__ctrl;
            
            #line 16 "/home/runner/workspace/RobloxWebSite/UserControls/VisitButtons.ascx"
            @__ctrl = new global::ASP.usercontrols_modals_insufficientcurrencyorbc_bconlymodal_ascx();
            
            #line default
            #line hidden
            
            #line 16 "/home/runner/workspace/RobloxWebSite/UserControls/VisitButtons.ascx"
            this._bctrl_75 = @__ctrl;
            
            #line default
            #line hidden
            this._bctrl_75.InitializeAsUserControl(this.Page);
            return @__ctrl;
        }
        
        protected override void FrameworkInitialize() {
            base.FrameworkInitialize();
            this.SetStringResourcePointer(global::ASP.usercontrols_visitbuttons_ascx.@__stringResource, 0);
            this.@__BuildControlTree(this);
        }
    }
}
