#pragma checksum "/home/runner/workspace/RobloxWebSite/UserControls/TrackingPixels/GoogleAnalytics.ascx" "{406ea660-64cf-4c82-b6f0-42d48172a799}" "F1DFECE508B73093D2BEE30224CDB412"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
    using System;
    using System.Collections;
    using System.Collections.Specialized;
    using System.Configuration;
    using System.Text;
    using System.Text.RegularExpressions;
    using System.Web;
    using System.Web.Caching;
    using System.Web.SessionState;
    using System.Web.Security;
    using System.Web.Profile;
    using System.Web.UI;
    using System.Web.UI.WebControls;
    using System.Web.UI.HtmlControls;
    using Roblox.Website;
    using Roblox.Web.Code;
    
    
    public class usercontrols_trackingpixels_googleanalytics_ascx : global::Roblox.Website.UserControls.GoogleAnalytics {
        
        private static bool @__initialized = false;
        
        private static object @__stringResource = null;
        
        private static int @__autoHandlers;
        
        public usercontrols_trackingpixels_googleanalytics_ascx() {
            ((global::Roblox.Website.UserControls.GoogleAnalytics)(this)).AppRelativeVirtualPath = "~/UserControls/TrackingPixels/GoogleAnalytics.ascx";
            if ((global::ASP.usercontrols_trackingpixels_googleanalytics_ascx.@__initialized == false)) {
                global::ASP.usercontrols_trackingpixels_googleanalytics_ascx.@__initialized = true;
            }
        }
        
        [System.Obsolete()]
        protected override int AutoHandlers {
            get {
                return ASP.usercontrols_trackingpixels_googleanalytics_ascx.@__autoHandlers;
            }
            set {
                ASP.usercontrols_trackingpixels_googleanalytics_ascx.@__autoHandlers = value;
            }
        }
        
        protected System.Web.HttpApplication ApplicationInstance {
            get {
                return ((System.Web.HttpApplication)(this.Context.ApplicationInstance));
            }
        }
        
        protected System.Web.Profile.DefaultProfile Profile {
            get {
                return ((System.Web.Profile.DefaultProfile)(this.Context.Profile));
            }
        }
        
        private void @__RenderTree(System.Web.UI.HtmlTextWriter @__output, System.Web.UI.Control parameterContainer) {
            @__output.Write(@"<script type=""text/javascript"">

        var _gaq = _gaq || [];
        _gaq.push(['_setAccount', 'UA-11419793-2']);
        _gaq.push(['_setCampSourceKey', 'rbx_source']);
        _gaq.push(['_setCampMediumKey', 'rbx_medium']);
        _gaq.push(['_setCampContentKey', 'rbx_campaign']);



        _gaq.push(['b._setAccount', '");
            
            #line 2 "/home/runner/workspace/RobloxWebSite/UserControls/TrackingPixels/GoogleAnalytics.ascx"
            @__output.Write(Roblox.WebsiteSettings.Properties.GoogleAnalytics.Default.GoogleAnalyticsAccountCode);
            
            #line default
            #line hidden
            @__output.Write(@"']);
        _gaq.push(['b._setCampSourceKey', 'rbx_source']);
        _gaq.push(['b._setCampMediumKey', 'rbx_medium']);
        _gaq.push(['b._setCampContentKey', 'rbx_campaign']);


        _gaq.push(['c._setAccount', 'UA-26810151-1']);


        (function () {
            var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
            ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
            var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
        })();

    </script>");
        }
        
        private void @__BuildControlTree(usercontrols_trackingpixels_googleanalytics_ascx @__ctrl) {
            @__ctrl.SetRenderMethodDelegate(new System.Web.UI.RenderMethod(this.@__RenderTree));
        }
        
        protected override void FrameworkInitialize() {
            base.FrameworkInitialize();
            this.SetStringResourcePointer(global::ASP.usercontrols_trackingpixels_googleanalytics_ascx.@__stringResource, 0);
            this.@__BuildControlTree(this);
        }
    }
}
