#pragma checksum "/home/runner/workspace/RobloxWebSite/UserControls/Abuse/ReportAbuseButton.ascx" "{406ea660-64cf-4c82-b6f0-42d48172a799}" "4981049DA446A0ABF488043694D6A863"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
    using System;
    using System.Collections;
    using System.Collections.Specialized;
    using System.Configuration;
    using System.Text;
    using System.Text.RegularExpressions;
    using System.Web;
    using System.Web.Caching;
    using System.Web.SessionState;
    using System.Web.Security;
    using System.Web.Profile;
    using System.Web.UI;
    using System.Web.UI.WebControls;
    using System.Web.UI.HtmlControls;
    using Roblox.Website;
    using Roblox.Web.Code;
    
    
    public class usercontrols_abuse_reportabusebutton_ascx : global::Roblox.Website.UserControls.Abuse.ReportAbuseButton {
        
        private static bool @__initialized = false;
        
        private static object @__stringResource = null;
        
        private static int @__autoHandlers;
        
        public usercontrols_abuse_reportabusebutton_ascx() {
            ((global::Roblox.Website.UserControls.Abuse.ReportAbuseButton)(this)).AppRelativeVirtualPath = "~/UserControls/Abuse/ReportAbuseButton.ascx";
            if ((global::ASP.usercontrols_abuse_reportabusebutton_ascx.@__initialized == false)) {
                global::ASP.usercontrols_abuse_reportabusebutton_ascx.@__initialized = true;
            }
        }
        
        [System.Obsolete()]
        protected override int AutoHandlers {
            get {
                return ASP.usercontrols_abuse_reportabusebutton_ascx.@__autoHandlers;
            }
            set {
                ASP.usercontrols_abuse_reportabusebutton_ascx.@__autoHandlers = value;
            }
        }
        
        protected System.Web.HttpApplication ApplicationInstance {
            get {
                return ((System.Web.HttpApplication)(this.Context.ApplicationInstance));
            }
        }
        
        protected System.Web.Profile.DefaultProfile Profile {
            get {
                return ((System.Web.Profile.DefaultProfile)(this.Context.Profile));
            }
        }
        
        private void @__BuildControlTree(usercontrols_abuse_reportabusebutton_ascx @__ctrl) {
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/Abuse/ReportAbuseButton.ascx"
            this.@__BuildControl_AbuseReportPanel();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/Abuse/ReportAbuseButton.ascx"
            @__parser.AddParsedSubObject(this.AbuseReportPanel);
            
            #line default
            #line hidden
        }
        
        private global::System.Web.UI.WebControls.Panel @__BuildControl_AbuseReportPanel() {
            global::System.Web.UI.WebControls.Panel @__ctrl;
            
            #line 2 "/home/runner/workspace/RobloxWebSite/UserControls/Abuse/ReportAbuseButton.ascx"
            @__ctrl = new global::System.Web.UI.WebControls.Panel();
            
            #line default
            #line hidden
            
            #line 2 "/home/runner/workspace/RobloxWebSite/UserControls/Abuse/ReportAbuseButton.ascx"
            this.AbuseReportPanel = @__ctrl;
            
            #line default
            #line hidden
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            
            #line 2 "/home/runner/workspace/RobloxWebSite/UserControls/Abuse/ReportAbuseButton.ascx"
            @__ctrl.ID = "AbuseReportPanel";
            
            #line default
            #line hidden
            
            #line 2 "/home/runner/workspace/RobloxWebSite/UserControls/Abuse/ReportAbuseButton.ascx"
            @__ctrl.CssClass = "ReportAbuse";
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 2 "/home/runner/workspace/RobloxWebSite/UserControls/Abuse/ReportAbuseButton.ascx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\n    <span class=\"AbuseIcon\">"));
            
            #line default
            #line hidden
            
            #line 2 "/home/runner/workspace/RobloxWebSite/UserControls/Abuse/ReportAbuseButton.ascx"
            this.@__BuildControl_ReportAbuseIconHyperLink();
            
            #line default
            #line hidden
            
            #line 2 "/home/runner/workspace/RobloxWebSite/UserControls/Abuse/ReportAbuseButton.ascx"
            @__parser.AddParsedSubObject(this.ReportAbuseIconHyperLink);
            
            #line default
            #line hidden
            
            #line 2 "/home/runner/workspace/RobloxWebSite/UserControls/Abuse/ReportAbuseButton.ascx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("</span>\n    <span class=\"AbuseButton\">"));
            
            #line default
            #line hidden
            
            #line 2 "/home/runner/workspace/RobloxWebSite/UserControls/Abuse/ReportAbuseButton.ascx"
            this.@__BuildControl_ReportAbuseTextHyperLink();
            
            #line default
            #line hidden
            
            #line 2 "/home/runner/workspace/RobloxWebSite/UserControls/Abuse/ReportAbuseButton.ascx"
            @__parser.AddParsedSubObject(this.ReportAbuseTextHyperLink);
            
            #line default
            #line hidden
            
            #line 2 "/home/runner/workspace/RobloxWebSite/UserControls/Abuse/ReportAbuseButton.ascx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("</span>\n"));
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        private global::System.Web.UI.WebControls.HyperLink @__BuildControl_ReportAbuseIconHyperLink() {
            global::System.Web.UI.WebControls.HyperLink @__ctrl;
            
            #line 3 "/home/runner/workspace/RobloxWebSite/UserControls/Abuse/ReportAbuseButton.ascx"
            @__ctrl = new global::System.Web.UI.WebControls.HyperLink();
            
            #line default
            #line hidden
            
            #line 3 "/home/runner/workspace/RobloxWebSite/UserControls/Abuse/ReportAbuseButton.ascx"
            this.ReportAbuseIconHyperLink = @__ctrl;
            
            #line default
            #line hidden
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            
            #line 3 "/home/runner/workspace/RobloxWebSite/UserControls/Abuse/ReportAbuseButton.ascx"
            @__ctrl.ID = "ReportAbuseIconHyperLink";
            
            #line default
            #line hidden
            
            #line 3 "/home/runner/workspace/RobloxWebSite/UserControls/Abuse/ReportAbuseButton.ascx"
            @__ctrl.ToolTip = "Report Abuse";
            
            #line default
            #line hidden
            
            #line 3 "/home/runner/workspace/RobloxWebSite/UserControls/Abuse/ReportAbuseButton.ascx"
            @__ctrl.ImageUrl = "~/images/abuse.PNG?v=2";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        private global::System.Web.UI.WebControls.HyperLink @__BuildControl_ReportAbuseTextHyperLink() {
            global::System.Web.UI.WebControls.HyperLink @__ctrl;
            
            #line 4 "/home/runner/workspace/RobloxWebSite/UserControls/Abuse/ReportAbuseButton.ascx"
            @__ctrl = new global::System.Web.UI.WebControls.HyperLink();
            
            #line default
            #line hidden
            
            #line 4 "/home/runner/workspace/RobloxWebSite/UserControls/Abuse/ReportAbuseButton.ascx"
            this.ReportAbuseTextHyperLink = @__ctrl;
            
            #line default
            #line hidden
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            
            #line 4 "/home/runner/workspace/RobloxWebSite/UserControls/Abuse/ReportAbuseButton.ascx"
            @__ctrl.ID = "ReportAbuseTextHyperLink";
            
            #line default
            #line hidden
            
            #line 4 "/home/runner/workspace/RobloxWebSite/UserControls/Abuse/ReportAbuseButton.ascx"
            @__ctrl.Text = "Report Abuse";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        protected override void FrameworkInitialize() {
            base.FrameworkInitialize();
            this.SetStringResourcePointer(global::ASP.usercontrols_abuse_reportabusebutton_ascx.@__stringResource, 0);
            this.@__BuildControlTree(this);
        }
    }
}
