#pragma checksum "/home/runner/workspace/RobloxWebSite/RobloxDefaultErrorPage.aspx" "{406ea660-64cf-4c82-b6f0-42d48172a799}" "E33D02EA99A4488A96BFD0E37C7D779A"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
    using System;
    using System.Collections;
    using System.Collections.Specialized;
    using System.Configuration;
    using System.Text;
    using System.Text.RegularExpressions;
    using System.Web;
    using System.Web.Caching;
    using System.Web.SessionState;
    using System.Web.Security;
    using System.Web.Profile;
    using System.Web.UI;
    using System.Web.UI.WebControls;
    using System.Web.UI.HtmlControls;
    using Roblox.Website;
    using Roblox.Web.Code;
    
    
    public class robloxdefaulterrorpage_aspx : global::Roblox.Website.RobloxDefaultErrorPage, System.Web.SessionState.IRequiresSessionState, System.Web.IHttpHandler {
        
        private static bool @__initialized = false;
        
        private static object @__stringResource = null;
        
        private static object @__fileDependencies = null;
        
        private static int @__autoHandlers;
        
        public robloxdefaulterrorpage_aspx() {
            string[] dependencies;
            ((global::Roblox.Website.RobloxDefaultErrorPage)(this)).AppRelativeVirtualPath = "~/RobloxDefaultErrorPage.aspx";
            if ((global::ASP.robloxdefaulterrorpage_aspx.@__initialized == false)) {
                dependencies = new string[2];
                dependencies[0] = "/Simple.Master";
                dependencies[1] = "~/RobloxDefaultErrorPage.aspx";
                global::ASP.robloxdefaulterrorpage_aspx.@__fileDependencies = this.GetWrappedFileDependencies(dependencies);
                global::ASP.robloxdefaulterrorpage_aspx.@__initialized = true;
            }
        }
        
        [System.Obsolete()]
        protected override int AutoHandlers {
            get {
                return ASP.robloxdefaulterrorpage_aspx.@__autoHandlers;
            }
            set {
                ASP.robloxdefaulterrorpage_aspx.@__autoHandlers = value;
            }
        }
        
        protected System.Web.HttpApplication ApplicationInstance {
            get {
                return ((System.Web.HttpApplication)(this.Context.ApplicationInstance));
            }
        }
        
        protected System.Web.Profile.DefaultProfile Profile {
            get {
                return ((System.Web.Profile.DefaultProfile)(this.Context.Profile));
            }
        }
        
        private void @__BuildControlTree(robloxdefaulterrorpage_aspx @__ctrl) {
            
            #line 1 "/home/runner/workspace/RobloxWebSite/RobloxDefaultErrorPage.aspx"
            this.Title = "ROBLOX Error";
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/RobloxDefaultErrorPage.aspx"
            this.MasterPageFile = "/Simple.Master";
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/RobloxDefaultErrorPage.aspx"
            this.InitializeCulture();
            
            #line default
            #line hidden
            
            #line 3 "/home/runner/workspace/RobloxWebSite/RobloxDefaultErrorPage.aspx"
            this.AddContentTemplate("cphRoblox", new System.Web.UI.CompiledTemplateBuilder(new System.Web.UI.BuildTemplateMethod(this.@__BuildControl_RobloxContent)));
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 1 "/home/runner/workspace/RobloxWebSite/RobloxDefaultErrorPage.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\n"));
            
            #line default
            #line hidden
        }
        
        private void @__BuildControl_RobloxContent(System.Web.UI.Control @__ctrl) {
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 3 "/home/runner/workspace/RobloxWebSite/RobloxDefaultErrorPage.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\n    <div id=\"ErrorPage\">    \n        <img src=\'/Images/Icons/img-alert-crop.png\'" +
                        " alt=\"Alert\" class=\"ErrorAlert\"/>\n    \n        <h1>"));
            
            #line default
            #line hidden
            
            #line 3 "/home/runner/workspace/RobloxWebSite/RobloxDefaultErrorPage.aspx"
            this.@__BuildControl_ErrorTitle();
            
            #line default
            #line hidden
            
            #line 3 "/home/runner/workspace/RobloxWebSite/RobloxDefaultErrorPage.aspx"
            @__parser.AddParsedSubObject(this.ErrorTitle);
            
            #line default
            #line hidden
            
            #line 3 "/home/runner/workspace/RobloxWebSite/RobloxDefaultErrorPage.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("</h1>\n        <h3>"));
            
            #line default
            #line hidden
            
            #line 3 "/home/runner/workspace/RobloxWebSite/RobloxDefaultErrorPage.aspx"
            this.@__BuildControl_ErrorMessage();
            
            #line default
            #line hidden
            
            #line 3 "/home/runner/workspace/RobloxWebSite/RobloxDefaultErrorPage.aspx"
            @__parser.AddParsedSubObject(this.ErrorMessage);
            
            #line default
            #line hidden
            
            #line 3 "/home/runner/workspace/RobloxWebSite/RobloxDefaultErrorPage.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("</h3>\n        <p>"));
            
            #line default
            #line hidden
            
            #line 3 "/home/runner/workspace/RobloxWebSite/RobloxDefaultErrorPage.aspx"
            this.@__BuildControl_CustomerServiceMessage();
            
            #line default
            #line hidden
            
            #line 3 "/home/runner/workspace/RobloxWebSite/RobloxDefaultErrorPage.aspx"
            @__parser.AddParsedSubObject(this.CustomerServiceMessage);
            
            #line default
            #line hidden
            
            #line 3 "/home/runner/workspace/RobloxWebSite/RobloxDefaultErrorPage.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("</p>\n        <pre>"));
            
            #line default
            #line hidden
            
            #line 3 "/home/runner/workspace/RobloxWebSite/RobloxDefaultErrorPage.aspx"
            this.@__BuildControl_errorMsgLbl();
            
            #line default
            #line hidden
            
            #line 3 "/home/runner/workspace/RobloxWebSite/RobloxDefaultErrorPage.aspx"
            @__parser.AddParsedSubObject(this.errorMsgLbl);
            
            #line default
            #line hidden
            
            #line 3 "/home/runner/workspace/RobloxWebSite/RobloxDefaultErrorPage.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"</pre>

        <div class=""divideTitleAndBackButtons"">&nbsp;</div>

        <div class=""CenterNavigationButtonsForFloat"">
            <a class=""btn-small btn-neutral"" title=""Go to Previous Page Button"" onclick=""history.back();return false;"" href=""#"">Go to Previous Page</a>
            <a class=""btn-neutral btn-small"" title=""Return Home"" href=""/Default.aspx"">Return Home</a>
            <div style=""clear:both""></div>
        </div>
    </div>
"));
            
            #line default
            #line hidden
        }
        
        private global::System.Web.UI.WebControls.Label @__BuildControl_ErrorTitle() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            
            #line 7 "/home/runner/workspace/RobloxWebSite/RobloxDefaultErrorPage.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            
            #line default
            #line hidden
            
            #line 7 "/home/runner/workspace/RobloxWebSite/RobloxDefaultErrorPage.aspx"
            this.ErrorTitle = @__ctrl;
            
            #line default
            #line hidden
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 7 "/home/runner/workspace/RobloxWebSite/RobloxDefaultErrorPage.aspx"
            @__ctrl.ID = "ErrorTitle";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        private global::System.Web.UI.WebControls.Label @__BuildControl_ErrorMessage() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            
            #line 8 "/home/runner/workspace/RobloxWebSite/RobloxDefaultErrorPage.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            
            #line default
            #line hidden
            
            #line 8 "/home/runner/workspace/RobloxWebSite/RobloxDefaultErrorPage.aspx"
            this.ErrorMessage = @__ctrl;
            
            #line default
            #line hidden
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 8 "/home/runner/workspace/RobloxWebSite/RobloxDefaultErrorPage.aspx"
            @__ctrl.ID = "ErrorMessage";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        private global::System.Web.UI.WebControls.Label @__BuildControl_CustomerServiceMessage() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            
            #line 9 "/home/runner/workspace/RobloxWebSite/RobloxDefaultErrorPage.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            
            #line default
            #line hidden
            
            #line 9 "/home/runner/workspace/RobloxWebSite/RobloxDefaultErrorPage.aspx"
            this.CustomerServiceMessage = @__ctrl;
            
            #line default
            #line hidden
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 9 "/home/runner/workspace/RobloxWebSite/RobloxDefaultErrorPage.aspx"
            @__ctrl.ID = "CustomerServiceMessage";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        private global::System.Web.UI.WebControls.Label @__BuildControl_errorMsgLbl() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            
            #line 10 "/home/runner/workspace/RobloxWebSite/RobloxDefaultErrorPage.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            
            #line default
            #line hidden
            
            #line 10 "/home/runner/workspace/RobloxWebSite/RobloxDefaultErrorPage.aspx"
            this.errorMsgLbl = @__ctrl;
            
            #line default
            #line hidden
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 10 "/home/runner/workspace/RobloxWebSite/RobloxDefaultErrorPage.aspx"
            @__ctrl.ID = "errorMsgLbl";
            
            #line default
            #line hidden
            
            #line 10 "/home/runner/workspace/RobloxWebSite/RobloxDefaultErrorPage.aspx"
            @__ctrl.Text = "";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        protected override void FrameworkInitialize() {
            base.FrameworkInitialize();
            this.SetStringResourcePointer(global::ASP.robloxdefaulterrorpage_aspx.@__stringResource, 0);
            this.@__BuildControlTree(this);
            this.AddWrappedFileDependencies(global::ASP.robloxdefaulterrorpage_aspx.@__fileDependencies);
            this.Request.ValidateInput();
        }
        
        public override int GetTypeHashCode() {
            return 845575931;
        }
    }
}
