#pragma checksum "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/UserSubmenu.ascx" "{406ea660-64cf-4c82-b6f0-42d48172a799}" "43393FB9C546040288E5CBAF5133319E"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
    using System;
    using System.Collections;
    using System.Collections.Specialized;
    using System.Configuration;
    using System.Text;
    using System.Text.RegularExpressions;
    using System.Web;
    using System.Web.Caching;
    using System.Web.SessionState;
    using System.Web.Security;
    using System.Web.Profile;
    using System.Web.UI;
    using System.Web.UI.WebControls;
    using System.Web.UI.HtmlControls;
    using Roblox.Website;
    using Roblox.Web.Code;
    
    
    public class usercontrols_navigation_usersubmenu_ascx : global::Roblox.Website.UserControls.Navigation.UserSubmenu {
        
        private static bool @__initialized = false;
        
        private static object @__stringResource = null;
        
        private static int @__autoHandlers;
        
        
        #line 7 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/UserSubmenu.ascx"
        protected global::System.Web.UI.WebControls.HyperLink _bctrl_57;
        
        #line default
        #line hidden
        
        
        #line 8 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/UserSubmenu.ascx"
        protected global::System.Web.UI.WebControls.HyperLink _bctrl_58;
        
        #line default
        #line hidden
        
        
        #line 9 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/UserSubmenu.ascx"
        protected global::System.Web.UI.WebControls.HyperLink _bctrl_59;
        
        #line default
        #line hidden
        
        
        #line 10 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/UserSubmenu.ascx"
        protected global::System.Web.UI.WebControls.HyperLink _bctrl_60;
        
        #line default
        #line hidden
        
        
        #line 11 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/UserSubmenu.ascx"
        protected global::System.Web.UI.WebControls.HyperLink _bctrl_61;
        
        #line default
        #line hidden
        
        
        #line 13 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/UserSubmenu.ascx"
        protected global::System.Web.UI.WebControls.HyperLink _bctrl_62;
        
        #line default
        #line hidden
        
        
        #line 14 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/UserSubmenu.ascx"
        protected global::System.Web.UI.WebControls.HyperLink _bctrl_63;
        
        #line default
        #line hidden
        
        
        #line 15 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/UserSubmenu.ascx"
        protected global::System.Web.UI.WebControls.HyperLink _bctrl_64;
        
        #line default
        #line hidden
        
        
        #line 16 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/UserSubmenu.ascx"
        protected global::System.Web.UI.WebControls.HyperLink _bctrl_65;
        
        #line default
        #line hidden
        
        public usercontrols_navigation_usersubmenu_ascx() {
            ((global::Roblox.Website.UserControls.Navigation.UserSubmenu)(this)).AppRelativeVirtualPath = "~/UserControls/Navigation/UserSubmenu.ascx";
            if ((global::ASP.usercontrols_navigation_usersubmenu_ascx.@__initialized == false)) {
                global::ASP.usercontrols_navigation_usersubmenu_ascx.@__initialized = true;
            }
        }
        
        [System.Obsolete()]
        protected override int AutoHandlers {
            get {
                return ASP.usercontrols_navigation_usersubmenu_ascx.@__autoHandlers;
            }
            set {
                ASP.usercontrols_navigation_usersubmenu_ascx.@__autoHandlers = value;
            }
        }
        
        protected System.Web.HttpApplication ApplicationInstance {
            get {
                return ((System.Web.HttpApplication)(this.Context.ApplicationInstance));
            }
        }
        
        protected System.Web.Profile.DefaultProfile Profile {
            get {
                return ((System.Web.Profile.DefaultProfile)(this.Context.Profile));
            }
        }
        
        private void @__RenderTree(System.Web.UI.HtmlTextWriter @__output, System.Web.UI.Control parameterContainer) {
            
            #line 2 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/UserSubmenu.ascx"
if (Request.IsAuthenticated)
        { 
            
            #line default
            #line hidden
            @__output.Write("<div class=\"mySubmenuFixed Redesign\">\n    ");
            parameterContainer.Controls[0].RenderControl(@__output);
            @__output.Write("\n  </div>\n<div class=\"forceSpaceUnderSubmenu\">&nbsp;</div>\n");
            
            #line 21 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/UserSubmenu.ascx"
} 
            
            #line default
            #line hidden
        }
        
        private void @__BuildControlTree(usercontrols_navigation_usersubmenu_ascx @__ctrl) {
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/UserSubmenu.ascx"
            this.@__BuildControl_subMenu();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/UserSubmenu.ascx"
            @__parser.AddParsedSubObject(this.subMenu);
            
            #line default
            #line hidden
            @__ctrl.SetRenderMethodDelegate(new System.Web.UI.RenderMethod(this.@__RenderTree));
        }
        
        private global::System.Web.UI.WebControls.Panel @__BuildControl_subMenu() {
            global::System.Web.UI.WebControls.Panel @__ctrl;
            
            #line 5 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/UserSubmenu.ascx"
            @__ctrl = new global::System.Web.UI.WebControls.Panel();
            
            #line default
            #line hidden
            
            #line 5 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/UserSubmenu.ascx"
            this.subMenu = @__ctrl;
            
            #line default
            #line hidden
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            
            #line 5 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/UserSubmenu.ascx"
            @__ctrl.ID = "subMenu";
            
            #line default
            #line hidden
            
            #line 5 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/UserSubmenu.ascx"
            @__ctrl.CssClass = "subMenu";
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 5 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/UserSubmenu.ascx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\n      <ul>\n        <li>"));
            
            #line default
            #line hidden
            
            #line 5 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/UserSubmenu.ascx"
            this.@__BuildControl__bctrl_57();
            
            #line default
            #line hidden
            
            #line 5 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/UserSubmenu.ascx"
            @__parser.AddParsedSubObject(this._bctrl_57);
            
            #line default
            #line hidden
            
            #line 5 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/UserSubmenu.ascx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("</li>\n        <li>"));
            
            #line default
            #line hidden
            
            #line 5 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/UserSubmenu.ascx"
            this.@__BuildControl__bctrl_58();
            
            #line default
            #line hidden
            
            #line 5 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/UserSubmenu.ascx"
            @__parser.AddParsedSubObject(this._bctrl_58);
            
            #line default
            #line hidden
            
            #line 5 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/UserSubmenu.ascx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("</li>\n        <li>"));
            
            #line default
            #line hidden
            
            #line 5 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/UserSubmenu.ascx"
            this.@__BuildControl__bctrl_59();
            
            #line default
            #line hidden
            
            #line 5 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/UserSubmenu.ascx"
            @__parser.AddParsedSubObject(this._bctrl_59);
            
            #line default
            #line hidden
            
            #line 5 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/UserSubmenu.ascx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("</li>\n        <li>"));
            
            #line default
            #line hidden
            
            #line 5 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/UserSubmenu.ascx"
            this.@__BuildControl__bctrl_60();
            
            #line default
            #line hidden
            
            #line 5 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/UserSubmenu.ascx"
            @__parser.AddParsedSubObject(this._bctrl_60);
            
            #line default
            #line hidden
            
            #line 5 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/UserSubmenu.ascx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("</li>\n        <li>"));
            
            #line default
            #line hidden
            
            #line 5 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/UserSubmenu.ascx"
            this.@__BuildControl__bctrl_61();
            
            #line default
            #line hidden
            
            #line 5 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/UserSubmenu.ascx"
            @__parser.AddParsedSubObject(this._bctrl_61);
            
            #line default
            #line hidden
            
            #line 5 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/UserSubmenu.ascx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("</li>\n        <li>"));
            
            #line default
            #line hidden
            
            #line 5 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/UserSubmenu.ascx"
            this.@__BuildControl_SetsUrl();
            
            #line default
            #line hidden
            
            #line 5 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/UserSubmenu.ascx"
            @__parser.AddParsedSubObject(this.SetsUrl);
            
            #line default
            #line hidden
            
            #line 5 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/UserSubmenu.ascx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("</li>\n        <li>"));
            
            #line default
            #line hidden
            
            #line 5 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/UserSubmenu.ascx"
            this.@__BuildControl__bctrl_62();
            
            #line default
            #line hidden
            
            #line 5 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/UserSubmenu.ascx"
            @__parser.AddParsedSubObject(this._bctrl_62);
            
            #line default
            #line hidden
            
            #line 5 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/UserSubmenu.ascx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("</li>\n        <li>"));
            
            #line default
            #line hidden
            
            #line 5 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/UserSubmenu.ascx"
            this.@__BuildControl__bctrl_63();
            
            #line default
            #line hidden
            
            #line 5 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/UserSubmenu.ascx"
            @__parser.AddParsedSubObject(this._bctrl_63);
            
            #line default
            #line hidden
            
            #line 5 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/UserSubmenu.ascx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("</li>\n        <li>"));
            
            #line default
            #line hidden
            
            #line 5 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/UserSubmenu.ascx"
            this.@__BuildControl__bctrl_64();
            
            #line default
            #line hidden
            
            #line 5 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/UserSubmenu.ascx"
            @__parser.AddParsedSubObject(this._bctrl_64);
            
            #line default
            #line hidden
            
            #line 5 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/UserSubmenu.ascx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("</li>\n        <li>"));
            
            #line default
            #line hidden
            
            #line 5 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/UserSubmenu.ascx"
            this.@__BuildControl__bctrl_65();
            
            #line default
            #line hidden
            
            #line 5 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/UserSubmenu.ascx"
            @__parser.AddParsedSubObject(this._bctrl_65);
            
            #line default
            #line hidden
            
            #line 5 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/UserSubmenu.ascx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("</li>\n      </ul>\n    "));
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        private global::System.Web.UI.WebControls.HyperLink @__BuildControl__bctrl_57() {
            global::System.Web.UI.WebControls.HyperLink @__ctrl;
            
            #line 7 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/UserSubmenu.ascx"
            @__ctrl = new global::System.Web.UI.WebControls.HyperLink();
            
            #line default
            #line hidden
            
            #line 7 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/UserSubmenu.ascx"
            this._bctrl_57 = @__ctrl;
            
            #line default
            #line hidden
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            
            #line 7 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/UserSubmenu.ascx"
            @__ctrl.Text = global::System.Convert.ToString(global::System.Convert.ToString(this.GetLocalResourceObject("SubNav.Profile"), System.Globalization.CultureInfo.CurrentCulture), System.Globalization.CultureInfo.CurrentCulture);
            
            #line default
            #line hidden
            
            #line 7 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/UserSubmenu.ascx"
            @__ctrl.NavigateUrl = "/User.aspx?submenu=true";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        private global::System.Web.UI.WebControls.HyperLink @__BuildControl__bctrl_58() {
            global::System.Web.UI.WebControls.HyperLink @__ctrl;
            
            #line 8 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/UserSubmenu.ascx"
            @__ctrl = new global::System.Web.UI.WebControls.HyperLink();
            
            #line default
            #line hidden
            
            #line 8 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/UserSubmenu.ascx"
            this._bctrl_58 = @__ctrl;
            
            #line default
            #line hidden
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            
            #line 8 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/UserSubmenu.ascx"
            @__ctrl.Text = global::System.Convert.ToString(global::System.Convert.ToString(this.GetLocalResourceObject("SubNav.Character"), System.Globalization.CultureInfo.CurrentCulture), System.Globalization.CultureInfo.CurrentCulture);
            
            #line default
            #line hidden
            
            #line 8 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/UserSubmenu.ascx"
            @__ctrl.NavigateUrl = "/My/Character.aspx";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        private global::System.Web.UI.WebControls.HyperLink @__BuildControl__bctrl_59() {
            global::System.Web.UI.WebControls.HyperLink @__ctrl;
            
            #line 9 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/UserSubmenu.ascx"
            @__ctrl = new global::System.Web.UI.WebControls.HyperLink();
            
            #line default
            #line hidden
            
            #line 9 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/UserSubmenu.ascx"
            this._bctrl_59 = @__ctrl;
            
            #line default
            #line hidden
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            
            #line 9 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/UserSubmenu.ascx"
            @__ctrl.Text = global::System.Convert.ToString(global::System.Convert.ToString(this.GetLocalResourceObject("SubNav.Friends"), System.Globalization.CultureInfo.CurrentCulture), System.Globalization.CultureInfo.CurrentCulture);
            
            #line default
            #line hidden
            
            #line 9 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/UserSubmenu.ascx"
            @__ctrl.NavigateUrl = "/My/EditFriends.aspx";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        private global::System.Web.UI.WebControls.HyperLink @__BuildControl__bctrl_60() {
            global::System.Web.UI.WebControls.HyperLink @__ctrl;
            
            #line 10 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/UserSubmenu.ascx"
            @__ctrl = new global::System.Web.UI.WebControls.HyperLink();
            
            #line default
            #line hidden
            
            #line 10 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/UserSubmenu.ascx"
            this._bctrl_60 = @__ctrl;
            
            #line default
            #line hidden
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            
            #line 10 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/UserSubmenu.ascx"
            @__ctrl.Text = global::System.Convert.ToString(global::System.Convert.ToString(this.GetLocalResourceObject("SubNav.Groups"), System.Globalization.CultureInfo.CurrentCulture), System.Globalization.CultureInfo.CurrentCulture);
            
            #line default
            #line hidden
            
            #line 10 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/UserSubmenu.ascx"
            @__ctrl.NavigateUrl = "/My/Groups.aspx";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        private global::System.Web.UI.WebControls.HyperLink @__BuildControl__bctrl_61() {
            global::System.Web.UI.WebControls.HyperLink @__ctrl;
            
            #line 11 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/UserSubmenu.ascx"
            @__ctrl = new global::System.Web.UI.WebControls.HyperLink();
            
            #line default
            #line hidden
            
            #line 11 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/UserSubmenu.ascx"
            this._bctrl_61 = @__ctrl;
            
            #line default
            #line hidden
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            
            #line 11 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/UserSubmenu.ascx"
            @__ctrl.Text = global::System.Convert.ToString(global::System.Convert.ToString(this.GetLocalResourceObject("SubNav.Inventory"), System.Globalization.CultureInfo.CurrentCulture), System.Globalization.CultureInfo.CurrentCulture);
            
            #line default
            #line hidden
            
            #line 11 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/UserSubmenu.ascx"
            @__ctrl.NavigateUrl = "/My/Stuff.aspx";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        private global::System.Web.UI.WebControls.HyperLink @__BuildControl_SetsUrl() {
            global::System.Web.UI.WebControls.HyperLink @__ctrl;
            
            #line 12 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/UserSubmenu.ascx"
            @__ctrl = new global::System.Web.UI.WebControls.HyperLink();
            
            #line default
            #line hidden
            
            #line 12 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/UserSubmenu.ascx"
            this.SetsUrl = @__ctrl;
            
            #line default
            #line hidden
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            
            #line 12 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/UserSubmenu.ascx"
            @__ctrl.ID = "SetsUrl";
            
            #line default
            #line hidden
            
            #line 12 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/UserSubmenu.ascx"
            @__ctrl.Text = global::System.Convert.ToString(global::System.Convert.ToString(this.GetLocalResourceObject("SubNav.Sets"), System.Globalization.CultureInfo.CurrentCulture), System.Globalization.CultureInfo.CurrentCulture);
            
            #line default
            #line hidden
            
            #line 12 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/UserSubmenu.ascx"
            @__ctrl.NavigateUrl = "/My/Sets.aspx";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        private global::System.Web.UI.WebControls.HyperLink @__BuildControl__bctrl_62() {
            global::System.Web.UI.WebControls.HyperLink @__ctrl;
            
            #line 13 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/UserSubmenu.ascx"
            @__ctrl = new global::System.Web.UI.WebControls.HyperLink();
            
            #line default
            #line hidden
            
            #line 13 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/UserSubmenu.ascx"
            this._bctrl_62 = @__ctrl;
            
            #line default
            #line hidden
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            
            #line 13 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/UserSubmenu.ascx"
            @__ctrl.Text = global::System.Convert.ToString(global::System.Convert.ToString(this.GetLocalResourceObject("SubNav.Trade"), System.Globalization.CultureInfo.CurrentCulture), System.Globalization.CultureInfo.CurrentCulture);
            
            #line default
            #line hidden
            
            #line 13 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/UserSubmenu.ascx"
            @__ctrl.NavigateUrl = "/My/Money.aspx?tab=TradeItems";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        private global::System.Web.UI.WebControls.HyperLink @__BuildControl__bctrl_63() {
            global::System.Web.UI.WebControls.HyperLink @__ctrl;
            
            #line 14 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/UserSubmenu.ascx"
            @__ctrl = new global::System.Web.UI.WebControls.HyperLink();
            
            #line default
            #line hidden
            
            #line 14 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/UserSubmenu.ascx"
            this._bctrl_63 = @__ctrl;
            
            #line default
            #line hidden
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            
            #line 14 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/UserSubmenu.ascx"
            @__ctrl.Text = global::System.Convert.ToString(global::System.Convert.ToString(this.GetLocalResourceObject("SubNav.Money"), System.Globalization.CultureInfo.CurrentCulture), System.Globalization.CultureInfo.CurrentCulture);
            
            #line default
            #line hidden
            
            #line 14 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/UserSubmenu.ascx"
            @__ctrl.NavigateUrl = "/My/Money.aspx?tab=MyTransactions";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        private global::System.Web.UI.WebControls.HyperLink @__BuildControl__bctrl_64() {
            global::System.Web.UI.WebControls.HyperLink @__ctrl;
            
            #line 15 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/UserSubmenu.ascx"
            @__ctrl = new global::System.Web.UI.WebControls.HyperLink();
            
            #line default
            #line hidden
            
            #line 15 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/UserSubmenu.ascx"
            this._bctrl_64 = @__ctrl;
            
            #line default
            #line hidden
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            
            #line 15 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/UserSubmenu.ascx"
            @__ctrl.Text = global::System.Convert.ToString(global::System.Convert.ToString(this.GetLocalResourceObject("SubNav.Advertising"), System.Globalization.CultureInfo.CurrentCulture), System.Globalization.CultureInfo.CurrentCulture);
            
            #line default
            #line hidden
            
            #line 15 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/UserSubmenu.ascx"
            @__ctrl.NavigateUrl = "/develop?Page=ads";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        private global::System.Web.UI.WebControls.HyperLink @__BuildControl__bctrl_65() {
            global::System.Web.UI.WebControls.HyperLink @__ctrl;
            
            #line 16 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/UserSubmenu.ascx"
            @__ctrl = new global::System.Web.UI.WebControls.HyperLink();
            
            #line default
            #line hidden
            
            #line 16 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/UserSubmenu.ascx"
            this._bctrl_65 = @__ctrl;
            
            #line default
            #line hidden
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            
            #line 16 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/UserSubmenu.ascx"
            @__ctrl.Text = global::System.Convert.ToString(global::System.Convert.ToString(this.GetLocalResourceObject("SubNav.Account"), System.Globalization.CultureInfo.CurrentCulture), System.Globalization.CultureInfo.CurrentCulture);
            
            #line default
            #line hidden
            
            #line 16 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/UserSubmenu.ascx"
            @__ctrl.NavigateUrl = "/My/Account.aspx";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        protected override void FrameworkInitialize() {
            base.FrameworkInitialize();
            this.SetStringResourcePointer(global::ASP.usercontrols_navigation_usersubmenu_ascx.@__stringResource, 0);
            this.@__BuildControlTree(this);
        }
    }
}
