#pragma checksum "/home/runner/workspace/RobloxWebSite/UserControls/VisitButtonOverhead.ascx" "{406ea660-64cf-4c82-b6f0-42d48172a799}" "E07D8F09BFCC6460837B52EEB8F09F85"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
    using System;
    using System.Collections;
    using System.Collections.Specialized;
    using System.Configuration;
    using System.Text;
    using System.Text.RegularExpressions;
    using System.Web;
    using System.Web.Caching;
    using System.Web.SessionState;
    using System.Web.Security;
    using System.Web.Profile;
    using System.Web.UI;
    using System.Web.UI.WebControls;
    using System.Web.UI.HtmlControls;
    using Roblox.Website;
    using Roblox.Web.Code;
    
    
    public class usercontrols_visitbuttonoverhead_ascx : global::Roblox.Website.UserControls.VisitButtonOverhead {
        
        private static bool @__initialized = false;
        
        private static object @__stringResource = null;
        
        private static int @__autoHandlers;
        
        
        #line 15 "/home/runner/workspace/RobloxWebSite/UserControls/VisitButtonOverhead.ascx"
        protected global::ASP.usercontrols_modals_insufficientcurrencyorbc_bconlymodal_ascx _bctrl_12;
        
        #line default
        #line hidden
        
        public usercontrols_visitbuttonoverhead_ascx() {
            ((global::Roblox.Website.UserControls.VisitButtonOverhead)(this)).AppRelativeVirtualPath = "~/UserControls/VisitButtonOverhead.ascx";
            if ((global::ASP.usercontrols_visitbuttonoverhead_ascx.@__initialized == false)) {
                global::ASP.usercontrols_visitbuttonoverhead_ascx.@__initialized = true;
            }
        }
        
        [System.Obsolete()]
        protected override int AutoHandlers {
            get {
                return ASP.usercontrols_visitbuttonoverhead_ascx.@__autoHandlers;
            }
            set {
                ASP.usercontrols_visitbuttonoverhead_ascx.@__autoHandlers = value;
            }
        }
        
        protected System.Web.HttpApplication ApplicationInstance {
            get {
                return ((System.Web.HttpApplication)(this.Context.ApplicationInstance));
            }
        }
        
        protected System.Web.Profile.DefaultProfile Profile {
            get {
                return ((System.Web.Profile.DefaultProfile)(this.Context.Profile));
            }
        }
        
        private void @__RenderTree(System.Web.UI.HtmlTextWriter @__output, System.Web.UI.Control parameterContainer) {
            @__output.Write("<script type=\"text/javascript\">\n        var play_placeId = ");
            
            #line 3 "/home/runner/workspace/RobloxWebSite/UserControls/VisitButtonOverhead.ascx"
            @__output.Write(PlaceID);
            
            #line default
            #line hidden
            @__output.Write(";\n        function redirectPlaceLauncherToLogin() {\n            location.href = \"" +
                    "/login/default.aspx?ReturnUrl=\" + encodeURIComponent(\"");
            
            #line 3 "/home/runner/workspace/RobloxWebSite/UserControls/VisitButtonOverhead.ascx"
            @__output.Write(Context.Request.Url.AbsolutePath );
            
            #line default
            #line hidden
            @__output.Write("\");\n        }\n        function redirectPlaceLauncherToRegister() {\n            lo" +
                    "cation.href = \"/login/NewAge.aspx?ReturnUrl=\" + encodeURIComponent(\"");
            
            #line 3 "/home/runner/workspace/RobloxWebSite/UserControls/VisitButtonOverhead.ascx"
            @__output.Write(Context.Request.Url.AbsolutePath );
            
            #line default
            #line hidden
            @__output.Write("\");\n        }\n        function fireEventAction(action) {\n            RobloxEventM" +
                    "anager.triggerEvent(\'rbx_evt_popup_action\', { action: action });\n        }\n    <" +
                    "/script>\n    ");
            parameterContainer.Controls[0].RenderControl(@__output);
        }
        
        private void @__BuildControlTree(usercontrols_visitbuttonoverhead_ascx @__ctrl) {
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/VisitButtonOverhead.ascx"
            this.@__BuildControl__bctrl_12();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/VisitButtonOverhead.ascx"
            @__parser.AddParsedSubObject(this._bctrl_12);
            
            #line default
            #line hidden
            @__ctrl.SetRenderMethodDelegate(new System.Web.UI.RenderMethod(this.@__RenderTree));
        }
        
        private global::ASP.usercontrols_modals_insufficientcurrencyorbc_bconlymodal_ascx @__BuildControl__bctrl_12() {
            global::ASP.usercontrols_modals_insufficientcurrencyorbc_bconlymodal_ascx @__ctrl;
            
            #line 15 "/home/runner/workspace/RobloxWebSite/UserControls/VisitButtonOverhead.ascx"
            @__ctrl = new global::ASP.usercontrols_modals_insufficientcurrencyorbc_bconlymodal_ascx();
            
            #line default
            #line hidden
            
            #line 15 "/home/runner/workspace/RobloxWebSite/UserControls/VisitButtonOverhead.ascx"
            this._bctrl_12 = @__ctrl;
            
            #line default
            #line hidden
            this._bctrl_12.InitializeAsUserControl(this.Page);
            return @__ctrl;
        }
        
        protected override void FrameworkInitialize() {
            base.FrameworkInitialize();
            this.SetStringResourcePointer(global::ASP.usercontrols_visitbuttonoverhead_ascx.@__stringResource, 0);
            this.@__BuildControlTree(this);
        }
    }
}
