#pragma checksum "/home/runner/workspace/RobloxWebSite/Simple.Master" "{406ea660-64cf-4c82-b6f0-42d48172a799}" "4BB8723559E0615EA4744FA7383E0B9A"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
    using System;
    using System.Collections;
    using System.Collections.Specialized;
    using System.Configuration;
    using System.Text;
    using System.Text.RegularExpressions;
    using System.Web;
    using System.Web.Caching;
    using System.Web.SessionState;
    using System.Web.Security;
    using System.Web.Profile;
    using System.Web.UI;
    using System.Web.UI.WebControls;
    using System.Web.UI.HtmlControls;
    using Roblox.Website;
    using Roblox.Web.Code;
    using System.Web.Optimization;
    using Roblox.Web.StaticContent;
    
    
    public class simple_master : global::Roblox.Website.Simple {
        
        private static bool @__initialized = false;
        
        private static object @__stringResource = null;
        
        private static int @__autoHandlers;
        
        
        #line 17 "/home/runner/workspace/RobloxWebSite/Simple.Master"
        protected global::System.Web.UI.HtmlControls.HtmlHead _bctrl_111;
        
        #line default
        #line hidden
        
        
        #line 18 "/home/runner/workspace/RobloxWebSite/Simple.Master"
        protected global::System.Web.UI.HtmlControls.HtmlMeta _bctrl_112;
        
        #line default
        #line hidden
        
        
        #line 19 "/home/runner/workspace/RobloxWebSite/Simple.Master"
        protected global::System.Web.UI.HtmlControls.HtmlTitle _bctrl_113;
        
        #line default
        #line hidden
        
        
        #line 23 "/home/runner/workspace/RobloxWebSite/Simple.Master"
        protected global::System.Web.UI.HtmlControls.HtmlLink _bctrl_114;
        
        #line default
        #line hidden
        
        
        #line 24 "/home/runner/workspace/RobloxWebSite/Simple.Master"
        protected global::System.Web.UI.HtmlControls.HtmlMeta _bctrl_115;
        
        #line default
        #line hidden
        
        
        #line 25 "/home/runner/workspace/RobloxWebSite/Simple.Master"
        protected global::System.Web.UI.HtmlControls.HtmlMeta _bctrl_116;
        
        #line default
        #line hidden
        
        
        #line 28 "/home/runner/workspace/RobloxWebSite/Simple.Master"
        protected global::System.Web.UI.HtmlControls.HtmlMeta _bctrl_117;
        
        #line default
        #line hidden
        
        
        #line 30 "/home/runner/workspace/RobloxWebSite/Simple.Master"
        protected global::ASP.usercontrols_trackingpixels_googleanalytics_ascx _bctrl_118;
        
        #line default
        #line hidden
        
        
        #line 37 "/home/runner/workspace/RobloxWebSite/Simple.Master"
        protected global::ASP.usercontrols_trackingpixels_javascripterrortracker_ascx _bctrl_119;
        
        #line default
        #line hidden
        
        private System.Web.UI.ITemplate @__Template_cphRoblox;
        
        private System.Web.UI.ITemplate @__Template_cphFooter;
        
        
        #line 75 "/home/runner/workspace/RobloxWebSite/Simple.Master"
        protected global::ASP.usercontrols_modals_confirmationmodal_ascx _bctrl_120;
        
        #line default
        #line hidden
        
        
        #line 76 "/home/runner/workspace/RobloxWebSite/Simple.Master"
        protected global::ASP.usercontrols_modals_upselladmodal_ascx _bctrl_121;
        
        #line default
        #line hidden
        
        
        #line 77 "/home/runner/workspace/RobloxWebSite/Simple.Master"
        protected global::ASP.usercontrols_trackingpixels_urchintracker_ascx _bctrl_122;
        
        #line default
        #line hidden
        
        
        #line 78 "/home/runner/workspace/RobloxWebSite/Simple.Master"
        protected global::ASP.usercontrols_trackingpixels_robloxeventmanager_ascx _bctrl_123;
        
        #line default
        #line hidden
        
        public simple_master() {
            ((global::Roblox.Website.Simple)(this)).AppRelativeVirtualPath = "~/Simple.Master";
            if ((global::ASP.simple_master.@__initialized == false)) {
                global::ASP.simple_master.@__initialized = true;
            }
            System.Collections.IList @__contentPlaceHolders = this.ContentPlaceHolders;
            @__contentPlaceHolders.Add("cphroblox");
            @__contentPlaceHolders.Add("cphfooter");
        }
        
        [System.Obsolete()]
        protected override int AutoHandlers {
            get {
                return ASP.simple_master.@__autoHandlers;
            }
            set {
                ASP.simple_master.@__autoHandlers = value;
            }
        }
        
        protected System.Web.HttpApplication ApplicationInstance {
            get {
                return ((System.Web.HttpApplication)(this.Context.ApplicationInstance));
            }
        }
        
        [TemplateContainer(typeof(System.Web.UI.MasterPage))]
        [TemplateInstanceAttribute(System.Web.UI.TemplateInstance.Single)]
        public virtual System.Web.UI.ITemplate Template_cphRoblox {
            get {
                return this.@__Template_cphRoblox;
            }
            set {
                this.@__Template_cphRoblox = value;
            }
        }
        
        [TemplateContainer(typeof(System.Web.UI.MasterPage))]
        [TemplateInstanceAttribute(System.Web.UI.TemplateInstance.Single)]
        public virtual System.Web.UI.ITemplate Template_cphFooter {
            get {
                return this.@__Template_cphFooter;
            }
            set {
                this.@__Template_cphFooter = value;
            }
        }
        
        protected System.Web.Profile.DefaultProfile Profile {
            get {
                return ((System.Web.Profile.DefaultProfile)(this.Context.Profile));
            }
        }
        
        private void @__RenderTree(System.Web.UI.HtmlTextWriter @__output, System.Web.UI.Control parameterContainer) {
            @__output.Write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org" +
                    "/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\n<html xmlns=\"http://www.w3.org/1999/xht" +
                    "ml\" xml:lang=\"en\" id=\"www-roblox-com\">\n<!-- MachineID: ");
            
            #line 16 "/home/runner/workspace/RobloxWebSite/Simple.Master"
            @__output.Write(System.Web.HttpUtility.HtmlEncode( Environment.MachineName ));
            
            #line default
            #line hidden
            @__output.Write(" -->\n");
            parameterContainer.Controls[0].RenderControl(@__output);
            @__output.Write("\n<body class=\"\">\n    ");
            parameterContainer.Controls[1].RenderControl(@__output);
            @__output.Write("\n</body>\n</html>");
        }
        
        private void @__BuildControlTree(simple_master @__ctrl) {
            
            #line 1 "/home/runner/workspace/RobloxWebSite/Simple.Master"
            this.@__BuildControl__bctrl_111();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 1 "/home/runner/workspace/RobloxWebSite/Simple.Master"
            @__parser.AddParsedSubObject(this._bctrl_111);
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/Simple.Master"
            this.@__BuildControl_aspnetForm();
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/Simple.Master"
            @__parser.AddParsedSubObject(this.aspnetForm);
            
            #line default
            #line hidden
            @__ctrl.SetRenderMethodDelegate(new System.Web.UI.RenderMethod(this.@__RenderTree));
        }
        
        private void @__Render__bctrl_111(System.Web.UI.HtmlTextWriter @__output, System.Web.UI.Control parameterContainer) {
            parameterContainer.Controls[0].RenderControl(@__output);
            parameterContainer.Controls[1].RenderControl(@__output);
            
            #line 20 "/home/runner/workspace/RobloxWebSite/Simple.Master"
            @__output.Write(System.Web.HttpUtility.HtmlEncode( RobloxCSS.RenderBundle("main") ));
            
            #line default
            #line hidden
            
            #line 21 "/home/runner/workspace/RobloxWebSite/Simple.Master"
            @__output.Write(System.Web.HttpUtility.HtmlEncode( RobloxCSS.Render(StaticContent.GetPageCSSBundle()) ));
            
            #line default
            #line hidden
            parameterContainer.Controls[2].RenderControl(@__output);
            parameterContainer.Controls[3].RenderControl(@__output);
            parameterContainer.Controls[4].RenderControl(@__output);
            @__output.Write("<meta name=\"description\" content=\"");
            
            #line 26 "/home/runner/workspace/RobloxWebSite/Simple.Master"
            @__output.Write(MetaTagListViewModel.Description );
            
            #line default
            #line hidden
            @__output.Write("\" />\n    <meta name=\"keywords\" content=\"");
            
            #line 27 "/home/runner/workspace/RobloxWebSite/Simple.Master"
            @__output.Write(MetaTagListViewModel.Keywords );
            
            #line default
            #line hidden
            @__output.Write("\" />\n    ");
            parameterContainer.Controls[5].RenderControl(@__output);
            parameterContainer.Controls[6].RenderControl(@__output);
            @__output.Write(@"<script type='text/javascript' src='//ajax.aspnetcdn.com/ajax/jQuery/jquery-1.7.2.min.js'></script>
<script type='text/javascript'>window.jQuery || document.write(""<script type='text/javascript' src='/js/jquery/jquery-1.7.2.min.js'><\/script>"")</script>
<script type='text/javascript' src='//ajax.aspnetcdn.com/ajax/4.0/1/MicrosoftAjax.js'></script>
<script type='text/javascript'>window.Sys || document.write(""<script type='text/javascript' src='/js/Microsoft/MicrosoftAjax.js'><\/script>"")</script>
    ");
            
            #line 35 "/home/runner/workspace/RobloxWebSite/Simple.Master"
            @__output.Write(System.Web.HttpUtility.HtmlEncode( RobloxScripts.RenderBundle("simple") ));
            
            #line default
            #line hidden
            parameterContainer.Controls[7].RenderControl(@__output);
            
            #line 38 "/home/runner/workspace/RobloxWebSite/Simple.Master"
            @__output.Write(System.Web.HttpUtility.HtmlEncode( RobloxScripts.Render(StaticContent.GetPageScriptBundle()) ));
            
            #line default
            #line hidden
            @__output.Write(@"<script type=""text/javascript"">
        $(function () {
            $('.tooltip').tipsy();
            $('.tooltip-top').tipsy({ gravity: 's' });
            $('.tooltip-right').tipsy({ gravity: 'w' });
            $('.tooltip-left').tipsy({ gravity: 'e' });
            $('.tooltip-bottom').tipsy({ gravity: 'n' });
            $('.tooltip-right-html').tipsy({ gravity: 'w', html: true, delayOut: 1000 });
            $('.tooltip-left-html').tipsy({ gravity: 'e', html: true, delayOut: 1000 });
        });
    </script>
");
        }
        
        private global::System.Web.UI.HtmlControls.HtmlHead @__BuildControl__bctrl_111() {
            global::System.Web.UI.HtmlControls.HtmlHead @__ctrl;
            
            #line 17 "/home/runner/workspace/RobloxWebSite/Simple.Master"
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlHead("head");
            
            #line default
            #line hidden
            
            #line 17 "/home/runner/workspace/RobloxWebSite/Simple.Master"
            this._bctrl_111 = @__ctrl;
            
            #line default
            #line hidden
            
            #line 17 "/home/runner/workspace/RobloxWebSite/Simple.Master"
            this.@__BuildControl__bctrl_112();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 17 "/home/runner/workspace/RobloxWebSite/Simple.Master"
            @__parser.AddParsedSubObject(this._bctrl_112);
            
            #line default
            #line hidden
            
            #line 17 "/home/runner/workspace/RobloxWebSite/Simple.Master"
            this.@__BuildControl__bctrl_113();
            
            #line default
            #line hidden
            
            #line 17 "/home/runner/workspace/RobloxWebSite/Simple.Master"
            @__parser.AddParsedSubObject(this._bctrl_113);
            
            #line default
            #line hidden
            
            #line 17 "/home/runner/workspace/RobloxWebSite/Simple.Master"
            this.@__BuildControl__bctrl_114();
            
            #line default
            #line hidden
            
            #line 17 "/home/runner/workspace/RobloxWebSite/Simple.Master"
            @__parser.AddParsedSubObject(this._bctrl_114);
            
            #line default
            #line hidden
            
            #line 17 "/home/runner/workspace/RobloxWebSite/Simple.Master"
            this.@__BuildControl__bctrl_115();
            
            #line default
            #line hidden
            
            #line 17 "/home/runner/workspace/RobloxWebSite/Simple.Master"
            @__parser.AddParsedSubObject(this._bctrl_115);
            
            #line default
            #line hidden
            
            #line 17 "/home/runner/workspace/RobloxWebSite/Simple.Master"
            this.@__BuildControl__bctrl_116();
            
            #line default
            #line hidden
            
            #line 17 "/home/runner/workspace/RobloxWebSite/Simple.Master"
            @__parser.AddParsedSubObject(this._bctrl_116);
            
            #line default
            #line hidden
            
            #line 17 "/home/runner/workspace/RobloxWebSite/Simple.Master"
            this.@__BuildControl__bctrl_117();
            
            #line default
            #line hidden
            
            #line 17 "/home/runner/workspace/RobloxWebSite/Simple.Master"
            @__parser.AddParsedSubObject(this._bctrl_117);
            
            #line default
            #line hidden
            
            #line 17 "/home/runner/workspace/RobloxWebSite/Simple.Master"
            this.@__BuildControl__bctrl_118();
            
            #line default
            #line hidden
            
            #line 17 "/home/runner/workspace/RobloxWebSite/Simple.Master"
            @__parser.AddParsedSubObject(this._bctrl_118);
            
            #line default
            #line hidden
            
            #line 17 "/home/runner/workspace/RobloxWebSite/Simple.Master"
            this.@__BuildControl__bctrl_119();
            
            #line default
            #line hidden
            
            #line 17 "/home/runner/workspace/RobloxWebSite/Simple.Master"
            @__parser.AddParsedSubObject(this._bctrl_119);
            
            #line default
            #line hidden
            @__ctrl.SetRenderMethodDelegate(new System.Web.UI.RenderMethod(this.@__Render__bctrl_111));
            return @__ctrl;
        }
        
        private global::System.Web.UI.HtmlControls.HtmlMeta @__BuildControl__bctrl_112() {
            global::System.Web.UI.HtmlControls.HtmlMeta @__ctrl;
            
            #line 18 "/home/runner/workspace/RobloxWebSite/Simple.Master"
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlMeta();
            
            #line default
            #line hidden
            
            #line 18 "/home/runner/workspace/RobloxWebSite/Simple.Master"
            this._bctrl_112 = @__ctrl;
            
            #line default
            #line hidden
            
            #line 18 "/home/runner/workspace/RobloxWebSite/Simple.Master"
            @__ctrl.Content = "IE=edge,requiresActiveX=true";
            
            #line default
            #line hidden
            
            #line 18 "/home/runner/workspace/RobloxWebSite/Simple.Master"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("http-equiv", "X-UA-Compatible");
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        private void @__Render__bctrl_113(System.Web.UI.HtmlTextWriter @__output, System.Web.UI.Control parameterContainer) {
            
            #line 19 "/home/runner/workspace/RobloxWebSite/Simple.Master"
            @__output.Write(Page.Title);
            
            #line default
            #line hidden
        }
        
        private global::System.Web.UI.HtmlControls.HtmlTitle @__BuildControl__bctrl_113() {
            global::System.Web.UI.HtmlControls.HtmlTitle @__ctrl;
            
            #line 19 "/home/runner/workspace/RobloxWebSite/Simple.Master"
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlTitle();
            
            #line default
            #line hidden
            
            #line 19 "/home/runner/workspace/RobloxWebSite/Simple.Master"
            this._bctrl_113 = @__ctrl;
            
            #line default
            #line hidden
            @__ctrl.SetRenderMethodDelegate(new System.Web.UI.RenderMethod(this.@__Render__bctrl_113));
            return @__ctrl;
        }
        
        private global::System.Web.UI.HtmlControls.HtmlLink @__BuildControl__bctrl_114() {
            global::System.Web.UI.HtmlControls.HtmlLink @__ctrl;
            
            #line 23 "/home/runner/workspace/RobloxWebSite/Simple.Master"
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlLink();
            
            #line default
            #line hidden
            
            #line 23 "/home/runner/workspace/RobloxWebSite/Simple.Master"
            this._bctrl_114 = @__ctrl;
            
            #line default
            #line hidden
            
            #line 23 "/home/runner/workspace/RobloxWebSite/Simple.Master"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("rel", "icon");
            
            #line default
            #line hidden
            
            #line 23 "/home/runner/workspace/RobloxWebSite/Simple.Master"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("type", "image/vnd.microsoft.icon");
            
            #line default
            #line hidden
            
            #line 23 "/home/runner/workspace/RobloxWebSite/Simple.Master"
            @__ctrl.Href = "/favicon.ico";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        private global::System.Web.UI.HtmlControls.HtmlMeta @__BuildControl__bctrl_115() {
            global::System.Web.UI.HtmlControls.HtmlMeta @__ctrl;
            
            #line 24 "/home/runner/workspace/RobloxWebSite/Simple.Master"
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlMeta();
            
            #line default
            #line hidden
            
            #line 24 "/home/runner/workspace/RobloxWebSite/Simple.Master"
            this._bctrl_115 = @__ctrl;
            
            #line default
            #line hidden
            
            #line 24 "/home/runner/workspace/RobloxWebSite/Simple.Master"
            @__ctrl.Content = "text/html; charset=utf-8";
            
            #line default
            #line hidden
            
            #line 24 "/home/runner/workspace/RobloxWebSite/Simple.Master"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("http-equiv", "Content-Type");
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        private global::System.Web.UI.HtmlControls.HtmlMeta @__BuildControl__bctrl_116() {
            global::System.Web.UI.HtmlControls.HtmlMeta @__ctrl;
            
            #line 25 "/home/runner/workspace/RobloxWebSite/Simple.Master"
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlMeta();
            
            #line default
            #line hidden
            
            #line 25 "/home/runner/workspace/RobloxWebSite/Simple.Master"
            this._bctrl_116 = @__ctrl;
            
            #line default
            #line hidden
            
            #line 25 "/home/runner/workspace/RobloxWebSite/Simple.Master"
            @__ctrl.Content = "ROBLOX Corporation";
            
            #line default
            #line hidden
            
            #line 25 "/home/runner/workspace/RobloxWebSite/Simple.Master"
            @__ctrl.Name = "author";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        private global::System.Web.UI.HtmlControls.HtmlMeta @__BuildControl__bctrl_117() {
            global::System.Web.UI.HtmlControls.HtmlMeta @__ctrl;
            
            #line 28 "/home/runner/workspace/RobloxWebSite/Simple.Master"
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlMeta();
            
            #line default
            #line hidden
            
            #line 28 "/home/runner/workspace/RobloxWebSite/Simple.Master"
            this._bctrl_117 = @__ctrl;
            
            #line default
            #line hidden
            
            #line 28 "/home/runner/workspace/RobloxWebSite/Simple.Master"
            @__ctrl.Content = "all";
            
            #line default
            #line hidden
            
            #line 28 "/home/runner/workspace/RobloxWebSite/Simple.Master"
            @__ctrl.Name = "robots";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        private global::ASP.usercontrols_trackingpixels_googleanalytics_ascx @__BuildControl__bctrl_118() {
            global::ASP.usercontrols_trackingpixels_googleanalytics_ascx @__ctrl;
            
            #line 30 "/home/runner/workspace/RobloxWebSite/Simple.Master"
            @__ctrl = new global::ASP.usercontrols_trackingpixels_googleanalytics_ascx();
            
            #line default
            #line hidden
            
            #line 30 "/home/runner/workspace/RobloxWebSite/Simple.Master"
            this._bctrl_118 = @__ctrl;
            
            #line default
            #line hidden
            this._bctrl_118.InitializeAsUserControl(this.Page);
            return @__ctrl;
        }
        
        private global::ASP.usercontrols_trackingpixels_javascripterrortracker_ascx @__BuildControl__bctrl_119() {
            global::ASP.usercontrols_trackingpixels_javascripterrortracker_ascx @__ctrl;
            
            #line 37 "/home/runner/workspace/RobloxWebSite/Simple.Master"
            @__ctrl = new global::ASP.usercontrols_trackingpixels_javascripterrortracker_ascx();
            
            #line default
            #line hidden
            
            #line 37 "/home/runner/workspace/RobloxWebSite/Simple.Master"
            this._bctrl_119 = @__ctrl;
            
            #line default
            #line hidden
            this._bctrl_119.InitializeAsUserControl(this.Page);
            return @__ctrl;
        }
        
        private global::System.Web.UI.HtmlControls.HtmlForm @__BuildControl_aspnetForm() {
            global::System.Web.UI.HtmlControls.HtmlForm @__ctrl;
            
            #line 52 "/home/runner/workspace/RobloxWebSite/Simple.Master"
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlForm();
            
            #line default
            #line hidden
            
            #line 52 "/home/runner/workspace/RobloxWebSite/Simple.Master"
            this.aspnetForm = @__ctrl;
            
            #line default
            #line hidden
            
            #line 52 "/home/runner/workspace/RobloxWebSite/Simple.Master"
            @__ctrl.ID = "aspnetForm";
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 52 "/home/runner/workspace/RobloxWebSite/Simple.Master"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
        <div class="""">
        <div class="""">

    <div id=""Container"">
        
        <div class=""site-header"">
		    <div id=""navigation-container"">
                <a href=""/Default.aspx"" class=""btn-logo""></a>
            </div>
        </div>
        
        <div style=""clear: both""></div>
        
        <div id=""Body"" class=""simple-body"">
            "));
            
            #line default
            #line hidden
            
            #line 52 "/home/runner/workspace/RobloxWebSite/Simple.Master"
            this.@__BuildControl_cphRoblox();
            
            #line default
            #line hidden
            
            #line 52 "/home/runner/workspace/RobloxWebSite/Simple.Master"
            @__parser.AddParsedSubObject(this.cphRoblox);
            
            #line default
            #line hidden
            
            #line 52 "/home/runner/workspace/RobloxWebSite/Simple.Master"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\n        </div>\n    "));
            
            #line default
            #line hidden
            
            #line 52 "/home/runner/workspace/RobloxWebSite/Simple.Master"
            this.@__BuildControl_cphFooter();
            
            #line default
            #line hidden
            
            #line 52 "/home/runner/workspace/RobloxWebSite/Simple.Master"
            @__parser.AddParsedSubObject(this.cphFooter);
            
            #line default
            #line hidden
            
            #line 52 "/home/runner/workspace/RobloxWebSite/Simple.Master"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\n    </div>\n        </div></div>\n    "));
            
            #line default
            #line hidden
            
            #line 52 "/home/runner/workspace/RobloxWebSite/Simple.Master"
            this.@__BuildControl__bctrl_120();
            
            #line default
            #line hidden
            
            #line 52 "/home/runner/workspace/RobloxWebSite/Simple.Master"
            @__parser.AddParsedSubObject(this._bctrl_120);
            
            #line default
            #line hidden
            
            #line 52 "/home/runner/workspace/RobloxWebSite/Simple.Master"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\n    "));
            
            #line default
            #line hidden
            
            #line 52 "/home/runner/workspace/RobloxWebSite/Simple.Master"
            this.@__BuildControl__bctrl_121();
            
            #line default
            #line hidden
            
            #line 52 "/home/runner/workspace/RobloxWebSite/Simple.Master"
            @__parser.AddParsedSubObject(this._bctrl_121);
            
            #line default
            #line hidden
            
            #line 52 "/home/runner/workspace/RobloxWebSite/Simple.Master"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\n    "));
            
            #line default
            #line hidden
            
            #line 52 "/home/runner/workspace/RobloxWebSite/Simple.Master"
            this.@__BuildControl__bctrl_122();
            
            #line default
            #line hidden
            
            #line 52 "/home/runner/workspace/RobloxWebSite/Simple.Master"
            @__parser.AddParsedSubObject(this._bctrl_122);
            
            #line default
            #line hidden
            
            #line 52 "/home/runner/workspace/RobloxWebSite/Simple.Master"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\n    "));
            
            #line default
            #line hidden
            
            #line 52 "/home/runner/workspace/RobloxWebSite/Simple.Master"
            this.@__BuildControl__bctrl_123();
            
            #line default
            #line hidden
            
            #line 52 "/home/runner/workspace/RobloxWebSite/Simple.Master"
            @__parser.AddParsedSubObject(this._bctrl_123);
            
            #line default
            #line hidden
            
            #line 52 "/home/runner/workspace/RobloxWebSite/Simple.Master"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\n"));
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        private global::System.Web.UI.WebControls.ContentPlaceHolder @__BuildControl_cphRoblox() {
            global::System.Web.UI.WebControls.ContentPlaceHolder @__ctrl;
            
            #line 67 "/home/runner/workspace/RobloxWebSite/Simple.Master"
            @__ctrl = new global::System.Web.UI.WebControls.ContentPlaceHolder();
            
            #line default
            #line hidden
            
            #line 67 "/home/runner/workspace/RobloxWebSite/Simple.Master"
            this.cphRoblox = @__ctrl;
            
            #line default
            #line hidden
            
            #line 67 "/home/runner/workspace/RobloxWebSite/Simple.Master"
            @__ctrl.ID = "cphRoblox";
            
            #line default
            #line hidden
            if ((this.ContentTemplates != null)) {
                this.@__Template_cphRoblox = ((System.Web.UI.ITemplate)(this.ContentTemplates["cphRoblox"]));
            }
            if ((this.@__Template_cphRoblox != null)) {
                this.@__Template_cphRoblox.InstantiateIn(@__ctrl);
            }
            else {
                System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
                
                #line 67 "/home/runner/workspace/RobloxWebSite/Simple.Master"
                @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\n            "));
                
                #line default
                #line hidden
            }
            return @__ctrl;
        }
        
        private global::System.Web.UI.WebControls.ContentPlaceHolder @__BuildControl_cphFooter() {
            global::System.Web.UI.WebControls.ContentPlaceHolder @__ctrl;
            
            #line 70 "/home/runner/workspace/RobloxWebSite/Simple.Master"
            @__ctrl = new global::System.Web.UI.WebControls.ContentPlaceHolder();
            
            #line default
            #line hidden
            
            #line 70 "/home/runner/workspace/RobloxWebSite/Simple.Master"
            this.cphFooter = @__ctrl;
            
            #line default
            #line hidden
            
            #line 70 "/home/runner/workspace/RobloxWebSite/Simple.Master"
            @__ctrl.ID = "cphFooter";
            
            #line default
            #line hidden
            if ((this.ContentTemplates != null)) {
                this.@__Template_cphFooter = ((System.Web.UI.ITemplate)(this.ContentTemplates["cphFooter"]));
            }
            if ((this.@__Template_cphFooter != null)) {
                this.@__Template_cphFooter.InstantiateIn(@__ctrl);
            }
            else {
                System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
                
                #line 70 "/home/runner/workspace/RobloxWebSite/Simple.Master"
                @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\n        "));
                
                #line default
                #line hidden
                
                #line 70 "/home/runner/workspace/RobloxWebSite/Simple.Master"
                this.@__BuildControl_rbxFooter();
                
                #line default
                #line hidden
                
                #line 70 "/home/runner/workspace/RobloxWebSite/Simple.Master"
                @__parser.AddParsedSubObject(this.rbxFooter);
                
                #line default
                #line hidden
                
                #line 70 "/home/runner/workspace/RobloxWebSite/Simple.Master"
                @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\n    "));
                
                #line default
                #line hidden
            }
            return @__ctrl;
        }
        
        private global::ASP.usercontrols_navigation_footer_ascx @__BuildControl_rbxFooter() {
            global::ASP.usercontrols_navigation_footer_ascx @__ctrl;
            
            #line 71 "/home/runner/workspace/RobloxWebSite/Simple.Master"
            @__ctrl = new global::ASP.usercontrols_navigation_footer_ascx();
            
            #line default
            #line hidden
            
            #line 71 "/home/runner/workspace/RobloxWebSite/Simple.Master"
            this.rbxFooter = @__ctrl;
            
            #line default
            #line hidden
            this.rbxFooter.InitializeAsUserControl(this.Page);
            
            #line 71 "/home/runner/workspace/RobloxWebSite/Simple.Master"
            @__ctrl.ID = "rbxFooter";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        private global::ASP.usercontrols_modals_confirmationmodal_ascx @__BuildControl__bctrl_120() {
            global::ASP.usercontrols_modals_confirmationmodal_ascx @__ctrl;
            
            #line 75 "/home/runner/workspace/RobloxWebSite/Simple.Master"
            @__ctrl = new global::ASP.usercontrols_modals_confirmationmodal_ascx();
            
            #line default
            #line hidden
            
            #line 75 "/home/runner/workspace/RobloxWebSite/Simple.Master"
            this._bctrl_120 = @__ctrl;
            
            #line default
            #line hidden
            this._bctrl_120.InitializeAsUserControl(this.Page);
            return @__ctrl;
        }
        
        private global::ASP.usercontrols_modals_upselladmodal_ascx @__BuildControl__bctrl_121() {
            global::ASP.usercontrols_modals_upselladmodal_ascx @__ctrl;
            
            #line 76 "/home/runner/workspace/RobloxWebSite/Simple.Master"
            @__ctrl = new global::ASP.usercontrols_modals_upselladmodal_ascx();
            
            #line default
            #line hidden
            
            #line 76 "/home/runner/workspace/RobloxWebSite/Simple.Master"
            this._bctrl_121 = @__ctrl;
            
            #line default
            #line hidden
            this._bctrl_121.InitializeAsUserControl(this.Page);
            return @__ctrl;
        }
        
        private global::ASP.usercontrols_trackingpixels_urchintracker_ascx @__BuildControl__bctrl_122() {
            global::ASP.usercontrols_trackingpixels_urchintracker_ascx @__ctrl;
            
            #line 77 "/home/runner/workspace/RobloxWebSite/Simple.Master"
            @__ctrl = new global::ASP.usercontrols_trackingpixels_urchintracker_ascx();
            
            #line default
            #line hidden
            
            #line 77 "/home/runner/workspace/RobloxWebSite/Simple.Master"
            this._bctrl_122 = @__ctrl;
            
            #line default
            #line hidden
            this._bctrl_122.InitializeAsUserControl(this.Page);
            return @__ctrl;
        }
        
        private global::ASP.usercontrols_trackingpixels_robloxeventmanager_ascx @__BuildControl__bctrl_123() {
            global::ASP.usercontrols_trackingpixels_robloxeventmanager_ascx @__ctrl;
            
            #line 78 "/home/runner/workspace/RobloxWebSite/Simple.Master"
            @__ctrl = new global::ASP.usercontrols_trackingpixels_robloxeventmanager_ascx();
            
            #line default
            #line hidden
            
            #line 78 "/home/runner/workspace/RobloxWebSite/Simple.Master"
            this._bctrl_123 = @__ctrl;
            
            #line default
            #line hidden
            this._bctrl_123.InitializeAsUserControl(this.Page);
            return @__ctrl;
        }
        
        protected override void FrameworkInitialize() {
            base.FrameworkInitialize();
            this.SetStringResourcePointer(global::ASP.simple_master.@__stringResource, 0);
            this.@__BuildControlTree(this);
        }
    }
}
