#pragma checksum "/home/runner/workspace/RobloxWebSite/UserControls/SignupForm.ascx" "{406ea660-64cf-4c82-b6f0-42d48172a799}" "9531B9F6C8C4E51B16611A8415073DC6"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
    using System;
    using System.Collections;
    using System.Collections.Specialized;
    using System.Configuration;
    using System.Text;
    using System.Text.RegularExpressions;
    using System.Web;
    using System.Web.Caching;
    using System.Web.SessionState;
    using System.Web.Security;
    using System.Web.Profile;
    using System.Web.UI;
    using System.Web.UI.WebControls;
    using System.Web.UI.HtmlControls;
    using Roblox.Website;
    using Roblox.Web.Code;
    
    
    public class usercontrols_signupform_ascx : global::Roblox.Website.UserControls.SignupForm {
        
        private static bool @__initialized = false;
        
        private static object @__stringResource = null;
        
        private static int @__autoHandlers;
        
        
        #line 6 "/home/runner/workspace/RobloxWebSite/UserControls/SignupForm.ascx"
        protected global::System.Web.UI.WebControls.ListItemCollection _bctrl_101;
        
        #line default
        #line hidden
        
        
        #line 7 "/home/runner/workspace/RobloxWebSite/UserControls/SignupForm.ascx"
        protected global::System.Web.UI.WebControls.ListItemCollection _bctrl_102;
        
        #line default
        #line hidden
        
        
        #line 8 "/home/runner/workspace/RobloxWebSite/UserControls/SignupForm.ascx"
        protected global::System.Web.UI.WebControls.ListItemCollection _bctrl_103;
        
        #line default
        #line hidden
        
        
        #line 104 "/home/runner/workspace/RobloxWebSite/UserControls/SignupForm.ascx"
        protected global::System.Web.UI.WebControls.LinkButton _bctrl_104;
        
        #line default
        #line hidden
        
        public usercontrols_signupform_ascx() {
            ((global::Roblox.Website.UserControls.SignupForm)(this)).AppRelativeVirtualPath = "~/UserControls/SignupForm.ascx";
            if ((global::ASP.usercontrols_signupform_ascx.@__initialized == false)) {
                global::ASP.usercontrols_signupform_ascx.@__initialized = true;
            }
        }
        
        [System.Obsolete()]
        protected override int AutoHandlers {
            get {
                return ASP.usercontrols_signupform_ascx.@__autoHandlers;
            }
            set {
                ASP.usercontrols_signupform_ascx.@__autoHandlers = value;
            }
        }
        
        protected System.Web.HttpApplication ApplicationInstance {
            get {
                return ((System.Web.HttpApplication)(this.Context.ApplicationInstance));
            }
        }
        
        protected System.Web.Profile.DefaultProfile Profile {
            get {
                return ((System.Web.Profile.DefaultProfile)(this.Context.Profile));
            }
        }
        
        private void @__BuildControlTree(usercontrols_signupform_ascx @__ctrl) {
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/SignupForm.ascx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("<div class=\"formRow\">\n    <label class=\"form-label\" for=\"birthdate\">Birthday</lab" +
                        "el>\n    <div class=\"rightFormColumn\">\n        <div class=\"inputColumn radio\">\n\t\t" +
                        "\t"));
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/SignupForm.ascx"
            this.@__BuildControl_lstMonths();
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/SignupForm.ascx"
            @__parser.AddParsedSubObject(this.lstMonths);
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/SignupForm.ascx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\n\t\t\t"));
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/SignupForm.ascx"
            this.@__BuildControl_lstDays();
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/SignupForm.ascx"
            @__parser.AddParsedSubObject(this.lstDays);
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/SignupForm.ascx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\n\t\t\t"));
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/SignupForm.ascx"
            this.@__BuildControl_lstYears();
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/SignupForm.ascx"
            @__parser.AddParsedSubObject(this.lstYears);
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/SignupForm.ascx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
        </div>
        <div class=""validation"">
            <table id=""birthdayError"" class=""validator-container"">
	<tr>
		<td><div class=""validator-tooltip-top""></div><div class=""validator-tooltip-main"">
                <p id=""birthdayErrorParagraph"">Invalid birthday</p>
            </div><div class=""validator-tooltip-bottom""></div></td>
	</tr>
</table>

            <div id=""birthdayGood"" class=""validator-checkmark""></div>
        </div>
        <div class=""clear"" style=""font-size:0;""></div>
        <span class=""tip-text"">Enter your birthday for a personalized experience.<br/>It will not be given to any third party.</span>
    </div>
    
    </div>

    <div class=""formRow"">
        <label class=""form-label"" for=""gender"">Gender:</label>

        <div class=""formRadio signupPage"">
            "));
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/SignupForm.ascx"
            this.@__BuildControl_MaleBtn();
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/SignupForm.ascx"
            @__parser.AddParsedSubObject(this.MaleBtn);
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/SignupForm.ascx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\n            "));
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/SignupForm.ascx"
            this.@__BuildControl_FemaleBtn();
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/SignupForm.ascx"
            @__parser.AddParsedSubObject(this.FemaleBtn);
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/SignupForm.ascx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
        </div>

        <div class=""validation"">
            <div id=""genderError"" class=""validator-container"" style=""position:absolute"">
                <div class=""validator-tooltip-top""></div>
                <div class=""validator-tooltip-main"">
                    <p>Required field</p>
                </div>
                <div class=""validator-tooltip-bottom""></div>
            </div>
            <div id=""genderGood"" class=""validator-checkmark""></div>
        </div>
    </div>

    <div class=""formRow"">
    <label class=""form-label"" for=""username"">Desired Username:</label>
    <div class=""rightFormColumn"">
        <div class=""inputColumn"">
            "));
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/SignupForm.ascx"
            this.@__BuildControl_UserName();
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/SignupForm.ascx"
            @__parser.AddParsedSubObject(this.UserName);
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/SignupForm.ascx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\n        </div>\n        <div class=\"validation\">\n            <table id=\"UsernameE" +
                        "rror\" class=\"validator-container\">\n            <tr><td><div class=\"validator-too" +
                        "ltip-top\"></div><div class=\"validator-tooltip-main\">\n                <div id=\"us" +
                        "ernameErrorMessage\"></div>\n            </div><div class=\"validator-tooltip-botto" +
                        "m\"></div></td></tr>\n            </table>\n        \n            <div id=\"usernameG" +
                        "ood\" class=\"validator-checkmark\"></div>\n        </div>\n        <div class=\"clear" +
                        "\" style=\"font-size:0;\"></div>\n        <span class=\"tip-text\">3-20 alphanumeric c" +
                        "haracters, no spaces. <br />Do not use your real name.</span>\n    </div>\n\n    </" +
                        "div>\n    <div class=\"formRow\">\n    <label class=\"form-label\" for=\"password1\">Pas" +
                        "sword:</label>\n    <div class=\"rightFormColumn\">\n        <div class=\"inputColumn" +
                        "\">\n            <input name=\"pass\" value=\"\" id=\"Password\" class=\"text-box text-bo" +
                        "x-large\"  TabIndex=\"7\" type=\"password\" onkeyup=\"Roblox.SignupFormValidator.check" +
                        "Password();\"/>\n        </div>\n        <div class=\"validation\">\n            <tabl" +
                        "e id=\"passwordError\" class=\"validator-container\">\n            <tr><td><div class" +
                        "=\"validator-tooltip-top\"></div><div class=\"validator-tooltip-main\">\n            " +
                        "    <div id=\"passwordErrorMessage\"></div>\n            </div><div class=\"validato" +
                        "r-tooltip-bottom\"></div></td></tr>\n            </table>\n            <div id=\"pas" +
                        "swordGood\" class=\"validator-checkmark\"></div>\n        </div>\n        <div class=" +
                        "\"clear\" style=\"font-size:0;\"></div>\n        <span class=\"tip-text\">6-20 characte" +
                        "rs, minimum of 4 letters & 2 numbers</span>\n    </div>\n    </div>\n    <div class" +
                        "=\"formRow\">\n        <label class=\"form-label\" for=\"password2\">Confirm Password:<" +
                        "/label>\n        <div class=\"inputColumn\">\n            <input name=\"passConfirm\" " +
                        "value=\"\" id=\"PasswordConfirm\" class=\"text-box text-box-large\" TabIndex=\"8\" type=" +
                        "\"password\" onkeyup=\"Roblox.SignupFormValidator.checkPasswordConfirm();\"/>\n      " +
                        "  </div>\n        <div class=\"validation\">\n            <table id=\"passwordConfirm" +
                        "Error\" class=\"validator-container\">\n            <tr><td><div class=\"validator-to" +
                        "oltip-top\"></div><div class=\"validator-tooltip-main\">\n                <div id=\"P" +
                        "asswordConfirmMessage\"></div>\n            </div><div class=\"validator-tooltip-bo" +
                        "ttom\"></div></td></tr>\n            </table>\n            <div id=\"passwordConfirm" +
                        "Good\" class=\"validator-checkmark\"></div>\n        </div>\n    </div>\n\n    <div cla" +
                        "ss=\"clear\" style=\"font-size:0;\"></div>\n    \n     \n    <div class=\"CreateAccountW" +
                        "rapper\" style=\"text-align:center\" >\n        "));
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/SignupForm.ascx"
            this.@__BuildControl__bctrl_104();
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/SignupForm.ascx"
            @__parser.AddParsedSubObject(this._bctrl_104);
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/SignupForm.ascx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
    </div>

<script type=""text/javascript"">
    $(function () {
 
        //<sl:translate>
        Roblox.SignupFormValidator.Resources = {
        doesntMatch : ""Doesn't match"",
        requiredField : ""Required field"",
        tooLong : ""Too long"",
        tooShort : ""Too short"",
        containsInvalidCharacters : ""Contains invalid characters"",
        needsFourLetters : ""Needs 4 letters"",
        needsTwoNumbers : ""Needs 2 numbers"",
        noSpaces : ""No spaces allowed"",
        weakKey : ""Weak key combination."",
        invalidName : ""Can't be your character name"",
        alreadyTaken : ""Already taken"",
        cantBeUsed : ""Can't be used"",
        password : ""password""
        };
        //</sl:translate>
    });
</script>   "));
            
            #line default
            #line hidden
        }
        
        private global::System.Web.UI.WebControls.DropDownList @__BuildControl_lstMonths() {
            global::System.Web.UI.WebControls.DropDownList @__ctrl;
            
            #line 6 "/home/runner/workspace/RobloxWebSite/UserControls/SignupForm.ascx"
            @__ctrl = new global::System.Web.UI.WebControls.DropDownList();
            
            #line default
            #line hidden
            
            #line 6 "/home/runner/workspace/RobloxWebSite/UserControls/SignupForm.ascx"
            this.lstMonths = @__ctrl;
            
            #line default
            #line hidden
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            
            #line 6 "/home/runner/workspace/RobloxWebSite/UserControls/SignupForm.ascx"
            @__ctrl.ID = "lstMonths";
            
            #line default
            #line hidden
            
            #line 6 "/home/runner/workspace/RobloxWebSite/UserControls/SignupForm.ascx"
            @__ctrl.CssClass = "form-select";
            
            #line default
            #line hidden
            
            #line 6 "/home/runner/workspace/RobloxWebSite/UserControls/SignupForm.ascx"
            @__ctrl.ClientIDMode = ((System.Web.UI.ClientIDMode)(System.Web.UI.ClientIDMode.Static));
            
            #line default
            #line hidden
            
            #line 6 "/home/runner/workspace/RobloxWebSite/UserControls/SignupForm.ascx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("change", "Roblox.SignupFormValidator.checkBirthday()");
            
            #line default
            #line hidden
            
            #line 6 "/home/runner/workspace/RobloxWebSite/UserControls/SignupForm.ascx"
            @__ctrl.TabIndex = 1;
            
            #line default
            #line hidden
            
            #line 6 "/home/runner/workspace/RobloxWebSite/UserControls/SignupForm.ascx"
            this.@__BuildControl__bctrl_101(@__ctrl.Items);
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        private void @__BuildControl__bctrl_101(System.Web.UI.WebControls.ListItemCollection @__ctrl) {
        }
        
        private global::System.Web.UI.WebControls.DropDownList @__BuildControl_lstDays() {
            global::System.Web.UI.WebControls.DropDownList @__ctrl;
            
            #line 7 "/home/runner/workspace/RobloxWebSite/UserControls/SignupForm.ascx"
            @__ctrl = new global::System.Web.UI.WebControls.DropDownList();
            
            #line default
            #line hidden
            
            #line 7 "/home/runner/workspace/RobloxWebSite/UserControls/SignupForm.ascx"
            this.lstDays = @__ctrl;
            
            #line default
            #line hidden
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            
            #line 7 "/home/runner/workspace/RobloxWebSite/UserControls/SignupForm.ascx"
            @__ctrl.ID = "lstDays";
            
            #line default
            #line hidden
            
            #line 7 "/home/runner/workspace/RobloxWebSite/UserControls/SignupForm.ascx"
            @__ctrl.CssClass = "form-select";
            
            #line default
            #line hidden
            
            #line 7 "/home/runner/workspace/RobloxWebSite/UserControls/SignupForm.ascx"
            @__ctrl.ClientIDMode = ((System.Web.UI.ClientIDMode)(System.Web.UI.ClientIDMode.Static));
            
            #line default
            #line hidden
            
            #line 7 "/home/runner/workspace/RobloxWebSite/UserControls/SignupForm.ascx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("onchange", "Roblox.SignupFormValidator.checkBirthday()");
            
            #line default
            #line hidden
            
            #line 7 "/home/runner/workspace/RobloxWebSite/UserControls/SignupForm.ascx"
            @__ctrl.TabIndex = 2;
            
            #line default
            #line hidden
            
            #line 7 "/home/runner/workspace/RobloxWebSite/UserControls/SignupForm.ascx"
            this.@__BuildControl__bctrl_102(@__ctrl.Items);
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        private void @__BuildControl__bctrl_102(System.Web.UI.WebControls.ListItemCollection @__ctrl) {
        }
        
        private global::System.Web.UI.WebControls.DropDownList @__BuildControl_lstYears() {
            global::System.Web.UI.WebControls.DropDownList @__ctrl;
            
            #line 8 "/home/runner/workspace/RobloxWebSite/UserControls/SignupForm.ascx"
            @__ctrl = new global::System.Web.UI.WebControls.DropDownList();
            
            #line default
            #line hidden
            
            #line 8 "/home/runner/workspace/RobloxWebSite/UserControls/SignupForm.ascx"
            this.lstYears = @__ctrl;
            
            #line default
            #line hidden
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            
            #line 8 "/home/runner/workspace/RobloxWebSite/UserControls/SignupForm.ascx"
            @__ctrl.ID = "lstYears";
            
            #line default
            #line hidden
            
            #line 8 "/home/runner/workspace/RobloxWebSite/UserControls/SignupForm.ascx"
            @__ctrl.CssClass = "form-select";
            
            #line default
            #line hidden
            
            #line 8 "/home/runner/workspace/RobloxWebSite/UserControls/SignupForm.ascx"
            @__ctrl.ClientIDMode = ((System.Web.UI.ClientIDMode)(System.Web.UI.ClientIDMode.Static));
            
            #line default
            #line hidden
            
            #line 8 "/home/runner/workspace/RobloxWebSite/UserControls/SignupForm.ascx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("onchange", "Roblox.SignupFormValidator.checkBirthday(false)");
            
            #line default
            #line hidden
            
            #line 8 "/home/runner/workspace/RobloxWebSite/UserControls/SignupForm.ascx"
            @__ctrl.TabIndex = 3;
            
            #line default
            #line hidden
            
            #line 8 "/home/runner/workspace/RobloxWebSite/UserControls/SignupForm.ascx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("style", "margin: 0;");
            
            #line default
            #line hidden
            
            #line 8 "/home/runner/workspace/RobloxWebSite/UserControls/SignupForm.ascx"
            this.@__BuildControl__bctrl_103(@__ctrl.Items);
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        private void @__BuildControl__bctrl_103(System.Web.UI.WebControls.ListItemCollection @__ctrl) {
        }
        
        private global::System.Web.UI.WebControls.RadioButton @__BuildControl_MaleBtn() {
            global::System.Web.UI.WebControls.RadioButton @__ctrl;
            
            #line 31 "/home/runner/workspace/RobloxWebSite/UserControls/SignupForm.ascx"
            @__ctrl = new global::System.Web.UI.WebControls.RadioButton();
            
            #line default
            #line hidden
            
            #line 31 "/home/runner/workspace/RobloxWebSite/UserControls/SignupForm.ascx"
            this.MaleBtn = @__ctrl;
            
            #line default
            #line hidden
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            
            #line 31 "/home/runner/workspace/RobloxWebSite/UserControls/SignupForm.ascx"
            @__ctrl.ID = "MaleBtn";
            
            #line default
            #line hidden
            
            #line 31 "/home/runner/workspace/RobloxWebSite/UserControls/SignupForm.ascx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("onclick", "Roblox.SignupFormValidator.checkGender();");
            
            #line default
            #line hidden
            
            #line 31 "/home/runner/workspace/RobloxWebSite/UserControls/SignupForm.ascx"
            @__ctrl.ClientIDMode = ((System.Web.UI.ClientIDMode)(System.Web.UI.ClientIDMode.Static));
            
            #line default
            #line hidden
            
            #line 31 "/home/runner/workspace/RobloxWebSite/UserControls/SignupForm.ascx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("Value", "MaleBtn");
            
            #line default
            #line hidden
            
            #line 31 "/home/runner/workspace/RobloxWebSite/UserControls/SignupForm.ascx"
            @__ctrl.Text = "Male";
            
            #line default
            #line hidden
            
            #line 31 "/home/runner/workspace/RobloxWebSite/UserControls/SignupForm.ascx"
            @__ctrl.TabIndex = 4;
            
            #line default
            #line hidden
            
            #line 31 "/home/runner/workspace/RobloxWebSite/UserControls/SignupForm.ascx"
            @__ctrl.GroupName = "Gender";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        private global::System.Web.UI.WebControls.RadioButton @__BuildControl_FemaleBtn() {
            global::System.Web.UI.WebControls.RadioButton @__ctrl;
            
            #line 32 "/home/runner/workspace/RobloxWebSite/UserControls/SignupForm.ascx"
            @__ctrl = new global::System.Web.UI.WebControls.RadioButton();
            
            #line default
            #line hidden
            
            #line 32 "/home/runner/workspace/RobloxWebSite/UserControls/SignupForm.ascx"
            this.FemaleBtn = @__ctrl;
            
            #line default
            #line hidden
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            
            #line 32 "/home/runner/workspace/RobloxWebSite/UserControls/SignupForm.ascx"
            @__ctrl.ID = "FemaleBtn";
            
            #line default
            #line hidden
            
            #line 32 "/home/runner/workspace/RobloxWebSite/UserControls/SignupForm.ascx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("onclick", "Roblox.SignupFormValidator.checkGender();");
            
            #line default
            #line hidden
            
            #line 32 "/home/runner/workspace/RobloxWebSite/UserControls/SignupForm.ascx"
            @__ctrl.ClientIDMode = ((System.Web.UI.ClientIDMode)(System.Web.UI.ClientIDMode.Static));
            
            #line default
            #line hidden
            
            #line 32 "/home/runner/workspace/RobloxWebSite/UserControls/SignupForm.ascx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("Value", "FemaleBtn");
            
            #line default
            #line hidden
            
            #line 32 "/home/runner/workspace/RobloxWebSite/UserControls/SignupForm.ascx"
            @__ctrl.Text = "Female";
            
            #line default
            #line hidden
            
            #line 32 "/home/runner/workspace/RobloxWebSite/UserControls/SignupForm.ascx"
            @__ctrl.TabIndex = 5;
            
            #line default
            #line hidden
            
            #line 32 "/home/runner/workspace/RobloxWebSite/UserControls/SignupForm.ascx"
            @__ctrl.GroupName = "Gender";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        private global::System.Web.UI.WebControls.TextBox @__BuildControl_UserName() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            
            #line 51 "/home/runner/workspace/RobloxWebSite/UserControls/SignupForm.ascx"
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            
            #line default
            #line hidden
            
            #line 51 "/home/runner/workspace/RobloxWebSite/UserControls/SignupForm.ascx"
            this.UserName = @__ctrl;
            
            #line default
            #line hidden
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            
            #line 51 "/home/runner/workspace/RobloxWebSite/UserControls/SignupForm.ascx"
            @__ctrl.ID = "UserName";
            
            #line default
            #line hidden
            
            #line 51 "/home/runner/workspace/RobloxWebSite/UserControls/SignupForm.ascx"
            @__ctrl.ClientIDMode = ((System.Web.UI.ClientIDMode)(System.Web.UI.ClientIDMode.Static));
            
            #line default
            #line hidden
            
            #line 51 "/home/runner/workspace/RobloxWebSite/UserControls/SignupForm.ascx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("onblur", "Roblox.SignupFormValidator.checkUsername()");
            
            #line default
            #line hidden
            
            #line 51 "/home/runner/workspace/RobloxWebSite/UserControls/SignupForm.ascx"
            @__ctrl.TabIndex = 6;
            
            #line default
            #line hidden
            
            #line 51 "/home/runner/workspace/RobloxWebSite/UserControls/SignupForm.ascx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "text-box text-box-large");
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        private global::System.Web.UI.WebControls.LinkButton @__BuildControl__bctrl_104() {
            global::System.Web.UI.WebControls.LinkButton @__ctrl;
            
            #line 104 "/home/runner/workspace/RobloxWebSite/UserControls/SignupForm.ascx"
            @__ctrl = new global::System.Web.UI.WebControls.LinkButton();
            
            #line default
            #line hidden
            
            #line 104 "/home/runner/workspace/RobloxWebSite/UserControls/SignupForm.ascx"
            this._bctrl_104 = @__ctrl;
            
            #line default
            #line hidden
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            
            #line 104 "/home/runner/workspace/RobloxWebSite/UserControls/SignupForm.ascx"
            @__ctrl.OnClientClick = "return Roblox.SignupFormValidator.ValidateForm();";
            
            #line default
            #line hidden
            
            #line 104 "/home/runner/workspace/RobloxWebSite/UserControls/SignupForm.ascx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("data-se", "SignUpButton");
            
            #line default
            #line hidden
            
            #line 104 "/home/runner/workspace/RobloxWebSite/UserControls/SignupForm.ascx"
            @__ctrl.Text = "Sign Up";
            
            #line default
            #line hidden
            
            #line 104 "/home/runner/workspace/RobloxWebSite/UserControls/SignupForm.ascx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "btn-large btn-primary");
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        protected override void FrameworkInitialize() {
            base.FrameworkInitialize();
            this.SetStringResourcePointer(global::ASP.usercontrols_signupform_ascx.@__stringResource, 0);
            this.@__BuildControlTree(this);
        }
    }
}
