#pragma checksum "/home/runner/workspace/RobloxWebSite/UserControls/UserContent/SetsPane.ascx" "{406ea660-64cf-4c82-b6f0-42d48172a799}" "5DDCEBD87FE3809E545A7E840B761B29"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
    using System;
    using System.Collections;
    using System.Collections.Specialized;
    using System.Configuration;
    using System.Text;
    using System.Text.RegularExpressions;
    using System.Web;
    using System.Web.Caching;
    using System.Web.SessionState;
    using System.Web.Security;
    using System.Web.Profile;
    using System.Web.UI;
    using System.Web.UI.WebControls;
    using System.Web.UI.HtmlControls;
    using Roblox.Website;
    using Roblox.Web.Code;
    
    
    public class usercontrols_usercontent_setspane_ascx : global::Roblox.Website.UserControls.UserContent.SetsPane {
        
        private static bool @__initialized = false;
        
        private static object @__stringResource = null;
        
        private static int @__autoHandlers;
        
        public usercontrols_usercontent_setspane_ascx() {
            ((global::Roblox.Website.UserControls.UserContent.SetsPane)(this)).AppRelativeVirtualPath = "~/UserControls/UserContent/SetsPane.ascx";
            if ((global::ASP.usercontrols_usercontent_setspane_ascx.@__initialized == false)) {
                global::ASP.usercontrols_usercontent_setspane_ascx.@__initialized = true;
            }
        }
        
        [System.Obsolete()]
        protected override int AutoHandlers {
            get {
                return ASP.usercontrols_usercontent_setspane_ascx.@__autoHandlers;
            }
            set {
                ASP.usercontrols_usercontent_setspane_ascx.@__autoHandlers = value;
            }
        }
        
        protected System.Web.HttpApplication ApplicationInstance {
            get {
                return ((System.Web.HttpApplication)(this.Context.ApplicationInstance));
            }
        }
        
        protected System.Web.Profile.DefaultProfile Profile {
            get {
                return ((System.Web.Profile.DefaultProfile)(this.Context.Profile));
            }
        }
        
        private void @__RenderTree(System.Web.UI.HtmlTextWriter @__output, System.Web.UI.Control parameterContainer) {
            @__output.Write("<div style=\"padding-bottom: 20px\">\n    <div>\n        <h2 class=\"title\" style=\"dis" +
                    "play:block;float: left;\">\n            ");
            
            #line 5 "/home/runner/workspace/RobloxWebSite/UserControls/UserContent/SetsPane.ascx"
            @__output.Write(String.Format(Resources.GetString("HeadingSets"), "<span class=\"notranslate\">" + UserProfile.ProfileDisplayName + "</span>") );
            
            #line default
            #line hidden
            @__output.Write("\n        </h2>\n        <a data-js-my-button href class=\"btn-small btn-neutral\" id" +
                    "=\"ToggleBetweenOwnedSubscribedSets\" style=\"float: right; margin-right: 20px; mar" +
                    "gin-top: 25px\" onclick=\"Roblox.SetsPaneObject.toggleBetweenSetsOwnedSubscribed()" +
                    ";return false;\" >View Subscribed<span class=\"btn-text\" id=\"SetsToggleSpan\">View " +
                    "Subscribed</span></a>\n        <div class=\"clear\"></div>\n    </div>\n    <div id=\"" +
                    "OwnedSetsContainerDiv\" style=\"padding-bottom:0;\">\n        <div id=\"SetsItemConta" +
                    "iner\" style=\"margin-bottom: 30px; margin-left: 15px\"></div>\n        <div style=\"" +
                    "clear:both;\"></div>\n        <div class=\"SetsPager_Container\" style=\"position: re" +
                    "lative\">\n            <div id=\"SetsPagerContainer\"></div>\n        </div>\n    </di" +
                    "v>\n    <div id=\"SubscribedSetsContainerDiv\" style=\"display:none; padding-bottom:" +
                    " 0px\">\n        <div id=\"SubscribedSetsItemContainer\" style=\"margin-bottom: 30px;" +
                    " margin-left: 15px\"></div>\n        <div style=\"clear:both;\"></div>\n        <div " +
                    "class=\"SetsPager_Container\" style=\"position: relative\">\n            <div id=\"Sub" +
                    "scribedSetsPagerContainer\"></div>\n        </div>\n    </div>\n    \n    <div id=\"Se" +
                    "tsPaneItemTemplate\" style=\"display:none;\">\n        <div class=\"AssetThumbnail\">\n" +
                    "            <img class=\"$ImageAssetID\"></img>\n        </div>\n        <div class=" +
                    "\"AssetDetails\">\n            <div class=\"AssetName notranslate\" >\n               " +
                    " <a href=\"/My/Sets.aspx?id=$ID\">$Name</a>\n            </div>\n            <div cl" +
                    "ass=\"AssetCreator\">\n                <span class=\"Label\">Creator:&nbsp;</span>\n  " +
                    "              <span class=\"Detail\">\n                    <a href=\"/User.aspx?id=$" +
                    "CreatorUserID\" class=\"notranslate\">$CreatorName</a>\n                </span>\n    " +
                    "        </div>\n        </div>\n    </div>\n</div>\n\n<script type=\"text/javascript\">" +
                    "\n    if (typeof Roblox === \"undefined\") {\n        Roblox = {};\n    }\n\n    $(func" +
                    "tion () {\n        Roblox.SetsPaneObject = Roblox.SetsPane(\'");
            
            #line 43 "/home/runner/workspace/RobloxWebSite/UserControls/UserContent/SetsPane.ascx"
            @__output.Write(Roblox.Common.Web.ApplicationURL );
            
            #line default
            #line hidden
            @__output.Write("/\', ");
            
            #line 43 "/home/runner/workspace/RobloxWebSite/UserControls/UserContent/SetsPane.ascx"
            @__output.Write(UserProfile.ProfileUserId );
            
            #line default
            #line hidden
            @__output.Write(@");

        var options = { Paging_PageNumbers_AreLinks: false };
        Roblox.OwnedSetsJSDataPager = new DataPager(0, 9, 'SetsItemContainer', 'SetsPagerContainer',
            Roblox.SetsPaneObject.getSetsPaged, Roblox.SetsPaneObject.ownedItemFormatter, Roblox.SetsPaneObject.getSetAssetImageThumbnail, options
        );
        Roblox.SubscribedSetsJSDataPager = new DataPager(0, 9, 'SubscribedSetsItemContainer', 'SubscribedSetsPagerContainer',
            Roblox.SetsPaneObject.getSubscribedSetsPaged, Roblox.SetsPaneObject.subscribedItemFormatter, Roblox.SetsPaneObject.getSetAssetImageThumbnail, options
        );
    });
</script>
");
        }
        
        private void @__BuildControlTree(usercontrols_usercontent_setspane_ascx @__ctrl) {
            @__ctrl.SetRenderMethodDelegate(new System.Web.UI.RenderMethod(this.@__RenderTree));
        }
        
        protected override void FrameworkInitialize() {
            base.FrameworkInitialize();
            this.SetStringResourcePointer(global::ASP.usercontrols_usercontent_setspane_ascx.@__stringResource, 0);
            this.@__BuildControlTree(this);
        }
    }
}
