#pragma checksum "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/AlertsAndOptionsAnonymous.ascx" "{406ea660-64cf-4c82-b6f0-42d48172a799}" "E448B4908624A17A335A912023841826"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
    using System;
    using System.Collections;
    using System.Collections.Specialized;
    using System.Configuration;
    using System.Text;
    using System.Text.RegularExpressions;
    using System.Web;
    using System.Web.Caching;
    using System.Web.SessionState;
    using System.Web.Security;
    using System.Web.Profile;
    using System.Web.UI;
    using System.Web.UI.WebControls;
    using System.Web.UI.HtmlControls;
    using Roblox.Website;
    using Roblox.Web.Code;
    
    
    public class usercontrols_navigation_alertsandoptionsanonymous_ascx : global::Roblox.Website.UserControls.Navigation.AlertsAndOptionsAnonymous {
        
        private static bool @__initialized = false;
        
        private static object @__stringResource = null;
        
        private static int @__autoHandlers;
        
        public usercontrols_navigation_alertsandoptionsanonymous_ascx() {
            ((global::Roblox.Website.UserControls.Navigation.AlertsAndOptionsAnonymous)(this)).AppRelativeVirtualPath = "~/UserControls/Navigation/AlertsAndOptionsAnonymous.ascx";
            if ((global::ASP.usercontrols_navigation_alertsandoptionsanonymous_ascx.@__initialized == false)) {
                global::ASP.usercontrols_navigation_alertsandoptionsanonymous_ascx.@__initialized = true;
            }
        }
        
        [System.Obsolete()]
        protected override int AutoHandlers {
            get {
                return ASP.usercontrols_navigation_alertsandoptionsanonymous_ascx.@__autoHandlers;
            }
            set {
                ASP.usercontrols_navigation_alertsandoptionsanonymous_ascx.@__autoHandlers = value;
            }
        }
        
        protected System.Web.HttpApplication ApplicationInstance {
            get {
                return ((System.Web.HttpApplication)(this.Context.ApplicationInstance));
            }
        }
        
        protected System.Web.Profile.DefaultProfile Profile {
            get {
                return ((System.Web.Profile.DefaultProfile)(this.Context.Profile));
            }
        }
        
        private void @__BuildControlTree(usercontrols_navigation_alertsandoptionsanonymous_ascx @__ctrl) {
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/AlertsAndOptionsAnonymous.ascx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("<div id=\"SiteWideHeaderLogin\">\n    <div id=\"HeaderLoginButton\" class=\"iFrameLogin" +
                        "SignUp\">\n\t\t"));
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/AlertsAndOptionsAnonymous.ascx"
            this.@__BuildControl_HeaderSignUp();
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/AlertsAndOptionsAnonymous.ascx"
            @__parser.AddParsedSubObject(this.HeaderSignUp);
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/AlertsAndOptionsAnonymous.ascx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\n\t\t"));
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/AlertsAndOptionsAnonymous.ascx"
            this.@__BuildControl_HeaderOr();
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/AlertsAndOptionsAnonymous.ascx"
            @__parser.AddParsedSubObject(this.HeaderOr);
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/AlertsAndOptionsAnonymous.ascx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\n        <span id=\"loginSpan\">\n\t\t\t<a id=\"headerLogin\" ></a>\n        </span>\n\t\t"));
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/AlertsAndOptionsAnonymous.ascx"
            this.@__BuildControl_iFrameLogin();
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/AlertsAndOptionsAnonymous.ascx"
            @__parser.AddParsedSubObject(this.iFrameLogin);
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/AlertsAndOptionsAnonymous.ascx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\n\t</div>\n</div>"));
            
            #line default
            #line hidden
        }
        
        private global::System.Web.UI.WebControls.HyperLink @__BuildControl_HeaderSignUp() {
            global::System.Web.UI.WebControls.HyperLink @__ctrl;
            
            #line 4 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/AlertsAndOptionsAnonymous.ascx"
            @__ctrl = new global::System.Web.UI.WebControls.HyperLink();
            
            #line default
            #line hidden
            
            #line 4 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/AlertsAndOptionsAnonymous.ascx"
            this.HeaderSignUp = @__ctrl;
            
            #line default
            #line hidden
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            
            #line 4 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/AlertsAndOptionsAnonymous.ascx"
            @__ctrl.ID = "HeaderSignUp";
            
            #line default
            #line hidden
            
            #line 4 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/AlertsAndOptionsAnonymous.ascx"
            @__ctrl.Text = global::System.Convert.ToString(global::System.Convert.ToString(this.GetLocalResourceObject("Header.SignUp"), System.Globalization.CultureInfo.CurrentCulture), System.Globalization.CultureInfo.CurrentCulture);
            
            #line default
            #line hidden
            
            #line 4 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/AlertsAndOptionsAnonymous.ascx"
            @__ctrl.ClientIDMode = ((System.Web.UI.ClientIDMode)(System.Web.UI.ClientIDMode.Static));
            
            #line default
            #line hidden
            
            #line 4 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/AlertsAndOptionsAnonymous.ascx"
            @__ctrl.NavigateUrl = "/Login/NewAge.aspx";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        private global::System.Web.UI.WebControls.Label @__BuildControl_HeaderOr() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            
            #line 5 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/AlertsAndOptionsAnonymous.ascx"
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            
            #line default
            #line hidden
            
            #line 5 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/AlertsAndOptionsAnonymous.ascx"
            this.HeaderOr = @__ctrl;
            
            #line default
            #line hidden
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            
            #line 5 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/AlertsAndOptionsAnonymous.ascx"
            @__ctrl.ID = "HeaderOr";
            
            #line default
            #line hidden
            
            #line 5 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/AlertsAndOptionsAnonymous.ascx"
            @__ctrl.Text = global::System.Convert.ToString(global::System.Convert.ToString(this.GetLocalResourceObject("Header.Or"), System.Globalization.CultureInfo.CurrentCulture), System.Globalization.CultureInfo.CurrentCulture);
            
            #line default
            #line hidden
            
            #line 5 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/AlertsAndOptionsAnonymous.ascx"
            @__ctrl.ClientIDMode = ((System.Web.UI.ClientIDMode)(System.Web.UI.ClientIDMode.Static));
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        private void @__Render_iFrameLogin(System.Web.UI.HtmlTextWriter @__output, System.Web.UI.Control parameterContainer) {
            @__output.Write("\n\t\t\t<iframe class=\"loginFrame\" src=\"/Login/iFrameLogin.aspx?loginRedirect=True&pa" +
                    "rentUrl=");
            
            #line 10 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/AlertsAndOptionsAnonymous.ascx"
            @__output.Write(HttpUtility.UrlEncode(HttpContext.Current.Request.Url.AbsoluteUri));
            
            #line default
            #line hidden
            @__output.Write("\" scrolling=\"no\" frameborder=\"0\"></iframe>\n\t\t");
        }
        
        private global::System.Web.UI.HtmlControls.HtmlGenericControl @__BuildControl_iFrameLogin() {
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl;
            
            #line 9 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/AlertsAndOptionsAnonymous.ascx"
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlGenericControl("div");
            
            #line default
            #line hidden
            
            #line 9 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/AlertsAndOptionsAnonymous.ascx"
            this.iFrameLogin = @__ctrl;
            
            #line default
            #line hidden
            
            #line 9 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/AlertsAndOptionsAnonymous.ascx"
            @__ctrl.ID = "iFrameLogin";
            
            #line default
            #line hidden
            
            #line 9 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/AlertsAndOptionsAnonymous.ascx"
            @__ctrl.ClientIDMode = ((System.Web.UI.ClientIDMode)(System.Web.UI.ClientIDMode.Static));
            
            #line default
            #line hidden
            
            #line 9 "/home/runner/workspace/RobloxWebSite/UserControls/Navigation/AlertsAndOptionsAnonymous.ascx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("style", "display:none");
            
            #line default
            #line hidden
            @__ctrl.SetRenderMethodDelegate(new System.Web.UI.RenderMethod(this.@__Render_iFrameLogin));
            return @__ctrl;
        }
        
        protected override void FrameworkInitialize() {
            base.FrameworkInitialize();
            this.SetStringResourcePointer(global::ASP.usercontrols_navigation_alertsandoptionsanonymous_ascx.@__stringResource, 0);
            this.@__BuildControlTree(this);
        }
    }
}
