#pragma checksum "/home/runner/workspace/RobloxWebSite/UserControls/SelectGenderPane.ascx" "{406ea660-64cf-4c82-b6f0-42d48172a799}" "B083ADEAD32FBB07B152AD326B761D3E"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
    using System;
    using System.Collections;
    using System.Collections.Specialized;
    using System.Configuration;
    using System.Text;
    using System.Text.RegularExpressions;
    using System.Web;
    using System.Web.Caching;
    using System.Web.SessionState;
    using System.Web.Security;
    using System.Web.Profile;
    using System.Web.UI;
    using System.Web.UI.WebControls;
    using System.Web.UI.HtmlControls;
    using Roblox.Website;
    using Roblox.Web.Code;
    
    
    public class usercontrols_selectgenderpane_ascx : global::Roblox.Website.UserControls.SelectGenderPane {
        
        private static bool @__initialized = false;
        
        private static object @__stringResource = null;
        
        private static int @__autoHandlers;
        
        public usercontrols_selectgenderpane_ascx() {
            ((global::Roblox.Website.UserControls.SelectGenderPane)(this)).AppRelativeVirtualPath = "~/UserControls/SelectGenderPane.ascx";
            if ((global::ASP.usercontrols_selectgenderpane_ascx.@__initialized == false)) {
                global::ASP.usercontrols_selectgenderpane_ascx.@__initialized = true;
            }
        }
        
        [System.Obsolete()]
        protected override int AutoHandlers {
            get {
                return ASP.usercontrols_selectgenderpane_ascx.@__autoHandlers;
            }
            set {
                ASP.usercontrols_selectgenderpane_ascx.@__autoHandlers = value;
            }
        }
        
        protected System.Web.HttpApplication ApplicationInstance {
            get {
                return ((System.Web.HttpApplication)(this.Context.ApplicationInstance));
            }
        }
        
        protected System.Web.Profile.DefaultProfile Profile {
            get {
                return ((System.Web.Profile.DefaultProfile)(this.Context.Profile));
            }
        }
        
        private void @__BuildControlTree(usercontrols_selectgenderpane_ascx @__ctrl) {
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/SelectGenderPane.ascx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("<div style=\"text-align:left\">Are you a boy or a girl?</div>\n<div style=\"text-alig" +
                        "n:center;position:relative;height:250px\">\n\t<div style=\"position:absolute;left:50" +
                        "%;margin-left:-175px\">\n\t\t<label for=\"MaleBtn\">"));
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/SelectGenderPane.ascx"
            this.@__BuildControl_BoyThumbnail();
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/SelectGenderPane.ascx"
            @__parser.AddParsedSubObject(this.BoyThumbnail);
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/SelectGenderPane.ascx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("<br /></label>\n\t\t"));
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/SelectGenderPane.ascx"
            this.@__BuildControl_MaleBtn();
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/SelectGenderPane.ascx"
            @__parser.AddParsedSubObject(this.MaleBtn);
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/SelectGenderPane.ascx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("<label for=\"MaleBtn\">Boy</label>\n\t</div>\n\t<div style=\"position:absolute;left:50%;" +
                        "margin-left:25px\">\n\t\t<label for=\"FemaleBtn\">"));
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/SelectGenderPane.ascx"
            this.@__BuildControl_GirlThumbnail();
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/SelectGenderPane.ascx"
            @__parser.AddParsedSubObject(this.GirlThumbnail);
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/SelectGenderPane.ascx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("<br /></label>\n\t\t"));
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/SelectGenderPane.ascx"
            this.@__BuildControl_FemaleBtn();
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/SelectGenderPane.ascx"
            @__parser.AddParsedSubObject(this.FemaleBtn);
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/SelectGenderPane.ascx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("<label for=\"FemaleBtn\">Girl</label>\n\t</div>\n</div>"));
            
            #line default
            #line hidden
        }
        
        private global::System.Web.UI.HtmlControls.HtmlImage @__BuildControl_BoyThumbnail() {
            global::System.Web.UI.HtmlControls.HtmlImage @__ctrl;
            
            #line 6 "/home/runner/workspace/RobloxWebSite/UserControls/SelectGenderPane.ascx"
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlImage();
            
            #line default
            #line hidden
            
            #line 6 "/home/runner/workspace/RobloxWebSite/UserControls/SelectGenderPane.ascx"
            this.BoyThumbnail = @__ctrl;
            
            #line default
            #line hidden
            
            #line 6 "/home/runner/workspace/RobloxWebSite/UserControls/SelectGenderPane.ascx"
            @__ctrl.ID = "BoyThumbnail";
            
            #line default
            #line hidden
            
            #line 6 "/home/runner/workspace/RobloxWebSite/UserControls/SelectGenderPane.ascx"
            @__ctrl.Src = "/images/Accounts/boy.png";
            
            #line default
            #line hidden
            
            #line 6 "/home/runner/workspace/RobloxWebSite/UserControls/SelectGenderPane.ascx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("style", "cursor:pointer");
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        private global::System.Web.UI.WebControls.RadioButton @__BuildControl_MaleBtn() {
            global::System.Web.UI.WebControls.RadioButton @__ctrl;
            
            #line 7 "/home/runner/workspace/RobloxWebSite/UserControls/SelectGenderPane.ascx"
            @__ctrl = new global::System.Web.UI.WebControls.RadioButton();
            
            #line default
            #line hidden
            
            #line 7 "/home/runner/workspace/RobloxWebSite/UserControls/SelectGenderPane.ascx"
            this.MaleBtn = @__ctrl;
            
            #line default
            #line hidden
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            
            #line 7 "/home/runner/workspace/RobloxWebSite/UserControls/SelectGenderPane.ascx"
            @__ctrl.ID = "MaleBtn";
            
            #line default
            #line hidden
            
            #line 7 "/home/runner/workspace/RobloxWebSite/UserControls/SelectGenderPane.ascx"
            @__ctrl.GroupName = "Gender";
            
            #line default
            #line hidden
            
            #line 7 "/home/runner/workspace/RobloxWebSite/UserControls/SelectGenderPane.ascx"
            @__ctrl.ClientIDMode = ((System.Web.UI.ClientIDMode)(System.Web.UI.ClientIDMode.Static));
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        private global::System.Web.UI.HtmlControls.HtmlImage @__BuildControl_GirlThumbnail() {
            global::System.Web.UI.HtmlControls.HtmlImage @__ctrl;
            
            #line 10 "/home/runner/workspace/RobloxWebSite/UserControls/SelectGenderPane.ascx"
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlImage();
            
            #line default
            #line hidden
            
            #line 10 "/home/runner/workspace/RobloxWebSite/UserControls/SelectGenderPane.ascx"
            this.GirlThumbnail = @__ctrl;
            
            #line default
            #line hidden
            
            #line 10 "/home/runner/workspace/RobloxWebSite/UserControls/SelectGenderPane.ascx"
            @__ctrl.ID = "GirlThumbnail";
            
            #line default
            #line hidden
            
            #line 10 "/home/runner/workspace/RobloxWebSite/UserControls/SelectGenderPane.ascx"
            @__ctrl.Src = "/images/Accounts/girl.png";
            
            #line default
            #line hidden
            
            #line 10 "/home/runner/workspace/RobloxWebSite/UserControls/SelectGenderPane.ascx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("style", "cursor:pointer");
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        private global::System.Web.UI.WebControls.RadioButton @__BuildControl_FemaleBtn() {
            global::System.Web.UI.WebControls.RadioButton @__ctrl;
            
            #line 11 "/home/runner/workspace/RobloxWebSite/UserControls/SelectGenderPane.ascx"
            @__ctrl = new global::System.Web.UI.WebControls.RadioButton();
            
            #line default
            #line hidden
            
            #line 11 "/home/runner/workspace/RobloxWebSite/UserControls/SelectGenderPane.ascx"
            this.FemaleBtn = @__ctrl;
            
            #line default
            #line hidden
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            
            #line 11 "/home/runner/workspace/RobloxWebSite/UserControls/SelectGenderPane.ascx"
            @__ctrl.ID = "FemaleBtn";
            
            #line default
            #line hidden
            
            #line 11 "/home/runner/workspace/RobloxWebSite/UserControls/SelectGenderPane.ascx"
            @__ctrl.GroupName = "Gender";
            
            #line default
            #line hidden
            
            #line 11 "/home/runner/workspace/RobloxWebSite/UserControls/SelectGenderPane.ascx"
            @__ctrl.ClientIDMode = ((System.Web.UI.ClientIDMode)(System.Web.UI.ClientIDMode.Static));
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        protected override void FrameworkInitialize() {
            base.FrameworkInitialize();
            this.SetStringResourcePointer(global::ASP.usercontrols_selectgenderpane_ascx.@__stringResource, 0);
            this.@__BuildControlTree(this);
        }
    }
}
