#pragma checksum "/home/runner/workspace/RobloxWebSite/UserControls/UserContent/HeaderPane.ascx" "{406ea660-64cf-4c82-b6f0-42d48172a799}" "AF83106F592DE1F70D533AC81D206CDC"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
    using System;
    using System.Collections;
    using System.Collections.Specialized;
    using System.Configuration;
    using System.Text;
    using System.Text.RegularExpressions;
    using System.Web;
    using System.Web.Caching;
    using System.Web.SessionState;
    using System.Web.Security;
    using System.Web.Profile;
    using System.Web.UI;
    using System.Web.UI.WebControls;
    using System.Web.UI.HtmlControls;
    using Roblox.Website;
    using Roblox.Web.Code;
    
    
    public class usercontrols_usercontent_headerpane_ascx : global::Roblox.Website.UserControls.UserContent.HeaderPane {
        
        private static bool @__initialized = false;
        
        private static object @__stringResource = null;
        
        private static int @__autoHandlers;
        
        
        #line 21 "/home/runner/workspace/RobloxWebSite/UserControls/UserContent/HeaderPane.ascx"
        protected global::System.Web.UI.DataBoundLiteralControl _bctrl_4;
        
        #line default
        #line hidden
        
        public usercontrols_usercontent_headerpane_ascx() {
            ((global::Roblox.Website.UserControls.UserContent.HeaderPane)(this)).AppRelativeVirtualPath = "~/UserControls/UserContent/HeaderPane.ascx";
            if ((global::ASP.usercontrols_usercontent_headerpane_ascx.@__initialized == false)) {
                global::ASP.usercontrols_usercontent_headerpane_ascx.@__initialized = true;
            }
        }
        
        [System.Obsolete()]
        protected override int AutoHandlers {
            get {
                return ASP.usercontrols_usercontent_headerpane_ascx.@__autoHandlers;
            }
            set {
                ASP.usercontrols_usercontent_headerpane_ascx.@__autoHandlers = value;
            }
        }
        
        protected System.Web.HttpApplication ApplicationInstance {
            get {
                return ((System.Web.HttpApplication)(this.Context.ApplicationInstance));
            }
        }
        
        protected System.Web.Profile.DefaultProfile Profile {
            get {
                return ((System.Web.Profile.DefaultProfile)(this.Context.Profile));
            }
        }
        
        private void @__BuildControlTree(usercontrols_usercontent_headerpane_ascx @__ctrl) {
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/UserContent/HeaderPane.ascx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("<div style=\"width:900px;height:30px;clear:both; display:none;\">\n    "));
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/UserContent/HeaderPane.ascx"
            this.@__BuildControl_nameRegion();
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/UserContent/HeaderPane.ascx"
            @__parser.AddParsedSubObject(this.nameRegion);
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/UserContent/HeaderPane.ascx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\n</div>\n\n\n"));
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/UserContent/HeaderPane.ascx"
            this.@__BuildControl_statusBox();
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/UserContent/HeaderPane.ascx"
            @__parser.AddParsedSubObject(this.statusBox);
            
            #line default
            #line hidden
        }
        
        private global::System.Web.UI.WebControls.Label @__BuildControl_nameRegion() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            
            #line 4 "/home/runner/workspace/RobloxWebSite/UserControls/UserContent/HeaderPane.ascx"
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            
            #line default
            #line hidden
            
            #line 4 "/home/runner/workspace/RobloxWebSite/UserControls/UserContent/HeaderPane.ascx"
            this.nameRegion = @__ctrl;
            
            #line default
            #line hidden
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            
            #line 4 "/home/runner/workspace/RobloxWebSite/UserControls/UserContent/HeaderPane.ascx"
            @__ctrl.ID = "nameRegion";
            
            #line default
            #line hidden
            
            #line 4 "/home/runner/workspace/RobloxWebSite/UserControls/UserContent/HeaderPane.ascx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("CssStyle", "font-size:20px; font-weight:bold;");
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        private global::System.Web.UI.HtmlControls.HtmlGenericControl @__BuildControl_statusBox() {
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl;
            
            #line 8 "/home/runner/workspace/RobloxWebSite/UserControls/UserContent/HeaderPane.ascx"
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlGenericControl("div");
            
            #line default
            #line hidden
            
            #line 8 "/home/runner/workspace/RobloxWebSite/UserControls/UserContent/HeaderPane.ascx"
            this.statusBox = @__ctrl;
            
            #line default
            #line hidden
            
            #line 8 "/home/runner/workspace/RobloxWebSite/UserControls/UserContent/HeaderPane.ascx"
            @__ctrl.ID = "statusBox";
            
            #line default
            #line hidden
            
            #line 8 "/home/runner/workspace/RobloxWebSite/UserControls/UserContent/HeaderPane.ascx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "blank-box");
            
            #line default
            #line hidden
            
            #line 8 "/home/runner/workspace/RobloxWebSite/UserControls/UserContent/HeaderPane.ascx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("style", "width:951px; padding: 8px;word-wrap: break-word;display:block;");
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 8 "/home/runner/workspace/RobloxWebSite/UserControls/UserContent/HeaderPane.ascx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\n    <span style=\"font-size:12px;color: #888;word-wrap: normal;\">\n    Right now I" +
                        "\'m: \n    </span> &nbsp;&nbsp;\n        \n    "));
            
            #line default
            #line hidden
            
            #line 8 "/home/runner/workspace/RobloxWebSite/UserControls/UserContent/HeaderPane.ascx"
            this.@__BuildControl_statusRegion();
            
            #line default
            #line hidden
            
            #line 8 "/home/runner/workspace/RobloxWebSite/UserControls/UserContent/HeaderPane.ascx"
            @__parser.AddParsedSubObject(this.statusRegion);
            
            #line default
            #line hidden
            
            #line 8 "/home/runner/workspace/RobloxWebSite/UserControls/UserContent/HeaderPane.ascx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("&nbsp;&nbsp;\n    "));
            
            #line default
            #line hidden
            
            #line 8 "/home/runner/workspace/RobloxWebSite/UserControls/UserContent/HeaderPane.ascx"
            this.@__BuildControl_ReportAbuse();
            
            #line default
            #line hidden
            
            #line 8 "/home/runner/workspace/RobloxWebSite/UserControls/UserContent/HeaderPane.ascx"
            @__parser.AddParsedSubObject(this.ReportAbuse);
            
            #line default
            #line hidden
            
            #line 8 "/home/runner/workspace/RobloxWebSite/UserControls/UserContent/HeaderPane.ascx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\n    "));
            
            #line default
            #line hidden
            
            #line 8 "/home/runner/workspace/RobloxWebSite/UserControls/UserContent/HeaderPane.ascx"
            this.@__BuildControl_updateStatusLink();
            
            #line default
            #line hidden
            
            #line 8 "/home/runner/workspace/RobloxWebSite/UserControls/UserContent/HeaderPane.ascx"
            @__parser.AddParsedSubObject(this.updateStatusLink);
            
            #line default
            #line hidden
            
            #line 8 "/home/runner/workspace/RobloxWebSite/UserControls/UserContent/HeaderPane.ascx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\n    <div id=\"updateStatusBox\" style=\"display:none;\">\n        <input type=\"text\" " +
                        "style=\"visibility:hidden;position:absolute\">\n        <span style=\"position:relat" +
                        "ive\">\n            "));
            
            #line default
            #line hidden
            
            #line 8 "/home/runner/workspace/RobloxWebSite/UserControls/UserContent/HeaderPane.ascx"
            this.@__BuildControl_txtStatusMessage();
            
            #line default
            #line hidden
            
            #line 8 "/home/runner/workspace/RobloxWebSite/UserControls/UserContent/HeaderPane.ascx"
            @__parser.AddParsedSubObject(this.txtStatusMessage);
            
            #line default
            #line hidden
            
            #line 8 "/home/runner/workspace/RobloxWebSite/UserControls/UserContent/HeaderPane.ascx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("&nbsp;&nbsp;\n        </span>\n        "));
            
            #line default
            #line hidden
            
            #line 8 "/home/runner/workspace/RobloxWebSite/UserControls/UserContent/HeaderPane.ascx"
            this.@__BuildControl_btnUpdateStatus();
            
            #line default
            #line hidden
            
            #line 8 "/home/runner/workspace/RobloxWebSite/UserControls/UserContent/HeaderPane.ascx"
            @__parser.AddParsedSubObject(this.btnUpdateStatus);
            
            #line default
            #line hidden
            
            #line 8 "/home/runner/workspace/RobloxWebSite/UserControls/UserContent/HeaderPane.ascx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("&nbsp<input type=\"button\" value=\"Cancel\" onclick=\"document.getElementById(\'update" +
                        "StatusBox\').style.display=\'none\';document.getElementById(\'"));
            
            #line default
            #line hidden
            
            #line 8 "/home/runner/workspace/RobloxWebSite/UserControls/UserContent/HeaderPane.ascx"
            this.@__BuildControl__bctrl_4();
            
            #line default
            #line hidden
            
            #line 8 "/home/runner/workspace/RobloxWebSite/UserControls/UserContent/HeaderPane.ascx"
            @__parser.AddParsedSubObject(this._bctrl_4);
            
            #line default
            #line hidden
            
            #line 8 "/home/runner/workspace/RobloxWebSite/UserControls/UserContent/HeaderPane.ascx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\').style.display=\'inline\';\" /><br />\n    </div>\n"));
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        private global::System.Web.UI.WebControls.Label @__BuildControl_statusRegion() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            
            #line 13 "/home/runner/workspace/RobloxWebSite/UserControls/UserContent/HeaderPane.ascx"
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            
            #line default
            #line hidden
            
            #line 13 "/home/runner/workspace/RobloxWebSite/UserControls/UserContent/HeaderPane.ascx"
            this.statusRegion = @__ctrl;
            
            #line default
            #line hidden
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            
            #line 13 "/home/runner/workspace/RobloxWebSite/UserControls/UserContent/HeaderPane.ascx"
            @__ctrl.ID = "statusRegion";
            
            #line default
            #line hidden
            
            #line 13 "/home/runner/workspace/RobloxWebSite/UserControls/UserContent/HeaderPane.ascx"
            @__ctrl.Font.Italic = true;
            
            #line default
            #line hidden
            
            #line 13 "/home/runner/workspace/RobloxWebSite/UserControls/UserContent/HeaderPane.ascx"
            @__ctrl.Font.Size = new System.Web.UI.WebControls.FontUnit(new System.Web.UI.WebControls.Unit(14D, System.Web.UI.WebControls.UnitType.Pixel));
            
            #line default
            #line hidden
            
            #line 13 "/home/runner/workspace/RobloxWebSite/UserControls/UserContent/HeaderPane.ascx"
            @__ctrl.CssClass = "notranslate";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        private global::ASP.usercontrols_abuse_reportabusebutton_ascx @__BuildControl_ReportAbuse() {
            global::ASP.usercontrols_abuse_reportabusebutton_ascx @__ctrl;
            
            #line 14 "/home/runner/workspace/RobloxWebSite/UserControls/UserContent/HeaderPane.ascx"
            @__ctrl = new global::ASP.usercontrols_abuse_reportabusebutton_ascx();
            
            #line default
            #line hidden
            
            #line 14 "/home/runner/workspace/RobloxWebSite/UserControls/UserContent/HeaderPane.ascx"
            this.ReportAbuse = @__ctrl;
            
            #line default
            #line hidden
            this.ReportAbuse.InitializeAsUserControl(this.Page);
            
            #line 14 "/home/runner/workspace/RobloxWebSite/UserControls/UserContent/HeaderPane.ascx"
            @__ctrl.ID = "ReportAbuse";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        private global::System.Web.UI.WebControls.LinkButton @__BuildControl_updateStatusLink() {
            global::System.Web.UI.WebControls.LinkButton @__ctrl;
            
            #line 15 "/home/runner/workspace/RobloxWebSite/UserControls/UserContent/HeaderPane.ascx"
            @__ctrl = new global::System.Web.UI.WebControls.LinkButton();
            
            #line default
            #line hidden
            
            #line 15 "/home/runner/workspace/RobloxWebSite/UserControls/UserContent/HeaderPane.ascx"
            this.updateStatusLink = @__ctrl;
            
            #line default
            #line hidden
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            
            #line 15 "/home/runner/workspace/RobloxWebSite/UserControls/UserContent/HeaderPane.ascx"
            @__ctrl.ID = "updateStatusLink";
            
            #line default
            #line hidden
            
            #line 15 "/home/runner/workspace/RobloxWebSite/UserControls/UserContent/HeaderPane.ascx"
            @__ctrl.Visible = false;
            
            #line default
            #line hidden
            
            #line 15 "/home/runner/workspace/RobloxWebSite/UserControls/UserContent/HeaderPane.ascx"
            @__ctrl.OnClientClick = "document.getElementById(\'updateStatusBox\').style.display=\'block\';document.getElem" +
                "entById(\'ctl00_cphRoblox_rbxHeaderPane_updateStatusLink\').style.display=\'none\'; " +
                "return false;";
            
            #line default
            #line hidden
            
            #line 15 "/home/runner/workspace/RobloxWebSite/UserControls/UserContent/HeaderPane.ascx"
            @__ctrl.Text = "> Update My Status";
            
            #line default
            #line hidden
            
            #line 15 "/home/runner/workspace/RobloxWebSite/UserControls/UserContent/HeaderPane.ascx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("NavigateUrl", "#");
            
            #line default
            #line hidden
            
            #line 15 "/home/runner/workspace/RobloxWebSite/UserControls/UserContent/HeaderPane.ascx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("Style", "font-size:14px;word-wrap:normal");
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        private global::System.Web.UI.WebControls.TextBox @__BuildControl_txtStatusMessage() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            
            #line 19 "/home/runner/workspace/RobloxWebSite/UserControls/UserContent/HeaderPane.ascx"
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            
            #line default
            #line hidden
            
            #line 19 "/home/runner/workspace/RobloxWebSite/UserControls/UserContent/HeaderPane.ascx"
            this.txtStatusMessage = @__ctrl;
            
            #line default
            #line hidden
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            
            #line 19 "/home/runner/workspace/RobloxWebSite/UserControls/UserContent/HeaderPane.ascx"
            @__ctrl.ID = "txtStatusMessage";
            
            #line default
            #line hidden
            
            #line 19 "/home/runner/workspace/RobloxWebSite/UserControls/UserContent/HeaderPane.ascx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("Style", "margin-bottom:5px;width:560px;height:17px;");
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        private global::System.Web.UI.WebControls.Button @__BuildControl_btnUpdateStatus() {
            global::System.Web.UI.WebControls.Button @__ctrl;
            
            #line 21 "/home/runner/workspace/RobloxWebSite/UserControls/UserContent/HeaderPane.ascx"
            @__ctrl = new global::System.Web.UI.WebControls.Button();
            
            #line default
            #line hidden
            
            #line 21 "/home/runner/workspace/RobloxWebSite/UserControls/UserContent/HeaderPane.ascx"
            this.btnUpdateStatus = @__ctrl;
            
            #line default
            #line hidden
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            
            #line 21 "/home/runner/workspace/RobloxWebSite/UserControls/UserContent/HeaderPane.ascx"
            @__ctrl.ID = "btnUpdateStatus";
            
            #line default
            #line hidden
            
            #line 21 "/home/runner/workspace/RobloxWebSite/UserControls/UserContent/HeaderPane.ascx"
            @__ctrl.Text = "Save";
            
            #line default
            #line hidden
            
            #line 21 "/home/runner/workspace/RobloxWebSite/UserControls/UserContent/HeaderPane.ascx"
            @__ctrl.CssClass = "translate";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        private global::System.Web.UI.DataBoundLiteralControl @__BuildControl__bctrl_4() {
            global::System.Web.UI.DataBoundLiteralControl @__ctrl;
            
            #line 21 "/home/runner/workspace/RobloxWebSite/UserControls/UserContent/HeaderPane.ascx"
            @__ctrl = new global::System.Web.UI.DataBoundLiteralControl(0, 1);
            
            #line default
            #line hidden
            
            #line 21 "/home/runner/workspace/RobloxWebSite/UserControls/UserContent/HeaderPane.ascx"
            this._bctrl_4 = @__ctrl;
            
            #line default
            #line hidden
            @__ctrl.DataBinding += new System.EventHandler(this.@__DataBind__bctrl_4);
            return @__ctrl;
        }
        
        public void @__DataBind__bctrl_4(object sender, System.EventArgs e) {
            System.Web.UI.Control Container;
            System.Web.UI.DataBoundLiteralControl target;
            
            #line 8 "/home/runner/workspace/RobloxWebSite/UserControls/UserContent/HeaderPane.ascx"
            target = ((System.Web.UI.DataBoundLiteralControl)(sender));
            
            #line default
            #line hidden
            
            #line 8 "/home/runner/workspace/RobloxWebSite/UserControls/UserContent/HeaderPane.ascx"
            Container = ((System.Web.UI.Control)(target.BindingContainer));
            
            #line default
            #line hidden
            
            #line 8 "/home/runner/workspace/RobloxWebSite/UserControls/UserContent/HeaderPane.ascx"
            target.SetDataBoundString(0, System.Convert.ToString( updateStatusLink.ClientID ));
            
            #line default
            #line hidden
        }
        
        protected override void FrameworkInitialize() {
            base.FrameworkInitialize();
            this.SetStringResourcePointer(global::ASP.usercontrols_usercontent_headerpane_ascx.@__stringResource, 0);
            this.@__BuildControlTree(this);
        }
    }
}
