#pragma checksum "/home/runner/workspace/RobloxWebSite/UserControls/Modals/ConfirmationModal.ascx" "{406ea660-64cf-4c82-b6f0-42d48172a799}" "98983C64157EF173AAD555D49EFF1429"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
    using System;
    using System.Collections;
    using System.Collections.Specialized;
    using System.Configuration;
    using System.Text;
    using System.Text.RegularExpressions;
    using System.Web;
    using System.Web.Caching;
    using System.Web.SessionState;
    using System.Web.Security;
    using System.Web.Profile;
    using System.Web.UI;
    using System.Web.UI.WebControls;
    using System.Web.UI.HtmlControls;
    using Roblox.Website;
    using Roblox.Web.Code;
    
    
    public class usercontrols_modals_confirmationmodal_ascx : global::Roblox.Website.UserControls.Modals.ConfirmationModal {
        
        private static bool @__initialized = false;
        
        private static object @__stringResource = null;
        
        private static int @__autoHandlers;
        
        public usercontrols_modals_confirmationmodal_ascx() {
            ((global::Roblox.Website.UserControls.Modals.ConfirmationModal)(this)).AppRelativeVirtualPath = "~/UserControls/Modals/ConfirmationModal.ascx";
            if ((global::ASP.usercontrols_modals_confirmationmodal_ascx.@__initialized == false)) {
                global::ASP.usercontrols_modals_confirmationmodal_ascx.@__initialized = true;
            }
        }
        
        [System.Obsolete()]
        protected override int AutoHandlers {
            get {
                return ASP.usercontrols_modals_confirmationmodal_ascx.@__autoHandlers;
            }
            set {
                ASP.usercontrols_modals_confirmationmodal_ascx.@__autoHandlers = value;
            }
        }
        
        protected System.Web.HttpApplication ApplicationInstance {
            get {
                return ((System.Web.HttpApplication)(this.Context.ApplicationInstance));
            }
        }
        
        protected System.Web.Profile.DefaultProfile Profile {
            get {
                return ((System.Web.Profile.DefaultProfile)(this.Context.Profile));
            }
        }
        
        private void @__RenderTree(System.Web.UI.HtmlTextWriter @__output, System.Web.UI.Control parameterContainer) {
            @__output.Write(@"<div class=""ConfirmationModal modalPopup unifiedModal smallModal"" data-modal-handle=""confirmation"" style=""display:none;"">
    <a class=""genericmodal-close ImageButton closeBtnCircle_20h""></a>
    <div class=""Title""></div>
    <div class=""GenericModalBody"">
        <div class=""TopBody"">
            <div class=""ImageContainer roblox-item-image"" data-image-size=""small"" data-no-overlays data-no-click>
                <img class=""GenericModalImage"" alt=""generic image"" />
            </div>
            <div class=""Message""></div>
        </div>
        <div class=""ConfirmationModalButtonContainer GenericModalButtonContainer"">
            <a href id=""roblox-confirm-btn""><span></span></a>
            <a href id=""roblox-decline-btn""><span></span></a>
        </div>
        <div class=""ConfirmationModalFooter"">
        
        </div>  
    </div>  
    <script type=""text/javascript"">
        Roblox = Roblox || {};
        Roblox.Resources = Roblox.Resources || {};

        //<sl:translate>
        Roblox.Resources.GenericConfirmation = {
            yes: """);
            
            #line 20 "/home/runner/workspace/RobloxWebSite/UserControls/Modals/ConfirmationModal.ascx"
            @__output.Write(LangResources["Action.Yes"]);
            
            #line default
            #line hidden
            @__output.Write("\",\n            No: \"");
            
            #line 20 "/home/runner/workspace/RobloxWebSite/UserControls/Modals/ConfirmationModal.ascx"
            @__output.Write(LangResources["Action.No"]);
            
            #line default
            #line hidden
            @__output.Write("\",\n            Confirm: \"");
            
            #line 20 "/home/runner/workspace/RobloxWebSite/UserControls/Modals/ConfirmationModal.ascx"
            @__output.Write(LangResources["Action.Confirm"]);
            
            #line default
            #line hidden
            @__output.Write("\",\n            Cancel: \"");
            
            #line 20 "/home/runner/workspace/RobloxWebSite/UserControls/Modals/ConfirmationModal.ascx"
            @__output.Write(LangResources["Action.Cancel"]);
            
            #line default
            #line hidden
            @__output.Write("\"\n        };\n        //</sl:translate>\n    </script>\n</div>");
        }
        
        private void @__BuildControlTree(usercontrols_modals_confirmationmodal_ascx @__ctrl) {
            @__ctrl.SetRenderMethodDelegate(new System.Web.UI.RenderMethod(this.@__RenderTree));
        }
        
        protected override void FrameworkInitialize() {
            base.FrameworkInitialize();
            this.SetStringResourcePointer(global::ASP.usercontrols_modals_confirmationmodal_ascx.@__stringResource, 0);
            this.@__BuildControlTree(this);
        }
    }
}
