#pragma checksum "/home/runner/workspace/RobloxWebSite/UserControls/Alerts.ascx" "{406ea660-64cf-4c82-b6f0-42d48172a799}" "773648577F08C361D31D37877504E2AB"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
    using System;
    using System.Collections;
    using System.Collections.Specialized;
    using System.Configuration;
    using System.Text;
    using System.Text.RegularExpressions;
    using System.Web;
    using System.Web.Caching;
    using System.Web.SessionState;
    using System.Web.Security;
    using System.Web.Profile;
    using System.Web.UI;
    using System.Web.UI.WebControls;
    using System.Web.UI.HtmlControls;
    using Roblox.Website;
    using Roblox.Web.Code;
    
    
    public class usercontrols_alerts_ascx : global::Roblox.Website.UserControls.Alerts {
        
        private static bool @__initialized = false;
        
        private static object @__stringResource = null;
        
        private static int @__autoHandlers;
        
        public usercontrols_alerts_ascx() {
            ((global::Roblox.Website.UserControls.Alerts)(this)).AppRelativeVirtualPath = "~/UserControls/Alerts.ascx";
            if ((global::ASP.usercontrols_alerts_ascx.@__initialized == false)) {
                global::ASP.usercontrols_alerts_ascx.@__initialized = true;
            }
        }
        
        [System.Obsolete()]
        protected override int AutoHandlers {
            get {
                return ASP.usercontrols_alerts_ascx.@__autoHandlers;
            }
            set {
                ASP.usercontrols_alerts_ascx.@__autoHandlers = value;
            }
        }
        
        protected System.Web.HttpApplication ApplicationInstance {
            get {
                return ((System.Web.HttpApplication)(this.Context.ApplicationInstance));
            }
        }
        
        protected System.Web.Profile.DefaultProfile Profile {
            get {
                return ((System.Web.Profile.DefaultProfile)(this.Context.Profile));
            }
        }
        
        private void @__BuildControlTree(usercontrols_alerts_ascx @__ctrl) {
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/Alerts.ascx"
            this.@__BuildControl_AlertSpacePanel();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/Alerts.ascx"
            @__parser.AddParsedSubObject(this.AlertSpacePanel);
            
            #line default
            #line hidden
        }
        
        private global::System.Web.UI.WebControls.Panel @__BuildControl_AlertSpacePanel() {
            global::System.Web.UI.WebControls.Panel @__ctrl;
            
            #line 2 "/home/runner/workspace/RobloxWebSite/UserControls/Alerts.ascx"
            @__ctrl = new global::System.Web.UI.WebControls.Panel();
            
            #line default
            #line hidden
            
            #line 2 "/home/runner/workspace/RobloxWebSite/UserControls/Alerts.ascx"
            this.AlertSpacePanel = @__ctrl;
            
            #line default
            #line hidden
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            
            #line 2 "/home/runner/workspace/RobloxWebSite/UserControls/Alerts.ascx"
            @__ctrl.ID = "AlertSpacePanel";
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 2 "/home/runner/workspace/RobloxWebSite/UserControls/Alerts.ascx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\n    <div class=\"SmallHeaderAlertSpaceLeft\">\n        <div class=\"AlertSpace\">\n   " +
                        "         <div class=\"MessageAlert\">\n                "));
            
            #line default
            #line hidden
            
            #line 2 "/home/runner/workspace/RobloxWebSite/UserControls/Alerts.ascx"
            this.@__BuildControl_MessageAlertCaptionHyperLink();
            
            #line default
            #line hidden
            
            #line 2 "/home/runner/workspace/RobloxWebSite/UserControls/Alerts.ascx"
            @__parser.AddParsedSubObject(this.MessageAlertCaptionHyperLink);
            
            #line default
            #line hidden
            
            #line 2 "/home/runner/workspace/RobloxWebSite/UserControls/Alerts.ascx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\n            </div>\n            <div class=\"FriendsAlert\">\n                "));
            
            #line default
            #line hidden
            
            #line 2 "/home/runner/workspace/RobloxWebSite/UserControls/Alerts.ascx"
            this.@__BuildControl_FriendsAlertCaptionHyperLink();
            
            #line default
            #line hidden
            
            #line 2 "/home/runner/workspace/RobloxWebSite/UserControls/Alerts.ascx"
            @__parser.AddParsedSubObject(this.FriendsAlertCaptionHyperLink);
            
            #line default
            #line hidden
            
            #line 2 "/home/runner/workspace/RobloxWebSite/UserControls/Alerts.ascx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\n            </div>\n            <div class=\"RobuxAlert\">\n                "));
            
            #line default
            #line hidden
            
            #line 2 "/home/runner/workspace/RobloxWebSite/UserControls/Alerts.ascx"
            this.@__BuildControl_RobuxAlertCaptionHyperLink();
            
            #line default
            #line hidden
            
            #line 2 "/home/runner/workspace/RobloxWebSite/UserControls/Alerts.ascx"
            @__parser.AddParsedSubObject(this.RobuxAlertCaptionHyperLink);
            
            #line default
            #line hidden
            
            #line 2 "/home/runner/workspace/RobloxWebSite/UserControls/Alerts.ascx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\n            </div>\n            <div class=\"TicketsAlert\">\n                "));
            
            #line default
            #line hidden
            
            #line 2 "/home/runner/workspace/RobloxWebSite/UserControls/Alerts.ascx"
            this.@__BuildControl_TicketsAlertCaptionHyperLink();
            
            #line default
            #line hidden
            
            #line 2 "/home/runner/workspace/RobloxWebSite/UserControls/Alerts.ascx"
            @__parser.AddParsedSubObject(this.TicketsAlertCaptionHyperLink);
            
            #line default
            #line hidden
            
            #line 2 "/home/runner/workspace/RobloxWebSite/UserControls/Alerts.ascx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\n            </div>\n        </div>\n    </div>\n"));
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        private global::System.Web.UI.WebControls.HyperLink @__BuildControl_MessageAlertCaptionHyperLink() {
            global::System.Web.UI.WebControls.HyperLink @__ctrl;
            
            #line 6 "/home/runner/workspace/RobloxWebSite/UserControls/Alerts.ascx"
            @__ctrl = new global::System.Web.UI.WebControls.HyperLink();
            
            #line default
            #line hidden
            
            #line 6 "/home/runner/workspace/RobloxWebSite/UserControls/Alerts.ascx"
            this.MessageAlertCaptionHyperLink = @__ctrl;
            
            #line default
            #line hidden
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            
            #line 6 "/home/runner/workspace/RobloxWebSite/UserControls/Alerts.ascx"
            @__ctrl.ID = "MessageAlertCaptionHyperLink";
            
            #line default
            #line hidden
            
            #line 6 "/home/runner/workspace/RobloxWebSite/UserControls/Alerts.ascx"
            @__ctrl.ToolTip = "Inbox";
            
            #line default
            #line hidden
            
            #line 6 "/home/runner/workspace/RobloxWebSite/UserControls/Alerts.ascx"
            @__ctrl.NavigateUrl = "/my/messages";
            
            #line default
            #line hidden
            
            #line 6 "/home/runner/workspace/RobloxWebSite/UserControls/Alerts.ascx"
            @__ctrl.CssClass = "MessageAlertCaption tooltip-bottom";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        private global::System.Web.UI.WebControls.HyperLink @__BuildControl_FriendsAlertCaptionHyperLink() {
            global::System.Web.UI.WebControls.HyperLink @__ctrl;
            
            #line 9 "/home/runner/workspace/RobloxWebSite/UserControls/Alerts.ascx"
            @__ctrl = new global::System.Web.UI.WebControls.HyperLink();
            
            #line default
            #line hidden
            
            #line 9 "/home/runner/workspace/RobloxWebSite/UserControls/Alerts.ascx"
            this.FriendsAlertCaptionHyperLink = @__ctrl;
            
            #line default
            #line hidden
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            
            #line 9 "/home/runner/workspace/RobloxWebSite/UserControls/Alerts.ascx"
            @__ctrl.ID = "FriendsAlertCaptionHyperLink";
            
            #line default
            #line hidden
            
            #line 9 "/home/runner/workspace/RobloxWebSite/UserControls/Alerts.ascx"
            @__ctrl.ToolTip = "Friend Requests";
            
            #line default
            #line hidden
            
            #line 9 "/home/runner/workspace/RobloxWebSite/UserControls/Alerts.ascx"
            @__ctrl.NavigateUrl = "~/Friends.aspx";
            
            #line default
            #line hidden
            
            #line 9 "/home/runner/workspace/RobloxWebSite/UserControls/Alerts.ascx"
            @__ctrl.CssClass = "FriendsAlertCaption tooltip-bottom";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        private global::System.Web.UI.WebControls.HyperLink @__BuildControl_RobuxAlertCaptionHyperLink() {
            global::System.Web.UI.WebControls.HyperLink @__ctrl;
            
            #line 12 "/home/runner/workspace/RobloxWebSite/UserControls/Alerts.ascx"
            @__ctrl = new global::System.Web.UI.WebControls.HyperLink();
            
            #line default
            #line hidden
            
            #line 12 "/home/runner/workspace/RobloxWebSite/UserControls/Alerts.ascx"
            this.RobuxAlertCaptionHyperLink = @__ctrl;
            
            #line default
            #line hidden
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            
            #line 12 "/home/runner/workspace/RobloxWebSite/UserControls/Alerts.ascx"
            @__ctrl.ID = "RobuxAlertCaptionHyperLink";
            
            #line default
            #line hidden
            
            #line 12 "/home/runner/workspace/RobloxWebSite/UserControls/Alerts.ascx"
            @__ctrl.ToolTip = "ROBUX";
            
            #line default
            #line hidden
            
            #line 12 "/home/runner/workspace/RobloxWebSite/UserControls/Alerts.ascx"
            @__ctrl.NavigateUrl = "~/My/Money.aspx?tab=MyTransactions";
            
            #line default
            #line hidden
            
            #line 12 "/home/runner/workspace/RobloxWebSite/UserControls/Alerts.ascx"
            @__ctrl.CssClass = "RobuxAlertCaption tooltip-bottom";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        private global::System.Web.UI.WebControls.HyperLink @__BuildControl_TicketsAlertCaptionHyperLink() {
            global::System.Web.UI.WebControls.HyperLink @__ctrl;
            
            #line 15 "/home/runner/workspace/RobloxWebSite/UserControls/Alerts.ascx"
            @__ctrl = new global::System.Web.UI.WebControls.HyperLink();
            
            #line default
            #line hidden
            
            #line 15 "/home/runner/workspace/RobloxWebSite/UserControls/Alerts.ascx"
            this.TicketsAlertCaptionHyperLink = @__ctrl;
            
            #line default
            #line hidden
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            
            #line 15 "/home/runner/workspace/RobloxWebSite/UserControls/Alerts.ascx"
            @__ctrl.ID = "TicketsAlertCaptionHyperLink";
            
            #line default
            #line hidden
            
            #line 15 "/home/runner/workspace/RobloxWebSite/UserControls/Alerts.ascx"
            @__ctrl.ToolTip = "Tickets";
            
            #line default
            #line hidden
            
            #line 15 "/home/runner/workspace/RobloxWebSite/UserControls/Alerts.ascx"
            @__ctrl.NavigateUrl = "~/My/Money.aspx?tab=MyTransactions";
            
            #line default
            #line hidden
            
            #line 15 "/home/runner/workspace/RobloxWebSite/UserControls/Alerts.ascx"
            @__ctrl.CssClass = "TicketsAlertCaption tooltip-bottom";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        protected override void FrameworkInitialize() {
            base.FrameworkInitialize();
            this.SetStringResourcePointer(global::ASP.usercontrols_alerts_ascx.@__stringResource, 0);
            this.@__BuildControlTree(this);
        }
    }
}
