#pragma checksum "/home/runner/workspace/RobloxWebSite/UserControls/PlaceAccessIndicator.ascx" "{406ea660-64cf-4c82-b6f0-42d48172a799}" "E8FB7054D39B221DE045AE8B4D360924"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
    using System;
    using System.Collections;
    using System.Collections.Specialized;
    using System.Configuration;
    using System.Text;
    using System.Text.RegularExpressions;
    using System.Web;
    using System.Web.Caching;
    using System.Web.SessionState;
    using System.Web.Security;
    using System.Web.Profile;
    using System.Web.UI;
    using System.Web.UI.WebControls;
    using System.Web.UI.HtmlControls;
    using Roblox.Website;
    using Roblox.Web.Code;
    
    
    public class usercontrols_placeaccessindicator_ascx : global::Roblox.Website.UserControls.PlaceAccessIndicator {
        
        private static bool @__initialized = false;
        
        private static object @__stringResource = null;
        
        private static int @__autoHandlers;
        
        public usercontrols_placeaccessindicator_ascx() {
            ((global::Roblox.Website.UserControls.PlaceAccessIndicator)(this)).AppRelativeVirtualPath = "~/UserControls/PlaceAccessIndicator.ascx";
            if ((global::ASP.usercontrols_placeaccessindicator_ascx.@__initialized == false)) {
                global::ASP.usercontrols_placeaccessindicator_ascx.@__initialized = true;
            }
        }
        
        [System.Obsolete()]
        protected override int AutoHandlers {
            get {
                return ASP.usercontrols_placeaccessindicator_ascx.@__autoHandlers;
            }
            set {
                ASP.usercontrols_placeaccessindicator_ascx.@__autoHandlers = value;
            }
        }
        
        protected System.Web.HttpApplication ApplicationInstance {
            get {
                return ((System.Web.HttpApplication)(this.Context.ApplicationInstance));
            }
        }
        
        protected System.Web.Profile.DefaultProfile Profile {
            get {
                return ((System.Web.Profile.DefaultProfile)(this.Context.Profile));
            }
        }
        
        private void @__BuildControlTree(usercontrols_placeaccessindicator_ascx @__ctrl) {
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/PlaceAccessIndicator.ascx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("<span class=\"PlaceAccessIndicator\">\n\t"));
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/PlaceAccessIndicator.ascx"
            this.@__BuildControl_FriendsOnlyLocked();
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/PlaceAccessIndicator.ascx"
            @__parser.AddParsedSubObject(this.FriendsOnlyLocked);
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/PlaceAccessIndicator.ascx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\n    "));
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/PlaceAccessIndicator.ascx"
            this.@__BuildControl_FriendsOnlyUnlocked();
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/PlaceAccessIndicator.ascx"
            @__parser.AddParsedSubObject(this.FriendsOnlyUnlocked);
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/PlaceAccessIndicator.ascx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\n\t"));
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/PlaceAccessIndicator.ascx"
            this.@__BuildControl_ExpiredSelf();
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/PlaceAccessIndicator.ascx"
            @__parser.AddParsedSubObject(this.ExpiredSelf);
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/PlaceAccessIndicator.ascx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\n    "));
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/PlaceAccessIndicator.ascx"
            this.@__BuildControl_ExpiredOther();
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/PlaceAccessIndicator.ascx"
            @__parser.AddParsedSubObject(this.ExpiredOther);
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/PlaceAccessIndicator.ascx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\t\n</span>\n\t"));
            
            #line default
            #line hidden
        }
        
        private global::System.Web.UI.HtmlControls.HtmlGenericControl @__BuildControl_FriendsOnlyLocked() {
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl;
            
            #line 3 "/home/runner/workspace/RobloxWebSite/UserControls/PlaceAccessIndicator.ascx"
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlGenericControl("span");
            
            #line default
            #line hidden
            
            #line 3 "/home/runner/workspace/RobloxWebSite/UserControls/PlaceAccessIndicator.ascx"
            this.FriendsOnlyLocked = @__ctrl;
            
            #line default
            #line hidden
            
            #line 3 "/home/runner/workspace/RobloxWebSite/UserControls/PlaceAccessIndicator.ascx"
            @__ctrl.ID = "FriendsOnlyLocked";
            
            #line default
            #line hidden
            
            #line 3 "/home/runner/workspace/RobloxWebSite/UserControls/PlaceAccessIndicator.ascx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("style", "display: none");
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 3 "/home/runner/workspace/RobloxWebSite/UserControls/PlaceAccessIndicator.ascx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\n        <a class=\"iLocked tooltip\" title=\"Friends Only\"></a><span class=\"invisib" +
                        "le\">&nbsp;Friends-only</span>\n\t"));
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        private global::System.Web.UI.HtmlControls.HtmlGenericControl @__BuildControl_FriendsOnlyUnlocked() {
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl;
            
            #line 6 "/home/runner/workspace/RobloxWebSite/UserControls/PlaceAccessIndicator.ascx"
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlGenericControl("span");
            
            #line default
            #line hidden
            
            #line 6 "/home/runner/workspace/RobloxWebSite/UserControls/PlaceAccessIndicator.ascx"
            this.FriendsOnlyUnlocked = @__ctrl;
            
            #line default
            #line hidden
            
            #line 6 "/home/runner/workspace/RobloxWebSite/UserControls/PlaceAccessIndicator.ascx"
            @__ctrl.ID = "FriendsOnlyUnlocked";
            
            #line default
            #line hidden
            
            #line 6 "/home/runner/workspace/RobloxWebSite/UserControls/PlaceAccessIndicator.ascx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("style", "display: none");
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 6 "/home/runner/workspace/RobloxWebSite/UserControls/PlaceAccessIndicator.ascx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\n        <a class=\"iUnlocked tooltip\" title=\"Friends Only - You are friends\"></a>" +
                        "<span class=\"invisible\">&nbsp;Friends-only: You are friends</span>\n\t"));
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        private global::System.Web.UI.HtmlControls.HtmlGenericControl @__BuildControl_ExpiredSelf() {
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl;
            
            #line 9 "/home/runner/workspace/RobloxWebSite/UserControls/PlaceAccessIndicator.ascx"
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlGenericControl("span");
            
            #line default
            #line hidden
            
            #line 9 "/home/runner/workspace/RobloxWebSite/UserControls/PlaceAccessIndicator.ascx"
            this.ExpiredSelf = @__ctrl;
            
            #line default
            #line hidden
            
            #line 9 "/home/runner/workspace/RobloxWebSite/UserControls/PlaceAccessIndicator.ascx"
            @__ctrl.ID = "ExpiredSelf";
            
            #line default
            #line hidden
            
            #line 9 "/home/runner/workspace/RobloxWebSite/UserControls/PlaceAccessIndicator.ascx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("style", "display: none");
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 9 "/home/runner/workspace/RobloxWebSite/UserControls/PlaceAccessIndicator.ascx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
        <a class=""iLocked tooltip"" title=""Locked""></a>
        <span class=""invisible"">&nbsp;Your Outrageous Builders Club, Turbo Builders Club, or Builders Club membership has expired, so you can
        only have one open place. Your places will not be deleted, and you can "));
            
            #line default
            #line hidden
            
            #line 9 "/home/runner/workspace/RobloxWebSite/UserControls/PlaceAccessIndicator.ascx"
            this.@__BuildControl_RBXLDownloadLink();
            
            #line default
            #line hidden
            
            #line 9 "/home/runner/workspace/RobloxWebSite/UserControls/PlaceAccessIndicator.ascx"
            @__parser.AddParsedSubObject(this.RBXLDownloadLink);
            
            #line default
            #line hidden
            
            #line 9 "/home/runner/workspace/RobloxWebSite/UserControls/PlaceAccessIndicator.ascx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(" To unlock all of your places,\n        please <a href=\"/upgrades/BuildersClubMemb" +
                        "erships.aspx\">re-order Outrageous Builders Club, Turbo Builders Club, or Builder" +
                        "s\n            Club </a>.<br /></span>\n    "));
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        private global::System.Web.UI.WebControls.HyperLink @__BuildControl_RBXLDownloadLink() {
            global::System.Web.UI.WebControls.HyperLink @__ctrl;
            
            #line 12 "/home/runner/workspace/RobloxWebSite/UserControls/PlaceAccessIndicator.ascx"
            @__ctrl = new global::System.Web.UI.WebControls.HyperLink();
            
            #line default
            #line hidden
            
            #line 12 "/home/runner/workspace/RobloxWebSite/UserControls/PlaceAccessIndicator.ascx"
            this.RBXLDownloadLink = @__ctrl;
            
            #line default
            #line hidden
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            
            #line 12 "/home/runner/workspace/RobloxWebSite/UserControls/PlaceAccessIndicator.ascx"
            @__ctrl.ID = "RBXLDownloadLink";
            
            #line default
            #line hidden
            
            #line 12 "/home/runner/workspace/RobloxWebSite/UserControls/PlaceAccessIndicator.ascx"
            @__ctrl.Text = "download the RBXL here.";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        private global::System.Web.UI.HtmlControls.HtmlGenericControl @__BuildControl_ExpiredOther() {
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl;
            
            #line 16 "/home/runner/workspace/RobloxWebSite/UserControls/PlaceAccessIndicator.ascx"
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlGenericControl("span");
            
            #line default
            #line hidden
            
            #line 16 "/home/runner/workspace/RobloxWebSite/UserControls/PlaceAccessIndicator.ascx"
            this.ExpiredOther = @__ctrl;
            
            #line default
            #line hidden
            
            #line 16 "/home/runner/workspace/RobloxWebSite/UserControls/PlaceAccessIndicator.ascx"
            @__ctrl.ID = "ExpiredOther";
            
            #line default
            #line hidden
            
            #line 16 "/home/runner/workspace/RobloxWebSite/UserControls/PlaceAccessIndicator.ascx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("style", "display: none");
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 16 "/home/runner/workspace/RobloxWebSite/UserControls/PlaceAccessIndicator.ascx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
        <a class=""iLocked tooltip"" title=""Locked""></a>
        <span class=""invisible"">This place is locked because the creator's <a href=""/upgrades/BuildersClubMemberships.aspx"">Builders
            Club / Turbo Builders Club / Outrageous Builders Club </a>has expired.
		</span>
	"));
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        protected override void FrameworkInitialize() {
            base.FrameworkInitialize();
            this.SetStringResourcePointer(global::ASP.usercontrols_placeaccessindicator_ascx.@__stringResource, 0);
            this.@__BuildControlTree(this);
        }
    }
}
