#pragma checksum "/home/runner/workspace/RobloxWebSite/UserControls/TrackingPixels/JavascriptErrorTracker.ascx" "{406ea660-64cf-4c82-b6f0-42d48172a799}" "D2208385AFDA20422BEDA3CE412624E1"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
    using System;
    using System.Collections;
    using System.Collections.Specialized;
    using System.Configuration;
    using System.Text;
    using System.Text.RegularExpressions;
    using System.Web;
    using System.Web.Caching;
    using System.Web.SessionState;
    using System.Web.Security;
    using System.Web.Profile;
    using System.Web.UI;
    using System.Web.UI.WebControls;
    using System.Web.UI.HtmlControls;
    using Roblox.Website;
    using Roblox.Web.Code;
    
    
    public class usercontrols_trackingpixels_javascripterrortracker_ascx : global::Roblox.Website.UserControls.TrackingPixels.JavascriptErrorTracker {
        
        private static bool @__initialized = false;
        
        private static object @__stringResource = null;
        
        private static int @__autoHandlers;
        
        public usercontrols_trackingpixels_javascripterrortracker_ascx() {
            ((global::Roblox.Website.UserControls.TrackingPixels.JavascriptErrorTracker)(this)).AppRelativeVirtualPath = "~/UserControls/TrackingPixels/JavascriptErrorTracker.ascx";
            if ((global::ASP.usercontrols_trackingpixels_javascripterrortracker_ascx.@__initialized == false)) {
                global::ASP.usercontrols_trackingpixels_javascripterrortracker_ascx.@__initialized = true;
            }
        }
        
        [System.Obsolete()]
        protected override int AutoHandlers {
            get {
                return ASP.usercontrols_trackingpixels_javascripterrortracker_ascx.@__autoHandlers;
            }
            set {
                ASP.usercontrols_trackingpixels_javascripterrortracker_ascx.@__autoHandlers = value;
            }
        }
        
        protected System.Web.HttpApplication ApplicationInstance {
            get {
                return ((System.Web.HttpApplication)(this.Context.ApplicationInstance));
            }
        }
        
        protected System.Web.Profile.DefaultProfile Profile {
            get {
                return ((System.Web.Profile.DefaultProfile)(this.Context.Profile));
            }
        }
        
        private void @__RenderTree(System.Web.UI.HtmlTextWriter @__output, System.Web.UI.Control parameterContainer) {
            @__output.Write("<script type=\"text/javascript\">\n        $(function () {\n            Roblox.JSErro" +
                    "rTracker.initialize(");
            
            #line 2 "/home/runner/workspace/RobloxWebSite/UserControls/TrackingPixels/JavascriptErrorTracker.ascx"
            @__output.Write(JavascriptErrorTrackerViewModel.InitializeParameter);
            
            #line default
            #line hidden
            @__output.Write(");\n        });\n</script>");
        }
        
        private void @__BuildControlTree(usercontrols_trackingpixels_javascripterrortracker_ascx @__ctrl) {
            @__ctrl.SetRenderMethodDelegate(new System.Web.UI.RenderMethod(this.@__RenderTree));
        }
        
        protected override void FrameworkInitialize() {
            base.FrameworkInitialize();
            this.SetStringResourcePointer(global::ASP.usercontrols_trackingpixels_javascripterrortracker_ascx.@__stringResource, 0);
            this.@__BuildControlTree(this);
        }
    }
}
