#pragma checksum "/home/runner/workspace/RobloxWebSite/UserControls/BonusRoundJavaScript.ascx" "{406ea660-64cf-4c82-b6f0-42d48172a799}" "40681CA5F59C214BC0EAB35B3698A826"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
    using System;
    using System.Collections;
    using System.Collections.Specialized;
    using System.Configuration;
    using System.Text;
    using System.Text.RegularExpressions;
    using System.Web;
    using System.Web.Caching;
    using System.Web.SessionState;
    using System.Web.Security;
    using System.Web.Profile;
    using System.Web.UI;
    using System.Web.UI.WebControls;
    using System.Web.UI.HtmlControls;
    using Roblox.Website;
    using Roblox.Web.Code;
    
    
    public class usercontrols_bonusroundjavascript_ascx : global::Roblox.Website.UserControls.BonusRoundJavaScript {
        
        private static bool @__initialized = false;
        
        private static object @__stringResource = null;
        
        private static int @__autoHandlers;
        
        
        #line 2 "/home/runner/workspace/RobloxWebSite/UserControls/BonusRoundJavaScript.ascx"
        protected global::System.Web.UI.DataBoundLiteralControl _bctrl_86;
        
        #line default
        #line hidden
        
        
        #line 2 "/home/runner/workspace/RobloxWebSite/UserControls/BonusRoundJavaScript.ascx"
        protected global::System.Web.UI.DataBoundLiteralControl _bctrl_87;
        
        #line default
        #line hidden
        
        
        #line 2 "/home/runner/workspace/RobloxWebSite/UserControls/BonusRoundJavaScript.ascx"
        protected global::System.Web.UI.DataBoundLiteralControl _bctrl_88;
        
        #line default
        #line hidden
        
        
        #line 2 "/home/runner/workspace/RobloxWebSite/UserControls/BonusRoundJavaScript.ascx"
        protected global::System.Web.UI.DataBoundLiteralControl _bctrl_89;
        
        #line default
        #line hidden
        
        
        #line 2 "/home/runner/workspace/RobloxWebSite/UserControls/BonusRoundJavaScript.ascx"
        protected global::System.Web.UI.DataBoundLiteralControl _bctrl_90;
        
        #line default
        #line hidden
        
        
        #line 2 "/home/runner/workspace/RobloxWebSite/UserControls/BonusRoundJavaScript.ascx"
        protected global::System.Web.UI.DataBoundLiteralControl _bctrl_91;
        
        #line default
        #line hidden
        
        
        #line 2 "/home/runner/workspace/RobloxWebSite/UserControls/BonusRoundJavaScript.ascx"
        protected global::System.Web.UI.DataBoundLiteralControl _bctrl_92;
        
        #line default
        #line hidden
        
        
        #line 2 "/home/runner/workspace/RobloxWebSite/UserControls/BonusRoundJavaScript.ascx"
        protected global::System.Web.UI.DataBoundLiteralControl _bctrl_93;
        
        #line default
        #line hidden
        
        
        #line 2 "/home/runner/workspace/RobloxWebSite/UserControls/BonusRoundJavaScript.ascx"
        protected global::System.Web.UI.DataBoundLiteralControl _bctrl_94;
        
        #line default
        #line hidden
        
        
        #line 2 "/home/runner/workspace/RobloxWebSite/UserControls/BonusRoundJavaScript.ascx"
        protected global::System.Web.UI.DataBoundLiteralControl _bctrl_95;
        
        #line default
        #line hidden
        
        public usercontrols_bonusroundjavascript_ascx() {
            ((global::Roblox.Website.UserControls.BonusRoundJavaScript)(this)).AppRelativeVirtualPath = "~/UserControls/BonusRoundJavaScript.ascx";
            if ((global::ASP.usercontrols_bonusroundjavascript_ascx.@__initialized == false)) {
                global::ASP.usercontrols_bonusroundjavascript_ascx.@__initialized = true;
            }
        }
        
        [System.Obsolete()]
        protected override int AutoHandlers {
            get {
                return ASP.usercontrols_bonusroundjavascript_ascx.@__autoHandlers;
            }
            set {
                ASP.usercontrols_bonusroundjavascript_ascx.@__autoHandlers = value;
            }
        }
        
        protected System.Web.HttpApplication ApplicationInstance {
            get {
                return ((System.Web.HttpApplication)(this.Context.ApplicationInstance));
            }
        }
        
        protected System.Web.Profile.DefaultProfile Profile {
            get {
                return ((System.Web.Profile.DefaultProfile)(this.Context.Profile));
            }
        }
        
        private void @__BuildControlTree(usercontrols_bonusroundjavascript_ascx @__ctrl) {
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/BonusRoundJavaScript.ascx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("<script type=\"text/javascript\">\n        var referrerIsValid = true;\n        funct" +
                        "ion check_code() {\n            if ($(\"#"));
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/BonusRoundJavaScript.ascx"
            this.@__BuildControl__bctrl_86();
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/BonusRoundJavaScript.ascx"
            @__parser.AddParsedSubObject(this._bctrl_86);
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/BonusRoundJavaScript.ascx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\").val() != \"\") {\n                $.ajax({\n                    type: \"GET\",\n     " +
                        "               url: \"/Login/ReferralCodeCheck.ashx?&code=\" + $(\"#"));
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/BonusRoundJavaScript.ascx"
            this.@__BuildControl__bctrl_87();
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/BonusRoundJavaScript.ascx"
            @__parser.AddParsedSubObject(this._bctrl_87);
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/BonusRoundJavaScript.ascx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\").val(),\n                    success: function(data) {\n\n                        " +
                        "if (data == \"false\") {\n                            $(\"#code_checker\").html(\"<img" +
                        " src=\'"));
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/BonusRoundJavaScript.ascx"
            this.@__BuildControl__bctrl_88();
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/BonusRoundJavaScript.ascx"
            @__parser.AddParsedSubObject(this._bctrl_88);
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/BonusRoundJavaScript.ascx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\' />\");\n                            referrerIsValid = false;\n\n                   " +
                        "     }\n                        else if (data == \"true\") {\n                      " +
                        "      $(\"#code_checker\").html(\"<img src=\'"));
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/BonusRoundJavaScript.ascx"
            this.@__BuildControl__bctrl_89();
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/BonusRoundJavaScript.ascx"
            @__parser.AddParsedSubObject(this._bctrl_89);
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/BonusRoundJavaScript.ascx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"' />"");
                            referrerIsValid = true;
                        }
                    }
                });
            }
            else {
                $(""#code_checker"").html("""");
                referrerIsValid = true;
            }
        }
        function initiate_waiting() {
            var input_code = $(""#"));
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/BonusRoundJavaScript.ascx"
            this.@__BuildControl__bctrl_90();
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/BonusRoundJavaScript.ascx"
            @__parser.AddParsedSubObject(this._bctrl_90);
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/BonusRoundJavaScript.ascx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\").val();\n            if (input_code != \"\") {\n                $(\"#code_checker\")." +
                        "html(\"<img src=\'"));
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/BonusRoundJavaScript.ascx"
            this.@__BuildControl__bctrl_91();
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/BonusRoundJavaScript.ascx"
            @__parser.AddParsedSubObject(this._bctrl_91);
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/BonusRoundJavaScript.ascx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\' />\");\n                if (input_code.length > 3 && input_code.length < 20) {\n  " +
                        "                  check_code();\n                }\n                else {\n       " +
                        "             $(\"#code_checker\").html(\"<img src=\'"));
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/BonusRoundJavaScript.ascx"
            this.@__BuildControl__bctrl_92();
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/BonusRoundJavaScript.ascx"
            @__parser.AddParsedSubObject(this._bctrl_92);
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/BonusRoundJavaScript.ascx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"' />"");
                    referrerIsValid = false;
                }
            }
            else {
                $(""#code_checker"").html("""");
                referrerIsValid = true;
            }
        }
        function checkReferralState(alsoCheckEmail) {
            if (referrerIsValid == false) {
                var answer = confirm(""The referral code you've entered is invalid. Are you sure you want to create an account without a referral code?"");
                if (answer) {
                    if (!alsoCheckEmail)
                        return true;
                    else
                    {
                        if ($(""#"));
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/BonusRoundJavaScript.ascx"
            this.@__BuildControl__bctrl_93();
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/BonusRoundJavaScript.ascx"
            @__parser.AddParsedSubObject(this._bctrl_93);
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/BonusRoundJavaScript.ascx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@""").val() == """")
			            {
			            var popupText = '';
                                    //Warn with modal popup that email is not present
                                   
                                        popupText = ""Looks like you're trying to enter your email but forgot. Enter email and click OK, or click Enter Email Later if you don't want to enter your email."";
                                   
                                   
                                   alert(popupText);
                                   
                                   return false;
			            }
			            return true;
                    }
                }
                else {
                    return false;
                }
            }
            else {
                if (!alsoCheckEmail)
                    return true;
                else 
                {
                    if ($(""#"));
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/BonusRoundJavaScript.ascx"
            this.@__BuildControl__bctrl_94();
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/BonusRoundJavaScript.ascx"
            @__parser.AddParsedSubObject(this._bctrl_94);
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/BonusRoundJavaScript.ascx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@""").val() == """")
			        {
			        var popupText = '';
                                //Warn with modal popup that email is not present
                               
                                    popupText = ""Looks like you're trying to enter your email but forgot. Enter email and click OK, or click Enter Email Later if you don't want to enter your email."";
                               
                               
                               alert(popupText);
                               
                               return false;
			        }
			        return true;
                }
            }
        }
        $(document).ready(function() {
            if ($(""#"));
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/BonusRoundJavaScript.ascx"
            this.@__BuildControl__bctrl_95();
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/BonusRoundJavaScript.ascx"
            @__parser.AddParsedSubObject(this._bctrl_95);
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/BonusRoundJavaScript.ascx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\").val() != \"\") {\n                check_code();\n            }\n        });\n    </s" +
                        "cript>"));
            
            #line default
            #line hidden
        }
        
        private global::System.Web.UI.DataBoundLiteralControl @__BuildControl__bctrl_86() {
            global::System.Web.UI.DataBoundLiteralControl @__ctrl;
            
            #line 2 "/home/runner/workspace/RobloxWebSite/UserControls/BonusRoundJavaScript.ascx"
            @__ctrl = new global::System.Web.UI.DataBoundLiteralControl(0, 1);
            
            #line default
            #line hidden
            
            #line 2 "/home/runner/workspace/RobloxWebSite/UserControls/BonusRoundJavaScript.ascx"
            this._bctrl_86 = @__ctrl;
            
            #line default
            #line hidden
            @__ctrl.DataBinding += new System.EventHandler(this.@__DataBind__bctrl_86);
            return @__ctrl;
        }
        
        public void @__DataBind__bctrl_86(object sender, System.EventArgs e) {
            System.Web.UI.Control Container;
            System.Web.UI.DataBoundLiteralControl target;
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/BonusRoundJavaScript.ascx"
            target = ((System.Web.UI.DataBoundLiteralControl)(sender));
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/BonusRoundJavaScript.ascx"
            Container = ((System.Web.UI.Control)(target.BindingContainer));
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/BonusRoundJavaScript.ascx"
            target.SetDataBoundString(0, System.Convert.ToString(Parent.FindControl("referral_code").ClientID ));
            
            #line default
            #line hidden
        }
        
        private global::System.Web.UI.DataBoundLiteralControl @__BuildControl__bctrl_87() {
            global::System.Web.UI.DataBoundLiteralControl @__ctrl;
            
            #line 2 "/home/runner/workspace/RobloxWebSite/UserControls/BonusRoundJavaScript.ascx"
            @__ctrl = new global::System.Web.UI.DataBoundLiteralControl(0, 1);
            
            #line default
            #line hidden
            
            #line 2 "/home/runner/workspace/RobloxWebSite/UserControls/BonusRoundJavaScript.ascx"
            this._bctrl_87 = @__ctrl;
            
            #line default
            #line hidden
            @__ctrl.DataBinding += new System.EventHandler(this.@__DataBind__bctrl_87);
            return @__ctrl;
        }
        
        public void @__DataBind__bctrl_87(object sender, System.EventArgs e) {
            System.Web.UI.Control Container;
            System.Web.UI.DataBoundLiteralControl target;
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/BonusRoundJavaScript.ascx"
            target = ((System.Web.UI.DataBoundLiteralControl)(sender));
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/BonusRoundJavaScript.ascx"
            Container = ((System.Web.UI.Control)(target.BindingContainer));
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/BonusRoundJavaScript.ascx"
            target.SetDataBoundString(0, System.Convert.ToString(Parent.FindControl("referral_code").ClientID ));
            
            #line default
            #line hidden
        }
        
        private global::System.Web.UI.DataBoundLiteralControl @__BuildControl__bctrl_88() {
            global::System.Web.UI.DataBoundLiteralControl @__ctrl;
            
            #line 2 "/home/runner/workspace/RobloxWebSite/UserControls/BonusRoundJavaScript.ascx"
            @__ctrl = new global::System.Web.UI.DataBoundLiteralControl(0, 1);
            
            #line default
            #line hidden
            
            #line 2 "/home/runner/workspace/RobloxWebSite/UserControls/BonusRoundJavaScript.ascx"
            this._bctrl_88 = @__ctrl;
            
            #line default
            #line hidden
            @__ctrl.DataBinding += new System.EventHandler(this.@__DataBind__bctrl_88);
            return @__ctrl;
        }
        
        public void @__DataBind__bctrl_88(object sender, System.EventArgs e) {
            System.Web.UI.Control Container;
            System.Web.UI.DataBoundLiteralControl target;
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/BonusRoundJavaScript.ascx"
            target = ((System.Web.UI.DataBoundLiteralControl)(sender));
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/BonusRoundJavaScript.ascx"
            Container = ((System.Web.UI.Control)(target.BindingContainer));
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/BonusRoundJavaScript.ascx"
            target.SetDataBoundString(0, System.Convert.ToString( StaticContent.GetUrl("~/images/cross.png") ));
            
            #line default
            #line hidden
        }
        
        private global::System.Web.UI.DataBoundLiteralControl @__BuildControl__bctrl_89() {
            global::System.Web.UI.DataBoundLiteralControl @__ctrl;
            
            #line 2 "/home/runner/workspace/RobloxWebSite/UserControls/BonusRoundJavaScript.ascx"
            @__ctrl = new global::System.Web.UI.DataBoundLiteralControl(0, 1);
            
            #line default
            #line hidden
            
            #line 2 "/home/runner/workspace/RobloxWebSite/UserControls/BonusRoundJavaScript.ascx"
            this._bctrl_89 = @__ctrl;
            
            #line default
            #line hidden
            @__ctrl.DataBinding += new System.EventHandler(this.@__DataBind__bctrl_89);
            return @__ctrl;
        }
        
        public void @__DataBind__bctrl_89(object sender, System.EventArgs e) {
            System.Web.UI.Control Container;
            System.Web.UI.DataBoundLiteralControl target;
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/BonusRoundJavaScript.ascx"
            target = ((System.Web.UI.DataBoundLiteralControl)(sender));
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/BonusRoundJavaScript.ascx"
            Container = ((System.Web.UI.Control)(target.BindingContainer));
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/BonusRoundJavaScript.ascx"
            target.SetDataBoundString(0, System.Convert.ToString( StaticContent.GetUrl("~/images/accept.png") ));
            
            #line default
            #line hidden
        }
        
        private global::System.Web.UI.DataBoundLiteralControl @__BuildControl__bctrl_90() {
            global::System.Web.UI.DataBoundLiteralControl @__ctrl;
            
            #line 2 "/home/runner/workspace/RobloxWebSite/UserControls/BonusRoundJavaScript.ascx"
            @__ctrl = new global::System.Web.UI.DataBoundLiteralControl(0, 1);
            
            #line default
            #line hidden
            
            #line 2 "/home/runner/workspace/RobloxWebSite/UserControls/BonusRoundJavaScript.ascx"
            this._bctrl_90 = @__ctrl;
            
            #line default
            #line hidden
            @__ctrl.DataBinding += new System.EventHandler(this.@__DataBind__bctrl_90);
            return @__ctrl;
        }
        
        public void @__DataBind__bctrl_90(object sender, System.EventArgs e) {
            System.Web.UI.Control Container;
            System.Web.UI.DataBoundLiteralControl target;
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/BonusRoundJavaScript.ascx"
            target = ((System.Web.UI.DataBoundLiteralControl)(sender));
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/BonusRoundJavaScript.ascx"
            Container = ((System.Web.UI.Control)(target.BindingContainer));
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/BonusRoundJavaScript.ascx"
            target.SetDataBoundString(0, System.Convert.ToString(Parent.FindControl("referral_code").ClientID ));
            
            #line default
            #line hidden
        }
        
        private global::System.Web.UI.DataBoundLiteralControl @__BuildControl__bctrl_91() {
            global::System.Web.UI.DataBoundLiteralControl @__ctrl;
            
            #line 2 "/home/runner/workspace/RobloxWebSite/UserControls/BonusRoundJavaScript.ascx"
            @__ctrl = new global::System.Web.UI.DataBoundLiteralControl(0, 1);
            
            #line default
            #line hidden
            
            #line 2 "/home/runner/workspace/RobloxWebSite/UserControls/BonusRoundJavaScript.ascx"
            this._bctrl_91 = @__ctrl;
            
            #line default
            #line hidden
            @__ctrl.DataBinding += new System.EventHandler(this.@__DataBind__bctrl_91);
            return @__ctrl;
        }
        
        public void @__DataBind__bctrl_91(object sender, System.EventArgs e) {
            System.Web.UI.Control Container;
            System.Web.UI.DataBoundLiteralControl target;
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/BonusRoundJavaScript.ascx"
            target = ((System.Web.UI.DataBoundLiteralControl)(sender));
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/BonusRoundJavaScript.ascx"
            Container = ((System.Web.UI.Control)(target.BindingContainer));
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/BonusRoundJavaScript.ascx"
            target.SetDataBoundString(0, System.Convert.ToString( StaticContent.GetUrl("~/images/waiting.gif") ));
            
            #line default
            #line hidden
        }
        
        private global::System.Web.UI.DataBoundLiteralControl @__BuildControl__bctrl_92() {
            global::System.Web.UI.DataBoundLiteralControl @__ctrl;
            
            #line 2 "/home/runner/workspace/RobloxWebSite/UserControls/BonusRoundJavaScript.ascx"
            @__ctrl = new global::System.Web.UI.DataBoundLiteralControl(0, 1);
            
            #line default
            #line hidden
            
            #line 2 "/home/runner/workspace/RobloxWebSite/UserControls/BonusRoundJavaScript.ascx"
            this._bctrl_92 = @__ctrl;
            
            #line default
            #line hidden
            @__ctrl.DataBinding += new System.EventHandler(this.@__DataBind__bctrl_92);
            return @__ctrl;
        }
        
        public void @__DataBind__bctrl_92(object sender, System.EventArgs e) {
            System.Web.UI.Control Container;
            System.Web.UI.DataBoundLiteralControl target;
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/BonusRoundJavaScript.ascx"
            target = ((System.Web.UI.DataBoundLiteralControl)(sender));
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/BonusRoundJavaScript.ascx"
            Container = ((System.Web.UI.Control)(target.BindingContainer));
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/BonusRoundJavaScript.ascx"
            target.SetDataBoundString(0, System.Convert.ToString( StaticContent.GetUrl("~/images/cross.png") ));
            
            #line default
            #line hidden
        }
        
        private global::System.Web.UI.DataBoundLiteralControl @__BuildControl__bctrl_93() {
            global::System.Web.UI.DataBoundLiteralControl @__ctrl;
            
            #line 2 "/home/runner/workspace/RobloxWebSite/UserControls/BonusRoundJavaScript.ascx"
            @__ctrl = new global::System.Web.UI.DataBoundLiteralControl(0, 1);
            
            #line default
            #line hidden
            
            #line 2 "/home/runner/workspace/RobloxWebSite/UserControls/BonusRoundJavaScript.ascx"
            this._bctrl_93 = @__ctrl;
            
            #line default
            #line hidden
            @__ctrl.DataBinding += new System.EventHandler(this.@__DataBind__bctrl_93);
            return @__ctrl;
        }
        
        public void @__DataBind__bctrl_93(object sender, System.EventArgs e) {
            System.Web.UI.Control Container;
            System.Web.UI.DataBoundLiteralControl target;
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/BonusRoundJavaScript.ascx"
            target = ((System.Web.UI.DataBoundLiteralControl)(sender));
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/BonusRoundJavaScript.ascx"
            Container = ((System.Web.UI.Control)(target.BindingContainer));
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/BonusRoundJavaScript.ascx"
            target.SetDataBoundString(0, System.Convert.ToString(Parent.FindControl("EmailTextBox").ClientID ));
            
            #line default
            #line hidden
        }
        
        private global::System.Web.UI.DataBoundLiteralControl @__BuildControl__bctrl_94() {
            global::System.Web.UI.DataBoundLiteralControl @__ctrl;
            
            #line 2 "/home/runner/workspace/RobloxWebSite/UserControls/BonusRoundJavaScript.ascx"
            @__ctrl = new global::System.Web.UI.DataBoundLiteralControl(0, 1);
            
            #line default
            #line hidden
            
            #line 2 "/home/runner/workspace/RobloxWebSite/UserControls/BonusRoundJavaScript.ascx"
            this._bctrl_94 = @__ctrl;
            
            #line default
            #line hidden
            @__ctrl.DataBinding += new System.EventHandler(this.@__DataBind__bctrl_94);
            return @__ctrl;
        }
        
        public void @__DataBind__bctrl_94(object sender, System.EventArgs e) {
            System.Web.UI.Control Container;
            System.Web.UI.DataBoundLiteralControl target;
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/BonusRoundJavaScript.ascx"
            target = ((System.Web.UI.DataBoundLiteralControl)(sender));
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/BonusRoundJavaScript.ascx"
            Container = ((System.Web.UI.Control)(target.BindingContainer));
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/BonusRoundJavaScript.ascx"
            target.SetDataBoundString(0, System.Convert.ToString(Parent.FindControl("EmailTextBox").ClientID ));
            
            #line default
            #line hidden
        }
        
        private global::System.Web.UI.DataBoundLiteralControl @__BuildControl__bctrl_95() {
            global::System.Web.UI.DataBoundLiteralControl @__ctrl;
            
            #line 2 "/home/runner/workspace/RobloxWebSite/UserControls/BonusRoundJavaScript.ascx"
            @__ctrl = new global::System.Web.UI.DataBoundLiteralControl(0, 1);
            
            #line default
            #line hidden
            
            #line 2 "/home/runner/workspace/RobloxWebSite/UserControls/BonusRoundJavaScript.ascx"
            this._bctrl_95 = @__ctrl;
            
            #line default
            #line hidden
            @__ctrl.DataBinding += new System.EventHandler(this.@__DataBind__bctrl_95);
            return @__ctrl;
        }
        
        public void @__DataBind__bctrl_95(object sender, System.EventArgs e) {
            System.Web.UI.Control Container;
            System.Web.UI.DataBoundLiteralControl target;
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/BonusRoundJavaScript.ascx"
            target = ((System.Web.UI.DataBoundLiteralControl)(sender));
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/BonusRoundJavaScript.ascx"
            Container = ((System.Web.UI.Control)(target.BindingContainer));
            
            #line default
            #line hidden
            
            #line 1 "/home/runner/workspace/RobloxWebSite/UserControls/BonusRoundJavaScript.ascx"
            target.SetDataBoundString(0, System.Convert.ToString(Parent.FindControl("referral_code").ClientID ));
            
            #line default
            #line hidden
        }
        
        protected override void FrameworkInitialize() {
            base.FrameworkInitialize();
            this.SetStringResourcePointer(global::ASP.usercontrols_bonusroundjavascript_ascx.@__stringResource, 0);
            this.@__BuildControlTree(this);
        }
    }
}
