#pragma checksum "/home/runner/workspace/RobloxWebSite/UserControls/ItemPurchaseAjax.ascx" "{406ea660-64cf-4c82-b6f0-42d48172a799}" "D899E81AAF0C5C12BA67004F28648FCB"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
    using System;
    using System.Collections;
    using System.Collections.Specialized;
    using System.Configuration;
    using System.Text;
    using System.Text.RegularExpressions;
    using System.Web;
    using System.Web.Caching;
    using System.Web.SessionState;
    using System.Web.Security;
    using System.Web.Profile;
    using System.Web.UI;
    using System.Web.UI.WebControls;
    using System.Web.UI.HtmlControls;
    using Roblox.Website;
    using Roblox.Web.Code;
    
    
    public class usercontrols_itempurchaseajax_ascx : global::Roblox.Website.UserControls.ItemPurchaseAjax {
        
        private static bool @__initialized = false;
        
        private static object @__stringResource = null;
        
        private static int @__autoHandlers;
        
        public usercontrols_itempurchaseajax_ascx() {
            ((global::Roblox.Website.UserControls.ItemPurchaseAjax)(this)).AppRelativeVirtualPath = "~/UserControls/ItemPurchaseAjax.ascx";
            if ((global::ASP.usercontrols_itempurchaseajax_ascx.@__initialized == false)) {
                global::ASP.usercontrols_itempurchaseajax_ascx.@__initialized = true;
            }
        }
        
        [System.Obsolete()]
        protected override int AutoHandlers {
            get {
                return ASP.usercontrols_itempurchaseajax_ascx.@__autoHandlers;
            }
            set {
                ASP.usercontrols_itempurchaseajax_ascx.@__autoHandlers = value;
            }
        }
        
        protected System.Web.HttpApplication ApplicationInstance {
            get {
                return ((System.Web.HttpApplication)(this.Context.ApplicationInstance));
            }
        }
        
        protected System.Web.Profile.DefaultProfile Profile {
            get {
                return ((System.Web.Profile.DefaultProfile)(this.Context.Profile));
            }
        }
        
        private void @__RenderTree(System.Web.UI.HtmlTextWriter @__output, System.Web.UI.Control parameterContainer) {
            @__output.Write("<div id=\"ItemPurchaseAjaxData\"\n        data-authenticateduser-isnull=\"");
            
            #line 3 "/home/runner/workspace/RobloxWebSite/UserControls/ItemPurchaseAjax.ascx"
            @__output.Write( Model.AuthenticatedUserIsNull );
            
            #line default
            #line hidden
            @__output.Write("\"\n        data-user-balance-robux=\"");
            
            #line 3 "/home/runner/workspace/RobloxWebSite/UserControls/ItemPurchaseAjax.ascx"
            @__output.Write( Model.UserBalanceRobux );
            
            #line default
            #line hidden
            @__output.Write("\"\"\n        data-user-balance-tickets=\"");
            
            #line 3 "/home/runner/workspace/RobloxWebSite/UserControls/ItemPurchaseAjax.ascx"
            @__output.Write( Model.UserBalanceTickets );
            
            #line default
            #line hidden
            @__output.Write("\"\"\n        data-user-bc=\"");
            
            #line 7 "/home/runner/workspace/RobloxWebSite/UserControls/ItemPurchaseAjax.ascx"
            @__output.Write( Model.UserBC );
            
            #line default
            #line hidden
            @__output.Write("\"\"\n        data-continueshopping-url=\"");
            
            #line 8 "/home/runner/workspace/RobloxWebSite/UserControls/ItemPurchaseAjax.ascx"
            @__output.Write( Model.ContinueShoppingUrl );
            
            #line default
            #line hidden
            @__output.Write("\"\"\n        data-imageurl=\"");
            
            #line 9 "/home/runner/workspace/RobloxWebSite/UserControls/ItemPurchaseAjax.ascx"
            @__output.Write( Model.ImageUrl );
            
            #line default
            #line hidden
            @__output.Write("\"\n        data-alerturl=\"");
            
            #line 10 "/home/runner/workspace/RobloxWebSite/UserControls/ItemPurchaseAjax.ascx"
            @__output.Write( Model.AlertUrl );
            
            #line default
            #line hidden
            @__output.Write("\"\n        data-builderscluburl=\"");
            
            #line 11 "/home/runner/workspace/RobloxWebSite/UserControls/ItemPurchaseAjax.ascx"
            @__output.Write( Model.BuildersClubUrl );
            
            #line default
            #line hidden
            @__output.Write("\"\"></div>\n\n    <div id=\"ProcessingView\" style=\"display:none\">\n        <div class=" +
                    "\"ProcessingModalBody\">\n            <p style=\"margin:0px\"><img src=\'");
            
            #line 15 "/home/runner/workspace/RobloxWebSite/UserControls/ItemPurchaseAjax.ascx"
            @__output.Write( StaticContent.GetUrl("~/Images/Spinners/waiting.gif") );
            
            #line default
            #line hidden
            @__output.Write("\' alt=\"Processing...\" /></p>\n            <p style=\"margin:7px 0px\">Processing Tra" +
                    "nsaction</p>\n        </div>\n    </div>\n    \n    <script type=\"text/javascript\">\n" +
                    "        //<sl:translate>\n        Roblox.ItemPurchase.strings = {\n            ins" +
                    "ufficientFundsTitle : \"Insufficient Funds\",\n            insufficientFundsText : " +
                    "\"You need {0} more to purchase this item.\",\n            cancelText : \"Cancel\",\n " +
                    "           okText : \"OK\",\n            buyText : \"Buy\",\n            buyTextLower " +
                    ": \"buy\",\n            tradeCurrencyText : \"Trade Currency\",\n            priceChan" +
                    "geTitle : \"Item Price Has Changed\",\n            priceChangeText : \"While you wer" +
                    "e shopping, the price of this item changed from {0} to {1}.\",\n            buyNow" +
                    "Text : \"Buy Now\",\n            buyAccessText: \"Buy Access\",\n            buildersC" +
                    "lubOnlyTitle : \"{0} Only\",\n            buildersClubOnlyText : \"You need {0} to b" +
                    "uy this item!\",\n            buyItemTitle : \"Buy Item\",\n            buyItemText :" +
                    " \"Would you like to {0} {5}the {1} {2} from {3} for {4}?\",\n            balanceTe" +
                    "xt : \"Your balance after this transaction will be {0}\",\n            freeText : \"" +
                    "Free\",\n            purchaseCompleteTitle : \"Purchase Complete!\",\n            pur" +
                    "chaseCompleteText : \"You have successfully {0} {5}the {1} {2} from {3} for {4}.\"" +
                    ",\n            continueShoppingText : \"Return to Profile\",\n            customizeC" +
                    "haracterText : \"Customize Character\",\n            orText : \"or\",\n            ren" +
                    "tText : \"rent\",\n            accessText: \"access to \"\n        }\n    //</sl:transl" +
                    "ate>\n    </script>\n");
        }
        
        private void @__BuildControlTree(usercontrols_itempurchaseajax_ascx @__ctrl) {
            @__ctrl.SetRenderMethodDelegate(new System.Web.UI.RenderMethod(this.@__RenderTree));
        }
        
        protected override void FrameworkInitialize() {
            base.FrameworkInitialize();
            this.SetStringResourcePointer(global::ASP.usercontrols_itempurchaseajax_ascx.@__stringResource, 0);
            this.@__BuildControlTree(this);
        }
    }
}
